#!/usr/bin/env node
// Read-only diagnosis after the first environment PATCH triggered a rebuild.
// Never changes or clears the stopped mutation journal.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const c=require('./production_phase5a_common.cjs'),reads=require('./production_read_retry.cjs'),p3a=require('./deploy_production_phase3a.cjs');
async function main(){
 const journalBytes=fs.readFileSync(path.join(c.DIR,'execution.json')),j=c.load('execution'),b=c.load('baseline');assert.equal(j.status,'STOPPED');assert.equal(j.attempts.length,1);assert.equal(j.attempts[0].method,'PATCH');assert.equal(j.attempts[0].status,'CONFIRMED');assert(j.attempts[0].resource.includes('/functions/aiCreateSource?updateMask=serviceConfig.environmentVariables'));assert.equal(j.public.length,0);assert.equal(j.queueResumed,false);
 const a=await c.snapshot();c.save('stopped/current',a);const proof={status:'STARTED',mutationCount:0,priorMutationCount:1,functions:[],protectedResourcesUnchanged:false,queue:'PAUSED',scheduler:'PAUSED',publicInvokerAdded:false,phase5bStarted:false};
 for(const f of a.functions){
  const n=f.name.split('/').pop(),gen1=f.environment==='GEN_1',api=gen1?'https://cloudfunctions.googleapis.com/v1/':c.G,full=gen1?await c.read(api+f.name):await c.read(c.G+f.name);
  const d=await c.read(api+f.name+':generateDownloadUrl','POST',gen1?{versionId:full.versionId}:{}),u=new URL(d.downloadUrl);assert(u.protocol==='https:'&&(u.hostname==='storage.googleapis.com'||u.hostname.endsWith('.storage.googleapis.com'))&&!u.username&&!u.password&&!u.port);
  const {data:bytes}=await reads.read(u,{}, {bytes:true,sourceName:'phase5a_stop_'+n});assert(bytes.length<=100*1024*1024);const out=path.join(c.DIR,'stopped',n+'-source.zip');fs.writeFileSync(out,bytes,{mode:0o600});
  const files=p3a.sourceManifest(out),expected=p3a.sourceManifest(path.join(c.DIR,'preflight',n+'-source.zip'));assert.deepEqual(files,expected,'Installed full source changed '+n);
  assert.deepEqual(c.p3b.safeMetadata(await c.read(c.G+f.name)),f,'Function changed during audit '+n);
  if(c.ALL.includes(n)){assert.equal(p3a.hash(files),c.SHA);assert.equal(full.state,'ACTIVE');assert.equal(full.buildConfig.runtime,'nodejs22');assert.equal(full.serviceConfig.serviceAccountEmail,c.SA);assert.equal(full.serviceConfig.environmentVariables.AI_FIRESTORE_DATABASE_ID,c.DB);assert.equal(full.serviceConfig.environmentVariables.AI_SHARING_ENABLED,'false');assert.equal(full.serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS,JSON.stringify(n==='aiCreateSource'?c.operator().allowedUIDs:[]));}
  proof.functions.push({function:n,sourceSha256:p3a.hash(files),fullSourceUnchanged:true,state:full.state,allowedUIDCount:c.ALL.includes(n)?(n==='aiCreateSource'?1:0):undefined});c.save('stopped/result',proof);console.log(n+': stopped-state installed full source unchanged PASS');
 }
 const old=b.functions.find(f=>f.name.endsWith('/aiCreateSource')),fresh=a.functions.find(f=>f.name===old.name),compared=structuredClone(a),actual=compared.functions.find(f=>f.name===old.name);
 const build=structuredClone(fresh.buildConfig);assert.notEqual(build.build,old.buildConfig.build);assert.notEqual(build.source.storageSource.generation,old.buildConfig.source.storageSource.generation);assert.notEqual(build.sourceProvenance.resolvedStorageSource.generation,old.buildConfig.sourceProvenance.resolvedStorageSource.generation);
 proof.rebuildMetadata={beforeBuild:old.buildConfig.build,afterBuild:build.build,beforeGeneration:old.buildConfig.source.storageSource.generation,afterGeneration:build.source.storageSource.generation,fullSourceUnchanged:true,autoRebuildObservedAfterEnvironmentOnlyPatch:true};
 build.build=old.buildConfig.build;build.source.storageSource.generation=old.buildConfig.source.storageSource.generation;build.sourceProvenance.resolvedStorageSource.generation=old.buildConfig.sourceProvenance.resolvedStorageSource.generation;assert.deepEqual(build,old.buildConfig,'Unexpected build configuration drift');
 actual.buildConfig=old.buildConfig;actual.updateTime=old.updateTime;actual.serviceConfig.environmentVariables=old.serviceConfig.environmentVariables;actual.serviceConfig.revision=old.serviceConfig.revision;
 c.protectedState(b,compared,{configured:[],public:[],queueResumed:false});assert.equal(a.functions.length,25);assert(a.resources.scheduler.data.jobs.every(x=>x.state==='PAUSED'&&!x.lastAttemptTime));
 for(const n of c.CALLABLES)assert(!(a.runIAM[n].bindings||[]).some(x=>x.members.some(m=>['allUsers','allAuthenticatedUsers'].includes(m))));
 const changed=await c.read(c.G+fresh.name);assert.deepEqual(c.p3b.safeMetadata(changed),fresh);assert.equal(c.metadataHash({...changed.serviceConfig.environmentVariables,AI_INPUT_ALLOWED_UIDS:'[]'}),old.serviceConfig.environmentVariables.sha256,'Unapproved environment change');for(const url of [changed.serviceConfig.uri,`https://${c.R}-${c.P}.cloudfunctions.net/aiCreateSource`]){const {response}=await reads.read(url,{}, {discard:true,allowStatuses:[401,403]});assert([401,403].includes(response.status));}
 assert.deepEqual(fs.readFileSync(path.join(c.DIR,'execution.json')),journalBytes);proof.status='PHASE5A_STOPPED_REBUILD_GUARD';proof.protectedResourcesUnchanged=true;proof.other24FunctionsUnchanged=true;proof.legacy13Unchanged=true;proof.callablesStillPrivate=true;proof.installedSourceChecks=25;proof.sourceModificationDetected=false;proof.userE2ENotStarted=true;proof.disposableAuthStatus=c.load('outsider-registry').status;proof.completedAt=new Date().toISOString();c.save('stopped/result',proof);
 console.log('STOPPED read-only audit PASS: 25 installed manifests unchanged; one env-only native rebuild; other24 Functions/protected resources unchanged; all Callables private; queue/Scheduler PAUSED; no E2E or further mutation');
}
if(require.main===module)main().catch(e=>{c.save('stopped/error',{status:'AUDIT_FAILED',error:c.masked(e.message),mutationCount:0});console.error('STOP audit: '+c.masked(e.message));process.exitCode=1;});
