#!/usr/bin/env node
// Explicitly approved four-resource source-only rollout. Never retry a mutation,
// rewrite env/IAM, deploy other exports, automatically rollback or resume on failure.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const d=require('./deploy_production_visual_router.cjs'),c=require('./production_phase5a_common.cjs'),p=require('./production_recognition_review.cjs'),r=require('./visual_latency_review.cjs'),reads=require('./production_read_retry.cjs'),{sourceManifest}=require('./deploy_production_phase3a.cjs');
const DIR=path.join(c.ROOT,'build/production-visual-latency-20261009-resume1'),G='https://cloudfunctions.googleapis.com/v2/',Q='https://cloudtasks.googleapis.com/v2/'+c.Q;
const ORDER=['aiProcessSource','aiCompleteSource','aiGetSource','aiGetEvidence'],MODULES=r.MODULES,hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function save(n,x){fs.mkdirSync(DIR,{recursive:true,mode:0o700});fs.writeFileSync(path.join(DIR,n+'.json'),JSON.stringify(x,null,2),{mode:0o600});}const load=n=>JSON.parse(fs.readFileSync(path.join(DIR,n+'.json')));
function validateMutation(url,method,body,kind,name){assert.equal(method,kind==='source'?'PATCH':'POST');assert(kind==='pause'&&url===Q+':pause'||kind==='resume'&&url===Q+':resume'||kind==='staging'&&ORDER.includes(name)&&url===G+c.parent+'/functions:generateUploadUrl'||kind==='source'&&ORDER.includes(name)&&url===G+c.parent+'/functions/'+name+'?updateMask=buildConfig.source','Unapproved mutation');if(kind==='source'){assert.deepEqual(Object.keys(body).sort(),['buildConfig','name']);assert.equal(body.name,c.parent+'/functions/'+name);assert.deepEqual(Object.keys(body.buildConfig),['source']);assert.deepEqual(Object.keys(body.buildConfig.source),['storageSource']);}else assert.deepEqual(body,{});}
function delta(before,after){assert(Object.keys(before).every(k=>after[k]),'Original source file removed');const changed=Object.keys(after).filter(k=>before[k]!==after[k]);assert.deepEqual(changed.sort(),[...MODULES].sort(),'Only five reviewed runtime modules may change/add');return changed;}
function artifact(name){const a=load('artifact-'+name);assert.deepEqual(a.changedModules.sort(),[...MODULES].sort());assert.equal(hash(sourceManifest(path.join(DIR,'candidate-'+name+'.zip'))),a.manifest);delta(a.beforeFiles,a.files);for(const mod of MODULES)assert.equal(a.files[mod],sha(fs.readFileSync(path.join(c.ROOT,'functions',mod))),'Local compiled artifact drift');return a;}
async function source(f,label){const old=await d.read(G+f.name),gen1=f.environment==='GEN_1',base='https://cloudfunctions.googleapis.com/'+(gen1?'v1/':'v2/'),issue=await d.read(base+f.name+':generateDownloadUrl','POST',gen1?{versionId:(await d.read(base+f.name)).versionId}:{}),u=new URL(issue.downloadUrl);assert(u.protocol==='https:'&&(u.hostname==='storage.googleapis.com'||u.hostname.endsWith('.storage.googleapis.com'))&&!u.username&&!u.password&&!u.port);const {data:bytes}=await reads.read(u,{}, {bytes:true,sourceName:'latency_'+f.name.split('/').at(-1)});assert(bytes.length<100*1024*1024);const n=f.name.split('/').at(-1),file=path.join(DIR,'sources',label+'-'+n+'.zip');fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});fs.writeFileSync(file,bytes,{mode:0o600});assert.deepEqual(await d.read(G+f.name),old,'Function changed during SourceCodeGet');const files=sourceManifest(file);return {files,sha256:hash(files),zipSha256:sha(bytes)};}
async function drain(){d.assertQueueDrained(await d.read(d.queueStatsURL()));let page,count=0;do{const x=await d.read(`https://firestore.googleapis.com/v1/projects/${c.P}/databases/${c.DB}/documents/aiSources?pageSize=100&mask.fieldPaths=status&mask.fieldPaths=leaseToken&mask.fieldPaths=leaseUntil`+(page?'&pageToken='+encodeURIComponent(page):''),'GET',undefined,{boundedPage:true});for(const doc of x.documents||[]){count++;const f=doc.fields||{};assert(!['extracting','indexing'].includes(f.status?.stringValue)&&!f.leaseToken?.stringValue&&Number(f.leaseUntil?.integerValue||f.leaseUntil?.doubleValue||0)<=Date.now(),'Active worker lease');}page=x.nextPageToken;}while(page);save('drain',{at:new Date().toISOString(),activeSourceLeases:0,concurrentDispatches:0,scannedSources:count});}
async function main(action,name){assert(['preflight','pause','update','audit','resume'].includes(action));if(action==='update')assert(ORDER.includes(name));else assert(!name);assert.equal(execFileSync('git',['branch','--show-current'],{cwd:c.ROOT,encoding:'utf8'}).trim(),'codex/ai-recognition-comparison-lab');r.plan();fs.mkdirSync(DIR,{recursive:true,mode:0o700});const j=fs.existsSync(path.join(DIR,'execution.json'))?load('execution'):{status:'STARTED',attempts:[],updated:[],after:{},paused:false,resumed:false};assert.notEqual(j.status,'STOPPED','Stopped rollout requires user review');const persist=()=>save('execution',j);
 async function mutation(url,method,body,kind){validateMutation(url,method,body,kind,name);assert(!j.attempts.some(x=>x.kind===kind&&x.name===(name||null)),'Mutation replay prohibited');const ev={kind,name:name||null,status:'UNKNOWN',at:new Date().toISOString()};j.attempts.push(ev);persist();const resp=await fetch(url,{method,redirect:'error',headers:{Authorization:'Bearer '+await c.cloud.oauth(),'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(45000)}),x=await resp.json().catch(()=>({}));ev.httpStatus=resp.status;ev.status=resp.ok?'CONFIRMED':'HTTP_ERROR';persist();assert(resp.ok,kind+' HTTP '+resp.status);return x;}
 try{
 if(action==='preflight'){assert.equal(j.status,'STARTED');assert(!fs.existsSync(path.join(DIR,'baseline.json')),'Do not overwrite a fresh baseline');const b=await d.snapshot(),raw=await d.rawFunctions();d.policyChecks(b,raw,'RUNNING');const prior=JSON.parse(fs.readFileSync(path.join(c.ROOT,'build/production-image-router-20261009/git-save-readonly.json')));d.protectedCheck(prior,b,{resumed:true,after:{}});save('baseline',b);save('baseline-functions.private',raw);await d.pilotAuth(raw);const proof={};
  const oldProof=JSON.parse(fs.readFileSync(path.join(c.ROOT,'build/production-image-router-20261009/baseline-sources.json'))),workerReview=JSON.parse(fs.readFileSync(path.join(c.ROOT,'build/image-router-production-review/review.json')));
  for(let i=0;i<raw.length;i+=3){const xs=await Promise.allSettled(raw.slice(i,i+3).map(async f=>{const n=f.name.split('/').at(-1),s=await source(f,'before');assert.deepEqual(s.files,n==='aiProcessSource'?workerReview.afterFiles:oldProof[n].files,'Drift from stable source '+n);return [n,s];}));for(const x of xs){if(x.status==='rejected')throw x.reason;proof[x.value[0]]=x.value[1];}console.log('Fresh installed sources '+Math.min(i+3,raw.length)+'/25 PASS');}save('baseline-sources',proof);
  for(const n of ORDER){const before=proof[n].files;assert.equal(before['lib/ai/recognition.js'],sha(fs.readFileSync(path.join(c.ROOT,'functions/lib/ai/recognition.js'))),'Grounded prompt/model drift');for(const file of Object.keys(before))assert(!/(^|\/)(\.env|node_modules|build|credentials|.*\.local\.json)(\/|$|\.)/.test(file),'Private file in original source');
   execFileSync('python3',['-c',`import zipfile,sys,pathlib
src,dst,root,*mods=sys.argv[1:]
with zipfile.ZipFile(src) as z: entries={n:z.read(n) for n in z.namelist() if not n.endswith('/')}
for n in mods: entries[n]=(pathlib.Path(root)/n).read_bytes()
with zipfile.ZipFile(dst,'w',zipfile.ZIP_DEFLATED) as out:
 for n,data in entries.items():
  assert not n.startswith('/') and '..' not in n.split('/')
  out.writestr(n,data)`,path.join(DIR,'sources','before-'+n+'.zip'),path.join(DIR,'candidate-'+n+'.zip'),path.join(c.ROOT,'functions'),...MODULES]);const files=sourceManifest(path.join(DIR,'candidate-'+n+'.zip'));save('artifact-'+n,{files,beforeFiles:before,manifest:hash(files),zipHash:sha(fs.readFileSync(path.join(DIR,'candidate-'+n+'.zip'))),changedModules:delta(before,files)});}
  assert.deepEqual(await d.rawFunctions(),raw);d.protectedCheck(b,await d.snapshot(),j);save('approval',{at:new Date().toISOString(),humanApproved:true,functions:ORDER,baselineHash:hash(b),sourceOnly:true,queuePauseRestoreApproved:true,envIAMSecretChangeApproved:false,cohort:p.cohort(raw.filter(f=>p.FUNCTIONS.includes(f.name.split('/').at(-1))))});j.status='PREFLIGHT_PASS';persist();console.log('PASS fresh25 full-source/protected state; four reviewed artifacts; mutation0');return;
 }
 const b=load('baseline'),approval=load('approval');assert(approval.humanApproved&&approval.sourceOnly);assert.deepEqual(approval.functions,ORDER);assert.equal(approval.baselineHash,hash(b));for(const n of ORDER)artifact(n);
 if(action==='pause'){assert.equal(j.status,'PREFLIGHT_PASS');d.protectedCheck(b,await d.snapshot(),j);await mutation(Q+':pause','POST',{},'pause');j.paused=true;persist();assert.equal((await d.read(Q)).state,'PAUSED');await new Promise(r=>setTimeout(r,15000));await drain();j.status='PAUSED_DRAINED';persist();console.log('PASS queue PAUSED and drained');return;}
 if(action==='update'){assert(j.paused&&!j.resumed);assert.equal(ORDER[j.updated.length],name);const a=artifact(name),start=Date.now();d.protectedCheck(b,await d.snapshot(),j);await drain();const before=await d.read(G+c.parent+'/functions/'+name);assert.deepEqual(before,load('baseline-functions.private').find(f=>f.name===before.name));assert.deepEqual((await source(before,'immediate')).files,a.beforeFiles);
  const issued=await mutation(G+c.parent+'/functions:generateUploadUrl','POST',{},'staging'),u=new URL(issued.uploadUrl);assert(u.protocol==='https:'&&u.hostname==='storage.googleapis.com'&&!u.username&&!u.password&&!u.port);assert(issued.storageSource.bucket.includes(c.N)&&issued.storageSource.bucket.includes(c.R));assert(decodeURIComponent(u.pathname).startsWith('/'+issued.storageSource.bucket+'/'));const ev={kind:'upload',name,status:'UNKNOWN'};assert(!j.attempts.some(x=>x.kind==='upload'&&x.name===name));j.attempts.push(ev);persist();const resp=await fetch(u,{method:'PUT',redirect:'error',headers:{'Content-Type':'application/zip'},body:fs.readFileSync(path.join(DIR,'candidate-'+name+'.zip')),signal:AbortSignal.timeout(45000)});ev.httpStatus=resp.status;ev.status=resp.ok?'CONFIRMED':'HTTP_ERROR';persist();assert(resp.ok,'Gen2 staging HTTP '+resp.status);assert(Date.now()-start<300000,'Immediate preflight expired');assert.deepEqual(await d.read(G+before.name),before);await drain();
  const op=await mutation(G+before.name+'?updateMask=buildConfig.source','PATCH',{name:before.name,buildConfig:{source:{storageSource:issued.storageSource}}},'source');assert(op.name.startsWith(c.parent+'/operations/'));save(name+'-operation',{name:op.name});let done=false;for(let i=0;i<240;i++){const x=await d.read(G+op.name);save(name+'-operation',c.p3b.safeMetadata(x));if(x.done){assert(!x.error,'Operation error '+x.error?.code);done=true;break;}if(i%12===0)console.log(name+' build pending');await new Promise(r=>setTimeout(r,5000));}assert(done,'Operation timeout; no PATCH replay');const after=await d.read(G+before.name),installed=await source(after,'installed');p.postCheck(before,after,installed.files,a.files);j.updated.push(name);j.after[name]=c.p3b.safeMetadata(after);save(name+'-proof',{beforeRevision:before.serviceConfig.revision,afterRevision:after.serviceConfig.revision,beforeSource:load('baseline-sources')[name].sha256,afterSource:installed.sha256,artifact:a.manifest,fullSourceVerified:true,envIAMUnchanged:true});persist();d.protectedCheck(b,await d.snapshot(),j);j.status='VERIFIED_'+name;persist();console.log('PASS '+name+' source/env/runtime/trigger/IAM/protected ('+j.updated.length+'/4)');return;}
 assert.deepEqual(j.updated,ORDER);const snap=await d.snapshot(),raw=await d.rawFunctions();d.protectedCheck(b,snap,j);d.policyChecks(snap,raw,'PAUSED');for(let i=0;i<raw.length;i+=3){const xs=await Promise.allSettled(raw.slice(i,i+3).map(async f=>{const n=f.name.split('/').at(-1),v=await source(f,'final');assert.deepEqual(v.files,ORDER.includes(n)?artifact(n).files:load('baseline-sources')[n].files);}));for(const x of xs)if(x.status==='rejected')throw x.reason;console.log('Final full source '+Math.min(i+3,raw.length)+'/25 PASS');}
 if(action==='audit'){j.status='ALL_POSTCHECK_PASS';save('audit',snap);persist();console.log('PASS four sources and other21 unchanged; protected state unchanged');return;}
 assert.equal(j.status,'ALL_POSTCHECK_PASS');assert(load('auth-gates').status==='PASS');await mutation(Q+':resume','POST',{},'resume');j.resumed=true;persist();assert.equal((await d.read(Q)).state,'RUNNING');const final=await d.snapshot();d.protectedCheck(b,final,j);save('resumed-audit',final);j.status='DEPLOYED_E2E_PENDING';persist();console.log('PASS queue RUNNING restored; E2E pending');
 }catch(e){j.status='STOPPED';j.safeError=e.name;j.safeCategory=e.readRecord||(/^[A-Za-z0-9 :_./()=-]{1,180}$/.test(e.message)?e.message:'assertion details retained privately');persist();console.error('SAFE STOP '+e.name+'; no mutation replay, automatic rollback or queue resume');process.exitCode=1;}}
module.exports={DIR,ORDER,MODULES,load,save,artifact,source,drain,validateMutation,delta};if(require.main===module)main(...process.argv.slice(2)).catch(e=>{console.error('SAFE STOP '+e.name);process.exitCode=1});
