#!/usr/bin/env node
// Explicitly approved one-worker production source update. No other Function,
// env/IAM/Rules/Secret mutation, mutation retry, CREATE/DELETE or rollback.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const d=require('./deploy_production_visual_router.cjs'),c=require('./production_phase5a_common.cjs'),p=require('./production_recognition_review.cjs'),r=require('./production_image_router_review.cjs'),{sourceManifest}=require('./deploy_production_phase3a.cjs');
const DIR=path.join(c.ROOT,'build/production-image-router-20261009'),REVIEW=path.join(c.ROOT,'build/image-router-production-review'),G='https://cloudfunctions.googleapis.com/v2/',F=G+c.parent+'/functions/aiProcessSource',Q='https://cloudtasks.googleapis.com/v2/'+c.Q;
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const save=(n,x)=>{fs.mkdirSync(DIR,{recursive:true,mode:0o700});fs.writeFileSync(path.join(DIR,n+'.json'),JSON.stringify(x,null,2)+'\n',{mode:0o600});};
const load=n=>JSON.parse(fs.readFileSync(path.join(DIR,n+'.json')));
function artifact(){const a=JSON.parse(fs.readFileSync(path.join(REVIEW,'review.json')));r.validatePlan(a);assert.equal(hash(sourceManifest(path.join(REVIEW,'candidate.zip'))),a.afterManifest);r.assertModuleDelta(a.beforeFiles,a.afterFiles);for(const n of r.MODULES)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(c.ROOT,'functions',n))).digest('hex'),a.afterFiles[n],'Local compiled routing differs from reviewed artifact');return a;}
function validateMutation(url,method,body,kind){
 const permitted=kind==='pause'&&method==='POST'&&url===Q+':pause'||kind==='resume'&&method==='POST'&&url===Q+':resume'||kind==='staging'&&method==='POST'&&url===G+c.parent+'/functions:generateUploadUrl'||kind==='source'&&method==='PATCH'&&url===F+'?updateMask=buildConfig.source';assert(permitted,'Mutation outside one-worker allowlist');
 if(kind==='source'){assert.deepEqual(Object.keys(body).sort(),['buildConfig','name']);assert.equal(body.name,c.parent+'/functions/aiProcessSource');assert.deepEqual(Object.keys(body.buildConfig),['source']);assert.deepEqual(Object.keys(body.buildConfig.source),['storageSource']);}else assert.deepEqual(body,{});
}
function policy(s,raw,state){p.cohort(raw.filter(f=>p.FUNCTIONS.includes(f.name.split('/').at(-1))));assert.equal(s.resources.queue.data.state,state);assert(s.resources.scheduler.data.jobs?.length);assert(s.resources.scheduler.data.jobs.every(x=>x.state==='PAUSED'));for(const n of ['aiProcessSource','aiReconcileInputs','aiRejectLateUpload'])assert(!(s.runIAM[n].bindings||[]).some(x=>x.members.some(m=>['allUsers','allAuthenticatedUsers'].includes(m))));}
async function drain(){d.assertQueueDrained(await d.read(d.queueStatsURL()));let page,count=0;do{const x=await d.read(`https://firestore.googleapis.com/v1/projects/${c.P}/databases/${c.DB}/documents/aiSources?pageSize=100&mask.fieldPaths=status&mask.fieldPaths=leaseToken&mask.fieldPaths=leaseUntil`+(page?'&pageToken='+encodeURIComponent(page):''),'GET',undefined,{boundedPage:true});for(const doc of x.documents||[]){count++;const f=doc.fields||{};assert(!['extracting','indexing'].includes(f.status?.stringValue)&&!f.leaseToken?.stringValue&&Number(f.leaseUntil?.integerValue||f.leaseUntil?.doubleValue||0)<=Date.now(),'Active worker source lease: stop without update');}page=x.nextPageToken;}while(page);save('drain',{at:new Date().toISOString(),concurrentDispatches:0,activeSourceLeases:0,scannedSources:count});}
async function main(action){assert(['preflight','pause','update','audit','resume'].includes(action));assert.equal(execFileSync('git',['branch','--show-current'],{cwd:c.ROOT,encoding:'utf8'}).trim(),'codex/ai-recognition-comparison-lab');const a=artifact();fs.mkdirSync(DIR,{recursive:true,mode:0o700});
 const j=fs.existsSync(path.join(DIR,'execution.json'))?load('execution'):{status:'STARTED',attempts:[],paused:false,resumed:false,after:{},updated:[]};assert.notEqual(j.status,'STOPPED','Prior error requires user review');const persist=()=>save('execution',j);
 async function mutation(url,method,body,kind){validateMutation(url,method,body,kind);assert(!j.attempts.some(x=>x.kind===kind),'Mutation replay forbidden');const ev={kind,at:new Date().toISOString(),status:'UNKNOWN'};j.attempts.push(ev);persist();const resp=await fetch(url,{method,redirect:'error',headers:{Authorization:'Bearer '+await c.cloud.oauth(),'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(45000)}),value=await resp.json().catch(()=>({}));ev.httpStatus=resp.status;ev.status=resp.ok?'CONFIRMED':'HTTP_ERROR';persist();assert(resp.ok,kind+' HTTP '+resp.status);return value;}
 try{
 if(action==='preflight'){assert.equal(j.status,'STARTED');assert(!fs.existsSync(path.join(DIR,'baseline.json')),'Fresh baseline only; preserve prior evidence');const b=await d.snapshot(),raw=await d.rawFunctions();policy(b,raw,'RUNNING');const prior=JSON.parse(fs.readFileSync(path.join(c.ROOT,'build/image-router-fix/production-final-read.private.json')));d.protectedCheck(prior.snapshot,b,{resumed:true,after:{}});save('baseline',b);save('baseline-functions.private',raw);
  const proof={};for(let i=0;i<raw.length;i+=3){const xs=await Promise.allSettled(raw.slice(i,i+3).map(async f=>{const n=f.name.split('/').at(-1),x=await d.source(f,'connector-fresh');assert.equal(x.sha256,prior.sourceProof[n].sha256,'Fresh installed source drift '+n);return[n,x];}));for(const x of xs){if(x.status==='rejected')throw x.reason;proof[x.value[0]]=x.value[1];}console.log('Fresh source '+Math.min(i+3,raw.length)+'/25 PASS');}
  assert.deepEqual(proof.aiProcessSource.files,a.beforeFiles);assert.equal(proof.aiProcessSource.sha256,a.beforeManifest);assert.deepEqual(await d.rawFunctions(),raw);d.protectedCheck(b,await d.snapshot(),j);save('baseline-sources',proof);fs.copyFileSync(path.join(REVIEW,'candidate.zip'),path.join(DIR,'candidate.zip'));
  save('approval',{at:new Date().toISOString(),humanApproved:true,functions:['aiProcessSource'],changedModules:r.MODULES,baselineHash:hash(b),artifactHash:a.afterManifest,sourceOnly:true,queuePauseRestoreApproved:true,envIAMSecretChangeApproved:false});j.status='PREFLIGHT_PASS';persist();console.log('PASS fresh full25 source/protected preflight; exact reviewed two-module candidate; production mutation0');return;
 }
 const b=load('baseline'),approval=load('approval');assert(approval.humanApproved);assert.equal(approval.baselineHash,hash(b));assert.equal(approval.artifactHash,a.afterManifest);assert.deepEqual(approval.functions,['aiProcessSource']);assert.equal(hash(sourceManifest(path.join(DIR,'candidate.zip'))),a.afterManifest);
 if(action==='pause'){assert.equal(j.status,'PREFLIGHT_PASS');d.protectedCheck(b,await d.snapshot(),j);await mutation(Q+':pause','POST',{},'pause');j.paused=true;persist();assert.equal((await d.read(Q)).state,'PAUSED');await new Promise(r=>setTimeout(r,15000));await drain();j.status='PAUSED_DRAINED';persist();console.log('PASS queue PAUSED and worker drain');return;}
 if(action==='update'){assert.equal(j.status,'PAUSED_DRAINED');assert(j.paused&&!j.resumed);const start=Date.now();d.protectedCheck(b,await d.snapshot(),j);await drain();const before=await d.read(F);assert.deepEqual(before,load('baseline-functions.private').find(f=>f.name===before.name));assert.deepEqual((await d.source(before,'connector-immediate')).files,a.beforeFiles);
  const issued=await mutation(G+c.parent+'/functions:generateUploadUrl','POST',{},'staging'),u=new URL(issued.uploadUrl);assert.equal(u.protocol,'https:');assert.equal(u.hostname,'storage.googleapis.com');assert(!u.username&&!u.password&&!u.port);assert(issued.storageSource.bucket.includes(c.N)&&issued.storageSource.bucket.includes(c.R));assert(decodeURIComponent(u.pathname).startsWith('/'+issued.storageSource.bucket+'/'));
  const ev={kind:'upload',at:new Date().toISOString(),status:'UNKNOWN'};assert(!j.attempts.some(x=>x.kind==='upload'));j.attempts.push(ev);persist();const resp=await fetch(u,{method:'PUT',redirect:'error',headers:{'Content-Type':'application/zip'},body:fs.readFileSync(path.join(DIR,'candidate.zip')),signal:AbortSignal.timeout(45000)});ev.httpStatus=resp.status;ev.status=resp.ok?'CONFIRMED':'HTTP_ERROR';persist();assert(resp.ok,'Gen2 staging status '+resp.status);assert(Date.now()-start<300000,'Fresh immediate preflight expired');assert.deepEqual(await d.read(F),before);await drain();
  const op=await mutation(F+'?updateMask=buildConfig.source','PATCH',{name:before.name,buildConfig:{source:{storageSource:issued.storageSource}}},'source');assert(op.name.startsWith(c.parent+'/operations/'));save('operation',{name:op.name});let done=false;
  for(let i=0;i<240;i++){const x=await d.read(G+op.name);save('operation',c.p3b.safeMetadata(x));if(x.done){assert(!x.error,'Update operation error '+x.error?.code);done=true;break;}if(i%12===0)console.log('One worker build pending');await new Promise(r=>setTimeout(r,5000));}assert(done,'Operation timeout; no mutation replay');
  const after=await d.read(F),installed=await d.source(after,'connector-installed');p.postCheck(before,after,installed.files,a.afterFiles);j.after.aiProcessSource=c.p3b.safeMetadata(after);j.updated=['aiProcessSource'];save('worker-proof',{beforeRevision:before.serviceConfig.revision,afterRevision:after.serviceConfig.revision,beforeManifest:a.beforeManifest,afterManifest:installed.sha256,fullSourceVerified:true,envIAMUnchanged:true});persist();d.protectedCheck(b,await d.snapshot(),j);j.status='WORKER_VERIFIED';persist();console.log('PASS one worker source/runtime/SA/trigger/env/IAM/protected post-check');return;
 }
 assert.equal(j.status,'WORKER_VERIFIED');assert.deepEqual(j.updated,['aiProcessSource']);const snap=await d.snapshot(),raw=await d.rawFunctions();d.protectedCheck(b,snap,j);policy(snap,raw,'PAUSED');for(let i=0;i<raw.length;i+=3){const xs=await Promise.allSettled(raw.slice(i,i+3).map(async f=>{const n=f.name.split('/').at(-1),v=await d.source(f,'connector-final');assert.deepEqual(v.files,n==='aiProcessSource'?a.afterFiles:load('baseline-sources')[n].files,'Final installed source mismatch '+n);}));for(const x of xs)if(x.status==='rejected')throw x.reason;console.log('Final source '+Math.min(i+3,raw.length)+'/25 PASS');}save('audit',snap);
 if(action==='audit'){save('audit-pass',{at:new Date().toISOString(),full25SourceVerified:true,onlyWorkerUpdated:true,protectedStateUnchanged:true});console.log('PASS all25 full source; other24 unchanged; queue PAUSED; Scheduler PAUSED; sharing OFF');return;}
 assert.equal(action,'resume');assert(load('audit-pass').full25SourceVerified);await mutation(Q+':resume','POST',{},'resume');j.resumed=true;persist();assert.equal((await d.read(Q)).state,'RUNNING');const last=await d.snapshot();d.protectedCheck(b,last,j);save('resumed-audit',last);j.status='DEPLOYED_E2E_PENDING';persist();console.log('PASS production queue RUNNING restored after all post-checks');
 }catch(e){j.status='STOPPED';j.safeError=e.name;j.partialSuccess=j.attempts.some(x=>['pause','source','resume'].includes(x.kind)&&['UNKNOWN','CONFIRMED'].includes(x.status));persist();console.error('SAFE STOP '+e.name+'; no additional mutation or automatic rollback; see private evidence');process.exitCode=1;}
}
module.exports={DIR,G,F,Q,load,save,artifact,validateMutation,policy,drain};if(require.main===module)main(process.argv[2]).catch(e=>{console.error('SAFE STOP '+e.name);process.exitCode=1});
