#!/usr/bin/env node
// Specific provided-page validation in Dev only; all evidence/auth stays ignored.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const c=require('./dev_cloud.cjs'),v=require('./visual_router_dev.cjs'),P=c.PROJECT,D='aogaku-ai',R=c.REGION;
const round=process.env.AOGAKU_EVIDENCE_REVIEW_ROUND||'1';assert(['1','2','3','4','5'].includes(round));
const out=path.join(c.ROOT,'build/evidence-prompt-dev'+(round==='1'?'':'-round'+round)),registry=path.join(out,'registry.json');
const Q=`https://cloudtasks.googleapis.com/v2/projects/${P}/locations/${R}/queues/aiProcessSource`,worker='aiProcessSource',originalPages=[4,15,25,27];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function save(n,x){fs.mkdirSync(out,{recursive:true,mode:0o700});fs.writeFileSync(path.join(out,n),JSON.stringify(x,null,2),{mode:0o600});}
function load(n){return JSON.parse(fs.readFileSync(path.join(out,n)));}
function promptOnly(){
 const file='functions/src/ai/recognition.ts',before=execFileSync('git',['show','HEAD:'+file],{cwd:c.ROOT,encoding:'utf8'}),after=fs.readFileSync(path.join(c.ROOT,file),'utf8');
 const strip=s=>s.replace(/export const IMAGE_INSTRUCTIONS = `[\s\S]*?`;\n/,'PROMPT\n');
 // Prompt may be promoted to system priority; the image data remains user input.
 const normalize=s=>s.replace('messages: [{role: "system", content: IMAGE_INSTRUCTIONS}, {role: "user", content: [\n            {type: "image_url",', 'messages: [{role: "user", content: [\n            {type: "text", text: IMAGE_INSTRUCTIONS}, {type: "image_url",');
 assert.equal(strip(normalize(after)),strip(before),'Only Evidence prompt text/priority may change in provider implementation');
 assert.equal(execFileSync('git',['diff','HEAD','--','functions/src/ai/visualRouter.ts','functions/src/ai/visualExtraction.ts','functions/src/ai/index.ts','functions/src/ai/pricing.ts','functions/package.json','functions/package-lock.json'],{cwd:c.ROOT,encoding:'utf8'}),'','Router/processing contract must remain unchanged');
}
function unchangedExceptWorker(b,a){v.protectedCheck(b,a);for(const f of b.functions.functions)if(!f.name.endsWith('/'+worker))assert.deepEqual(a.functions.functions.find(x=>x.name===f.name),f,'Unselected Dev Function changed');}
async function installed(f,compare){
 const data=await c.request('https://cloudfunctions.googleapis.com/v2/'+f.name+':generateDownloadUrl','POST',{}),u=new URL(data.downloadUrl);assert.equal(u.protocol,'https:');assert(u.hostname==='storage.googleapis.com'||u.hostname.endsWith('.storage.googleapis.com'));
 const r=await fetch(u,{signal:AbortSignal.timeout(60000)});assert(r.ok);const zip=path.join(out,compare?'installed-source.zip':'before-source.zip');fs.writeFileSync(zip,Buffer.from(await r.arrayBuffer()),{mode:0o600});
 const names=execFileSync('unzip',['-Z1',zip],{encoding:'utf8'}).trim().split('\n'),manifest={};
 for(const name of names.filter(n=>n.startsWith('lib/ai/')&&n.endsWith('.js')||['package.json','package-lock.json'].includes(n))){const bytes=execFileSync('unzip',['-p',zip,name]);manifest[name]=crypto.createHash('sha256').update(bytes).digest('hex');if(compare)assert(bytes.equals(fs.readFileSync(path.join(c.ROOT,'functions',name))),'Installed source mismatch: '+name);}
 save(compare?'installed-manifest.json':'before-manifest.json',manifest);return zip;
}
async function prepare(){promptOnly();assert(!fs.existsSync(path.join(out,'before.json')),'Fresh baseline required');const b=await v.snapshot();assert.equal(b.queue.state,'RUNNING');assert(!(await v.read(Q+'/tasks?pageSize=100')).tasks?.length,'Queue must be drained before prompt update');const f=b.functions.functions.find(x=>x.name.endsWith('/'+worker));assert(f);await installed(f,false);save('start.json',b);await c.request(Q+':pause','POST',{});await sleep(5000);assert.equal((await v.read(Q)).state,'PAUSED');assert(!(await v.read(Q+'/tasks?pageSize=100')).tasks?.length);save('before.json',{...b,queue:await v.read(Q)});console.log('PASS Dev-only fresh preflight; original source retained; queue PAUSED/drained');}
async function audit(){promptOnly();const b=load('before.json'),a=await v.snapshot();unchangedExceptWorker(b,a);assert.equal(a.queue.state,'PAUSED');const f=a.functions.functions.find(x=>x.name.endsWith('/'+worker));assert.equal(f.state,'ACTIVE');await installed(f,true);save('after-paused.json',a);await c.request(Q+':resume','POST',{});assert.equal((await v.read(Q)).state,'RUNNING');console.log('PASS worker prompt source/config/protected audit; other sixteen Functions unchanged; queue restored RUNNING');}
async function e2e(retry=false){c.guard();assert.equal((await v.read(Q)).state,'RUNNING');assert(retry?fs.existsSync(registry):!fs.existsSync(registry),'Never recreate billed fixtures');let state=retry?load('registry.json'):{projectId:P,run:crypto.randomUUID(),originalPages};assert.equal(state.projectId,P);
 const persist=()=>save('registry.json',state);persist();
 if(!retry){const key=execFileSync('python3',['-c','import plistlib;print(plistlib.load(open("Config/Firebase/Development/GoogleService-Info.plist","rb"))["API_KEY"])'],{cwd:c.ROOT,encoding:'utf8'}).trim();const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(key),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnSecureToken:true})});assert(r.ok);const user=await r.json();state.user={uid:user.localId,idToken:user.idToken,refreshToken:user.refreshToken};state.context=JSON.parse(fs.readFileSync(path.join(c.ROOT,'build/detection-dev-e2e/registry.json'))).context;persist();}
 const claims=JSON.parse(Buffer.from(state.user.idToken.split('.')[1],'base64url'));assert.equal(claims.aud,P);assert.equal(claims.sub,state.user.uid);
 async function call(name,data){assert(['aiCreateSource','aiCompleteSource','aiGetSource','aiGetEvidence','aiRetrieveContext','aiRetrySource'].includes(name));c.guard();const r=await fetch(`https://${R}-${P}.cloudfunctions.net/${name}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+state.user.idToken},body:JSON.stringify({data}),signal:AbortSignal.timeout(150000)}),d=await r.json();assert(r.ok,'DEV_CALL_'+name+'_'+r.status);return d.result;}
 const bytes=fs.readFileSync(path.join(out,'science-selected.pdf')),hash=crypto.createHash('sha256').update(bytes).digest('hex');
 if(!retry){state.pdfSHA=hash;const source=await call('aiCreateSource',{clientRequestId:state.run,type:'pdf',title:'Provided Evidence prompt validation',mime:'application/pdf',size:bytes.length,context:state.context});assert.equal(source.pipelineVersion,'pdf-auto-v1');state.sourceId=source.sourceId;persist();const u=new URL(source.upload.url);assert.equal(u.hostname,'storage.googleapis.com');assert(u.pathname.startsWith('/'+c.BUCKET+'/'));assert.equal((await fetch(u,{method:'PUT',headers:source.upload.headers,body:bytes})).status,200);await call('aiCompleteSource',{sourceId:source.sourceId});}
 else{assert.equal(hash,state.pdfSHA);const failed=await call('aiGetSource',{sourceId:state.sourceId});assert.equal(failed.status,'failed');assert.equal(failed.error?.code,'IMAGE_AI_RATE_LIMIT');assert(failed.error.retryable);state.explicitRetries=(state.explicitRetries||0)+1;persist();await call('aiRetrySource',{sourceId:state.sourceId});}
 let source;const end=Date.now()+600000;while(Date.now()<end){source=await call('aiGetSource',{sourceId:state.sourceId});if(source.status==='ready')break;assert(!['failed','partial_ready'].includes(source.status),'PROCESSING_'+source.error?.code);await sleep(5000);}assert.equal(source.status,'ready');const pages=source.recognition.routing.pages;assert.equal(pages.length,4);assert(pages.every(p=>p.route==='multimodal_ai'&&p.provider==='groq'&&p.model==='qwen/qwen3.8-27b'));
 const items=[];let after;do{const e=await call('aiGetEvidence',{sourceId:state.sourceId,...(after?{after}:{})});assert.equal(e.activeVersion,source.activeVersion);items.push(...e.items);after=e.nextCursor;}while(after);assert.equal(new Set(items.map(i=>i.locator.pageNumber)).size,4);assert(items.every(i=>i.method==='multimodal_ai'));
 const retrieval=await call('aiRetrieveContext',{courseOfferingId:source.courseOfferingId,purpose:'lecture_summary',maxCharacters:30000});assert(retrieval.items.some(i=>i.sourceId===state.sourceId));
 assert(items.every(i=>!i.text.includes('"visibleRelations"')&&!i.text.includes('"visibleText"')));save('result.json',{source,items,originalPages});state.status='READY_FOR_VISUAL_REVIEW';persist();console.log(JSON.stringify({status:state.status,pages:originalPages,totalTokens:source.recognition.totalTokens,estimatedCostUSD:source.recognition.estimatedCostUSD}));}
async function cleanup(){const state=load('registry.json');assert.equal(state.projectId,P);assert.equal(state.status,'READY_FOR_VISUAL_REVIEW');const r=await fetch(`https://identitytoolkit.googleapis.com/v1/projects/${P}/accounts:delete`,{method:'POST',headers:{Authorization:'Bearer '+await c.token(),'Content-Type':'application/json'},body:JSON.stringify({localId:state.user.uid})});assert(r.ok);delete state.user.idToken;delete state.user.refreshToken;state.status='CLEANUP_REQUESTED';save('registry.json',state);console.log('Disposable Dev Auth deletion requested; tokens removed locally');}
async function final(){const a=await v.snapshot(),b=load('before.json'),deployed=load('after-paused.json');unchangedExceptWorker(b,a);assert.deepEqual(a.functions,deployed.functions);assert.equal(a.queue.state,'RUNNING');const s=load('registry.json');assert.equal(s.status,'CLEANUP_REQUESTED');const ownerURL=`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiInputOwners/${s.user.uid}`;let owner;for(let i=0;i<40;i++){owner=await v.read(ownerURL);if(owner.fields.state.stringValue==='deleted')break;await sleep(3000);}assert.equal(owner.fields.state.stringValue,'deleted');const source=await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${s.sourceId}`);assert.equal(source.fields.status.stringValue,'deleted');assert(!(await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${s.sourceId}/runs`)).documents?.length);const version=load('result.json').source.activeVersion;assert.equal(typeof version,'string');assert(/^[A-Za-z0-9_-]{1,128}$/.test(version));assert(!(await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${s.sourceId}/runs/${version}/chunks`)).documents?.length);assert(!(await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${s.sourceId}/jobs`)).documents?.length);assert(!(await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiUsage/${s.user.uid}/periods`)).documents?.length);for(const prefix of ['ai-inputs','ai-derived'])assert(!(await v.read(`https://storage.googleapis.com/storage/v1/b/${c.BUCKET}/o?prefix=${encodeURIComponent(prefix+'/'+D+'/'+s.user.uid+'/')}`)).items?.length);s.status='EVIDENCE_PROMPT_DEV_CLEANED';save('registry.json',s);save('final.json',a);console.log('PASS final Dev protected audit and source/storage cleanup; queue RUNNING');}
const actions={prepare,audit,e2e, retry:()=>e2e(true),cleanup,final};
module.exports={promptOnly};if(require.main===module)(async()=>{assert(actions[process.argv[2]]);await actions[process.argv[2]]();})().catch(e=>{console.error('SAFE STOP '+e.name+' '+(e.httpStatus||'')+' (private evidence retained; no mutation replay)');process.exitCode=1});
