#!/usr/bin/env node
// Dev-only, explicitly approved course-PDF validation. No deploy/config mutation.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const c=require('./dev_cloud.cjs'),v=require('./visual_router_dev.cjs');
const P=c.PROJECT,D='aogaku-ai',R=c.REGION,OUT=path.join(c.ROOT,'build/evidence-adoption-dev');
const targets=[4,15,25,27],sleep=ms=>new Promise(r=>setTimeout(r,ms));
function save(name,value){fs.mkdirSync(OUT,{recursive:true,mode:0o700});fs.writeFileSync(path.join(OUT,name),JSON.stringify(value,null,2),{mode:0o600});}
function load(name){return JSON.parse(fs.readFileSync(path.join(OUT,name)));}
function joinChunks(items){let text='',end=0;for(const item of [...items].sort((a,b)=>a.chunkId.localeCompare(b.chunkId))){const start=item.locator.startChar||0;assert(start<=end,'Missing Evidence span');text+=item.text.slice(Math.max(0,end-start));end=item.locator.endChar;}return text;}
async function call(state,name,data){assert(['aiListSources','aiCreateSource','aiCompleteSource','aiGetSource','aiGetEvidence','aiRetrieveContext','aiRetrySource'].includes(name));c.guard();const r=await fetch(`https://${R}-${P}.cloudfunctions.net/${name}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+state.user.idToken},body:JSON.stringify({data}),signal:AbortSignal.timeout(150000)});const value=await r.json();assert(r.ok,'DEV_CALL_'+name+'_'+r.status);return value.result;}
async function object(name){assert(name.startsWith('ai-derived/'+D+'/'));c.guard();const url=`https://storage.googleapis.com/storage/v1/b/${c.BUCKET}/o/${encodeURIComponent(name)}?alt=media`;c.assertURL(url);const r=await fetch(url,{headers:{Authorization:'Bearer '+await c.token()},signal:AbortSignal.timeout(60000)});assert(r.ok,'Dev checkpoint read');return r.json();}
async function start(){c.guard();assert(!fs.existsSync(path.join(OUT,'registry.json')),'Never recreate billed fixture');const before=await v.snapshot();assert.equal(before.queue.state,'RUNNING');save('before.json',before);
 const key=execFileSync('python3',['-c','import plistlib;print(plistlib.load(open("Config/Firebase/Development/GoogleService-Info.plist","rb"))["API_KEY"])'],{cwd:c.ROOT,encoding:'utf8'}).trim();
 const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(key),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnSecureToken:true})});assert(r.ok);const user=await r.json();assert.equal(JSON.parse(Buffer.from(user.idToken.split('.')[1],'base64url')).aud,P);
 const state={projectId:P,run:crypto.randomUUID(),user:{uid:user.localId,idToken:user.idToken,refreshToken:user.refreshToken},context:loadContext()};save('registry.json',state);
 const capability=await call(state,'aiListSources',{context:state.context});assert.equal(capability.inputCapabilities.pdf.pipelineVersion,'pdf-auto-v1');save('capabilities.json',capability.inputCapabilities);
 const bytes=fs.readFileSync(path.join(c.ROOT,'build/visual-router-before/science.pdf'));state.pdfSHA256=crypto.createHash('sha256').update(bytes).digest('hex');
 const source=await call(state,'aiCreateSource',{clientRequestId:state.run,type:'pdf',title:'Selected Evidence adoption validation',mime:'application/pdf',size:bytes.length,context:state.context});assert.equal(source.pipelineVersion,'pdf-auto-v1');state.sourceId=source.sourceId;save('registry.json',state);
 const u=new URL(source.upload.url);assert.equal(u.hostname,'storage.googleapis.com');assert(u.pathname.startsWith('/'+c.BUCKET+'/'));assert.equal((await fetch(u,{method:'PUT',headers:source.upload.headers,body:bytes})).status,200);await call(state,'aiCompleteSource',{sourceId:state.sourceId});
 console.log('Fresh full 30-page PDF submitted to Dev; no production/config/deploy mutation');await collect();
}
function loadContext(){const state=JSON.parse(fs.readFileSync(path.join(c.ROOT,'build/detection-dev-e2e/registry.json')));assert.equal(state.projectId,P);return state.context;}
async function collect(){const state=load('registry.json');assert.equal(state.projectId,P);let source;const end=Date.now()+1200000;while(Date.now()<end){source=await call(state,'aiGetSource',{sourceId:state.sourceId});if(source.status==='ready')break;if(['failed','partial_ready'].includes(source.status)){save('failed-source.json',source);throw Error('PROCESSING_'+source.error?.code);}await sleep(5000);}assert.equal(source.status,'ready');save('source.json',source);
 const items=[];let after;do{const page=await call(state,'aiGetEvidence',{sourceId:state.sourceId,...(after?{after}:{})});assert.equal(page.activeVersion,source.activeVersion);items.push(...page.items);after=page.nextCursor;}while(after);
 const retrieval=await call(state,'aiRetrieveContext',{courseOfferingId:source.courseOfferingId,purpose:'lecture_summary',maxCharacters:30000});save('retrieval.json',retrieval);
 const files=await v.read(`https://storage.googleapis.com/storage/v1/b/${c.BUCKET}/o?prefix=${encodeURIComponent('ai-derived/'+D+'/'+state.user.uid+'/'+state.sourceId+'/')}`);assert(!files.nextPageToken);const names=(files.items||[]).map(x=>x.name);
 const {openRouterPDF,analyzePDFPage}=require('../functions/lib/ai/visualExtraction'),{chooseVisualRoute}=require('../functions/lib/ai/visualRouter'),{chunksFor}=require('../functions/lib/ai/domain');const pdf=await openRouterPDF(path.join(c.ROOT,'build/visual-router-before/science.pdf')),trace=[];
 try{for(let n=1;n<=pdf.doc.numPages;n++){
  const p=await pdf.doc.getPage(n),native=await analyzePDFPage(p,pdf.OPS);p.cleanup();const checkpointName=names.find(x=>x.endsWith('/pdf-auto-v1-page-'+n+'.json'));assert(checkpointName);const checkpoint=await object(checkpointName);
  const probeName=names.find(x=>x.endsWith('/pdf-auto-v1-page-'+n+'-ocr-probe.json')),probe=probeName?await object(probeName):null;
  const chunks=items.filter(x=>x.locator.pageNumber===n),retrieved=retrieval.items.filter(x=>x.sourceId===state.sourceId&&x.locator.pageNumber===n);
  assert.equal(joinChunks(chunks),checkpoint.unit.text,'Unit -> Evidence '+n);assert.deepEqual(chunks.map(x=>({text:x.text,method:x.method,locator:x.locator})),chunksFor([checkpoint.unit]).map(x=>({text:x.text,method:x.method,locator:x.locator})),'Chunk offsets '+n);
  assert.equal(checkpoint.unit.method,checkpoint.page.route);if(checkpoint.page.route==='native_text'){assert.equal(checkpoint.unit.text,native.text.trim());assert.equal(probe,null);assert.equal(checkpoint.page.totalTokens,0);}
  if(targets.includes(n)){assert.equal(checkpoint.page.route,'multimodal_ai');assert.equal(checkpoint.page.provider,'groq');assert.equal(checkpoint.page.model,'qwen/qwen3.8-27b');assert(checkpoint.page.totalTokens>0);assert.notEqual(checkpoint.unit.text,native.text);assert.equal(joinChunks(retrieved),checkpoint.unit.text,'Evidence -> retrieval '+n);for(const x of retrieved)assert(chunks.some(c=>c.chunkId===x.chunkId&&c.text===x.text&&JSON.stringify(c.locator)===JSON.stringify(x.locator)));}
  trace.push({pageNumber:n,routerDecision:chooseVisualRoute('pdf',native.features),selectedRoute:checkpoint.page.route,nativeText:native.text,ocrProbe:probe?.text??null,qwenFinalText:checkpoint.page.route==='multimodal_ai'?checkpoint.unit.text:null,qwenFinalTextOrigin:'Provider finalText -> Unit in persisted post-provider checkpoint (raw response not retained)',unit:checkpoint.unit,chunkText:joinChunks(chunks),evidenceText:joinChunks(chunks),retrieveContextText:joinChunks(retrieved),metadata:checkpoint.page});
 }}finally{await pdf.destroy();}
 save('trace.json',trace);const ui={items,status:source.status,pipelineVersion:source.pipelineVersion,activeVersion:source.activeVersion,recognition:source.recognition,processingMs:source.processingMs};save('ui.json',ui);
 fs.mkdirSync(path.join(c.ROOT,'AogakuTests/DevFixtures'),{recursive:true});fs.writeFileSync(path.join(c.ROOT,'AogakuTests/DevFixtures/evidence-adoption-dev.json'),JSON.stringify({evidence:ui,trace:trace.filter(x=>targets.includes(x.pageNumber)).map(x=>({pageNumber:x.pageNumber,finalText:x.unit.text}))}),{mode:0o600});
 const afterSnapshot=await v.snapshot();v.protectedCheck(load('before.json'),afterSnapshot);assert.deepEqual(afterSnapshot.functions,load('before.json').functions);assert.equal(afterSnapshot.queue.state,'RUNNING');save('after.json',afterSnapshot);state.status='TRACE_PASS';save('registry.json',state);console.log(JSON.stringify({status:state.status,pages:trace.length,targetPages:targets,routeCounts:source.recognition.routing.counts,totalTokens:source.recognition.totalTokens,costUSD:source.recognition.estimatedCostUSD,protectedState:'UNCHANGED'}));
}
async function cleanup(){const state=load('registry.json');assert.equal(state.projectId,P);assert.equal(state.status,'TRACE_PASS');const r=await fetch(`https://identitytoolkit.googleapis.com/v1/projects/${P}/accounts:delete`,{method:'POST',headers:{Authorization:'Bearer '+await c.token(),'Content-Type':'application/json'},body:JSON.stringify({localId:state.user.uid})});assert(r.ok);delete state.user.idToken;delete state.user.refreshToken;state.status='CLEANUP_REQUESTED';save('registry.json',state);console.log('Own disposable Dev Auth cleanup requested; local tokens removed');}
async function retry(){assert(process.argv.includes('--approve-provider-retry'),'Explicit retry required; never automatic');const state=load('registry.json');assert.equal(state.projectId,P);const failed=await call(state,'aiGetSource',{sourceId:state.sourceId});assert.equal(failed.status,'failed');assert.equal(failed.error?.code,'IMAGE_AI_RATE_LIMIT');assert.equal(failed.error.retryable,true);state.explicitRetries=(state.explicitRetries||0)+1;save('registry.json',state);await call(state,'aiRetrySource',{sourceId:state.sourceId});console.log('Explicit Dev retry of the same source; completed page checkpoints retained');await collect();}
async function final(){const state=load('registry.json');assert.equal(state.status,'CLEANUP_REQUESTED');assert.equal(state.projectId,P);const base=`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/`;
 let owner;for(let i=0;i<40;i++){owner=await v.read(base+'aiInputOwners/'+state.user.uid);if(owner.fields.state.stringValue==='deleted')break;await sleep(3000);}assert.equal(owner.fields.state.stringValue,'deleted');assert.equal((await v.read(base+'aiSources/'+state.sourceId)).fields.status.stringValue,'deleted');
 for(const suffix of ['/runs','/runs/'+load('source.json').activeVersion+'/chunks','/jobs'])assert(!(await v.read(base+'aiSources/'+state.sourceId+suffix)).documents?.length);
 assert(!(await v.read(base+'aiUsage/'+state.user.uid+'/periods')).documents?.length);
 for(const prefix of ['ai-inputs','ai-derived'])assert(!(await v.read(`https://storage.googleapis.com/storage/v1/b/${c.BUCKET}/o?prefix=${encodeURIComponent(prefix+'/'+D+'/'+state.user.uid+'/')}`)).items?.length);
 const a=await v.snapshot();v.protectedCheck(load('before.json'),a);assert.deepEqual(a.functions,load('before.json').functions);assert.equal(a.queue.state,'RUNNING');save('final.json',a);state.status='CLEANED_TRACE_PASS';save('registry.json',state);console.log('PASS own Dev fixture cleanup, tokens removed, protected resources unchanged');
}
module.exports={joinChunks};if(require.main===module){const actions={start,collect,cleanup,final,retry};(async()=>{assert(actions[process.argv[2]]);await actions[process.argv[2]]();})().catch(e=>{console.error('SAFE STOP '+e.name+' '+e.message.replace(/[A-Za-z0-9_-]{28,}/g,'[private]'));process.exitCode=1});}
