#!/usr/bin/env node
// Dev-only, one worker source PATCH; no env/IAM/Rules/Secret/allowlist updates.
// Preserve installed package, changing only two image routing modules.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const c=require('./dev_cloud.cjs'),v=require('./visual_router_dev.cjs'),reads=require('./production_read_retry.cjs'),p=require('./production_recognition_review.cjs'),{sourceManifest}=require('./deploy_production_phase3a.cjs');
const OUT=path.join(c.ROOT,'build/image-router-dev'),P=c.PROJECT,D='aogaku-ai',R=c.REGION,G='https://cloudfunctions.googleapis.com/v2/',parent=`projects/${P}/locations/${R}`,F=parent+'/functions/aiProcessSource',Q=`https://cloudtasks.googleapis.com/v2/projects/${P}/locations/${R}/queues/aiProcessSource`;
const modules=['lib/ai/visualRouter.js','lib/ai/visualExtraction.js'],sleep=ms=>new Promise(r=>setTimeout(r,ms)),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function save(n,x){fs.mkdirSync(OUT,{recursive:true,mode:0o700});fs.writeFileSync(path.join(OUT,n+'.json'),JSON.stringify(x,null,2),{mode:0o600});}
function load(n){return JSON.parse(fs.readFileSync(path.join(OUT,n+'.json')));}
async function source(f,label){const data=(await reads.read(G+f.name+':generateDownloadUrl',{method:'POST',headers:{Authorization:'Bearer '+await c.token(),'Content-Type':'application/json'},body:'{}'})).data,u=new URL(data.downloadUrl);assert.equal(u.protocol,'https:');assert(u.hostname==='storage.googleapis.com'||u.hostname.endsWith('.storage.googleapis.com'));
 const bytes=(await reads.read(u,{}, {bytes:true,sourceName:'dev_image_router'})).data,file=path.join(OUT,label+'.zip');fs.writeFileSync(file,bytes,{mode:0o600});assert.deepEqual(await v.read(G+f.name),f);return sourceManifest(file);}
async function prepare(){assert(!fs.existsSync(path.join(OUT,'before.json')),'Fresh Dev baseline only');c.guard();const b=await v.snapshot();assert.equal(b.queue.state,'RUNNING');assert(!(await v.read(Q+'/tasks?pageSize=100')).tasks?.length);save('start',b);const f=b.functions.functions.find(x=>x.name===F);assert(f&&f.state==='ACTIVE');const manifest=await source(f,'before-source');save('before-manifest',manifest);
 assert.equal(manifest['lib/ai/recognition.js'],sha(fs.readFileSync(path.join(c.ROOT,'functions/lib/ai/recognition.js'))),'Grounded prompt must be unchanged from Dev baseline');
 execFileSync('python3',['-c',`import zipfile,sys,pathlib
src,dst,root,*mods=sys.argv[1:]; z=zipfile.ZipFile(src)
with zipfile.ZipFile(dst,'w',zipfile.ZIP_DEFLATED) as out:
 for n in z.namelist():
  if not n.endswith('/'):
   assert not n.startswith('/') and '..' not in n.split('/')
   out.writestr(n,(pathlib.Path(root)/n).read_bytes() if n in mods else z.read(n))`,path.join(OUT,'before-source.zip'),path.join(OUT,'candidate.zip'),path.join(c.ROOT,'functions'),...modules]);
 const candidate=sourceManifest(path.join(OUT,'candidate.zip'));assert.deepEqual(Object.keys(candidate),Object.keys(manifest));assert.deepEqual(Object.keys(candidate).filter(n=>candidate[n]!==manifest[n]).sort(),[...modules].sort());save('candidate-manifest',candidate);
 await c.request(Q+':pause','POST',{});assert.equal((await v.read(Q)).state,'PAUSED');await sleep(10000);assert(!(await v.read(Q+'/tasks?pageSize=100')).tasks?.length);save('before',{...b,queue:await v.read(Q)});console.log('PASS fresh Dev identity/config/source; exactly two modules; queue PAUSED/drained');}
async function update(){assert(!fs.existsSync(path.join(OUT,'update-attempt.json')),'No automatic mutation replay');const b=load('before'),a=await v.snapshot();v.protectedCheck(b,a);assert.deepEqual(a.functions,b.functions);assert.equal(a.queue.state,'PAUSED');const before=await v.read(G+F);save('update-attempt',{status:'STAGING_ATTEMPTED'});
 const issued=await c.request(G+parent+'/functions:generateUploadUrl','POST',{}),u=new URL(issued.uploadUrl);assert.equal(u.protocol,'https:');assert.equal(u.hostname,'storage.googleapis.com');assert(issued.storageSource.bucket.includes(c.NUMBER)&&issued.storageSource.bucket.includes(R));
 const r=await fetch(u,{method:'PUT',redirect:'error',headers:{'Content-Type':'application/zip'},body:fs.readFileSync(path.join(OUT,'candidate.zip')),signal:AbortSignal.timeout(60000)});assert(r.ok,'Dev staging status '+r.status);save('update-attempt',{status:'PATCH_ATTEMPTED'});
 const op=await c.request(G+F+'?updateMask=buildConfig.source','PATCH',{name:F,buildConfig:{source:{storageSource:issued.storageSource}}});assert(op.name.startsWith(parent+'/operations/'));save('operation',{name:op.name});let done=false;
 for(let i=0;i<240;i++){const x=await v.read(G+op.name);save('operation',x);if(x.done){assert(!x.error,'Dev operation error '+x.error?.code);done=true;break;}if(i%12===0)console.log('Dev worker build pending');await sleep(5000);}assert(done,'Operation timeout; never retry PATCH');
 const after=await v.read(G+F),manifest=await source(after,'installed');p.postCheck(before,after,manifest,load('candidate-manifest'));const latest=await v.snapshot();v.protectedCheck(b,latest);for(const f of b.functions.functions)if(f.name!==F)assert.deepEqual(latest.functions.functions.find(x=>x.name===f.name),f);assert.equal(latest.queue.state,'PAUSED');save('after-paused',latest);save('update-attempt',{status:'FULL_SOURCE_PROTECTED_PASS',beforeRevision:before.serviceConfig.revision,afterRevision:after.serviceConfig.revision});console.log('PASS Dev worker-only source revision; env/IAM/protected and all other Functions unchanged');}
async function resume(){assert.equal(load('update-attempt').status,'FULL_SOURCE_PROTECTED_PASS');assert(!fs.existsSync(path.join(OUT,'resume-attempt.json')));const a=await v.snapshot();v.protectedCheck(load('before'),a);assert.deepEqual(a.functions,load('after-paused').functions);assert.equal(a.queue.state,'PAUSED');save('resume-attempt',{status:'ATTEMPTED'});await c.request(Q+':resume','POST',{});assert.equal((await v.read(Q)).state,'RUNNING');save('resume-attempt',{status:'RUNNING'});console.log('PASS Dev queue RUNNING restored');}
async function e2e(){assert(!fs.existsSync(path.join(OUT,'registry.json')),'Never replay billed fixtures');assert.equal((await v.read(Q)).state,'RUNNING');
 const fixtures=require('./image_router_fixtures.cjs').generate(path.join(OUT,'fixtures')),state={projectId:P,run:crypto.randomUUID(),sources:[],results:[]};const persist=()=>save('registry',state);persist();
 const key=execFileSync('python3',['-c','import plistlib;print(plistlib.load(open("Config/Firebase/Development/GoogleService-Info.plist","rb"))["API_KEY"])'],{cwd:c.ROOT,encoding:'utf8'}).trim(),r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(key),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnSecureToken:true})});assert(r.ok);const user=await r.json();assert.equal(JSON.parse(Buffer.from(user.idToken.split('.')[1],'base64url')).aud,P);state.user={uid:user.localId,idToken:user.idToken,refreshToken:user.refreshToken};state.context=JSON.parse(fs.readFileSync(path.join(c.ROOT,'build/detection-dev-e2e/registry.json'))).context;persist();
 async function call(name,data){assert(['aiListSources','aiCreateSource','aiCompleteSource','aiGetSource','aiGetEvidence','aiRetrieveContext'].includes(name));c.guard();const r=await fetch(`https://${R}-${P}.cloudfunctions.net/${name}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+state.user.idToken},body:JSON.stringify({data}),signal:AbortSignal.timeout(150000)}),d=await r.json();assert(r.ok,'Dev callable '+name+' HTTP '+r.status);return d.result;}
 const {joinChunks}=require('./evidence_adoption_dev.cjs'),{value}=require('./production_phase5a_e2e.cjs');const doc=x=>Object.fromEntries(Object.entries(x.fields||{}).map(([k,v])=>[k,value(v)]));
 const base=`https://firestore.googleapis.com/v1/projects/${P}/databases/`;
 for(const f of fixtures){const type=f.type||'image',bytes=fs.readFileSync(path.join(OUT,'fixtures',f.file)),row={key:f.key,status:'CREATE_ATTEMPTED'};state.sources.push(row);persist();
  const created=await call('aiCreateSource',{clientRequestId:state.run+'-'+f.key,type,title:'Synthetic image routing '+f.key,mime:type==='image'?'image/png':'application/pdf',size:bytes.length,context:state.context});row.sourceId=created.sourceId;persist();assert.equal(created.pipelineVersion,type+'-auto-v1');const u=new URL(created.upload.url);assert.equal(u.hostname,'storage.googleapis.com');assert(u.pathname.startsWith('/'+c.BUCKET+'/'));assert.equal((await fetch(u,{method:'PUT',headers:created.upload.headers,body:bytes})).status,200);await call('aiCompleteSource',{sourceId:row.sourceId});
  let ready;for(let i=0;i<120;i++){ready=await call('aiGetSource',{sourceId:row.sourceId});if(ready.status==='ready')break;assert(!['failed','partial_ready'].includes(ready.status),'Processing '+ready.error?.code);await sleep(5000);}assert.equal(ready.status,'ready');
  const pages=ready.recognition.routing.pages;assert.deepEqual(pages.map(x=>x.route),type==='pdf'?f.expected:[f.expected],'Real route '+f.key);
  const items=[];let after;do{const e=await call('aiGetEvidence',{sourceId:row.sourceId,...(after?{after}:{})});items.push(...e.items);after=e.nextCursor;}while(after);
  const chunks=await v.read(base+D+`/documents/aiSources/${row.sourceId}/runs/${ready.activeVersion}/chunks?pageSize=100`);assert(!chunks.nextPageToken);const stored=chunks.documents.map(doc);assert.deepEqual(stored.map(x=>({text:x.text,method:x.method,locator:x.locator})),items.map(x=>({text:x.text,method:x.method,locator:x.locator})));
  const retrieval=await call('aiRetrieveContext',{courseOfferingId:ready.courseOfferingId,lectureIds:[ready.lectureId],purpose:'lecture_summary',maxCharacters:30000}),own=retrieval.items.filter(x=>x.sourceId===row.sourceId);
  const objects=await v.read(`https://storage.googleapis.com/storage/v1/b/${c.BUCKET}/o?prefix=${encodeURIComponent(`ai-derived/${D}/${state.user.uid}/${row.sourceId}/`)}`);assert(!objects.nextPageToken);const trace=[];
  for(const [i,page]of pages.entries()){const suffix=type==='pdf'?`pdf-auto-v1-page-${i+1}.json`:'image-auto-v1-final.json',name=objects.items.find(x=>x.name.endsWith('/'+suffix))?.name;assert(name);const url=`https://storage.googleapis.com/storage/v1/b/${c.BUCKET}/o/${encodeURIComponent(name)}?alt=media`,checkpoint=await v.read(url),select=xs=>xs.filter(x=>type==='image'||x.locator.pageNumber===i+1);
   assert.equal(checkpoint.unit.method,page.route);for(const xs of [items,stored,own])assert.equal(joinChunks(select(xs)),checkpoint.unit.text,'FinalText -> Unit/chunks/Evidence/retrieval '+f.key);
   if(page.route==='multimodal_ai'){assert.equal(page.provider,'groq');assert.equal(page.model,'qwen/qwen3.8-27b');assert(page.totalTokens>0);}
   if(f.key==='short-arrow-flow'){for(const label of ['Observation','Question','Hypothesis','Experiment','Conclusion','Result'])assert(checkpoint.unit.text.includes(label));assert(/矢印|接続|→|arrow|connect/i.test(checkpoint.unit.text));assert(!/Result\s*(?:→|から)\s*Observation/i.test(checkpoint.unit.text));}
   trace.push({route:page.route,provider:page.provider,model:page.model,features:page.features,finalText:checkpoint.unit.text,unit:checkpoint.unit,chunkText:joinChunks(select(stored)),evidenceText:joinChunks(select(items)),retrieveContextText:joinChunks(select(own)),metadata:page});
  }
  await assert.rejects(v.read(base+`(default)/documents/aiSources/${row.sourceId}`),e=>e.httpStatus===404);save('result-'+f.key,{source:ready,trace,items});row.status='PASS';state.results.push({key:f.key,routes:pages.map(x=>x.route),tokens:ready.recognition.totalTokens,costUSD:ready.recognition.estimatedCostUSD});persist();console.log(JSON.stringify(state.results.at(-1)));
 }
 const a=await v.snapshot();v.protectedCheck(load('before'),a);assert.deepEqual(a.functions,load('after-paused').functions);assert.equal(a.queue.state,'RUNNING');save('final',a);state.status='DEV_IMAGE_ROUTING_TRACE_PASS';persist();console.log(state.status);}
async function cleanup(){const s=load('registry');assert.equal(s.projectId,P);assert.equal(s.status,'DEV_IMAGE_ROUTING_TRACE_PASS');assert.equal(s.sources.length,10);assert(s.sources.every(x=>x.status==='PASS'));assert(!fs.existsSync(path.join(OUT,'cleanup-attempt.json')),'Cleanup mutation never replayed');
 save('cleanup-attempt',{status:'AUTH_DELETE_ATTEMPTED'});const r=await fetch('https://identitytoolkit.googleapis.com/v1/projects/'+P+'/accounts:delete',{method:'POST',headers:{Authorization:'Bearer '+await c.token(),'Content-Type':'application/json'},body:JSON.stringify({localId:s.user.uid}),signal:AbortSignal.timeout(45000)});assert(r.ok);delete s.user.idToken;delete s.user.refreshToken;s.status='CLEANUP_REQUESTED';save('registry',s);
 const base=`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/`;let owner;for(let i=0;i<40;i++){owner=await v.read(base+'aiInputOwners/'+s.user.uid);if(owner.fields.state.stringValue==='deleted')break;await sleep(3000);}assert.equal(owner.fields.state.stringValue,'deleted');
 for(const row of s.sources){const source=await v.read(base+'aiSources/'+row.sourceId);assert.equal(source.fields.status.stringValue,'deleted');for(const suffix of ['/runs','/jobs','/runs/'+load('result-'+row.key).source.activeVersion+'/chunks'])assert(!(await v.read(base+'aiSources/'+row.sourceId+suffix)).documents?.length);}
 assert(!(await v.read(base+'aiUsage/'+s.user.uid+'/periods')).documents?.length);for(const prefix of ['ai-inputs','ai-derived'])assert(!(await v.read(`https://storage.googleapis.com/storage/v1/b/${c.BUCKET}/o?prefix=${encodeURIComponent(prefix+'/'+D+'/'+s.user.uid+'/')}`)).items?.length);
 const a=await v.snapshot();v.protectedCheck(load('before'),a);assert.deepEqual(a.functions,load('after-paused').functions);assert.equal(a.queue.state,'RUNNING');save('final-cleaned',a);s.status='DEV_IMAGE_ROUTING_TRACE_PASS_CLEANED';save('registry',s);console.log('PASS 10 own Dev fixtures/Auth/storage/usage cleaned; tombstones and private trace retained; protected config unchanged');}
module.exports={modules};if(require.main===module)(async()=>{const actions={prepare,update,resume,e2e,cleanup};assert(actions[process.argv[2]]);await actions[process.argv[2]]();})().catch(e=>{console.error('SAFE STOP Dev image router '+e.name+(e.httpStatus?' HTTP '+e.httpStatus:'')+'; no mutation replay');process.exitCode=1});
