#!/usr/bin/env node
// Reuse the previously approved disposable nonpilot. Never create an account,
// change allowlists/IAM, or delete a pilot. Cleanup needs its original consent.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const deploy=require('./deploy_production_image_router.cjs'),d=require('./deploy_production_visual_router.cjs'),c=require('./production_phase5a_common.cjs'),p=require('./production_recognition_review.cjs');
const OLD=path.join(d.DIR,'e2e'),load=n=>JSON.parse(fs.readFileSync(path.join(OLD,n+'.json'))),save=(n,x)=>fs.writeFileSync(path.join(OLD,n+'.json'),JSON.stringify(x),{mode:0o600});
async function outsider(raw){const reg=load('outsider-registry.private');assert.equal(reg.status,'CREATED');assert.equal(reg.projectId,c.P);assert.equal(reg.allowlisted,false);assert.equal(reg.fixtureSourcesCreated,0);let a=load('outsider-auth.private');assert.equal(a.projectId,c.P);
 if(a.expiresAt*1000<Date.now()+120000){const r=await fetch('https://securetoken.googleapis.com/v1/token?key='+encodeURIComponent(c.apiKey()),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:a.refreshToken}),signal:AbortSignal.timeout(45000)});assert(r.ok,'Existing nonpilot refresh HTTP '+r.status);const x=await r.json();a={projectId:c.P,idToken:x.id_token,refreshToken:x.refresh_token,expiresAt:Date.now()/1000+Number(x.expires_in)};save('outsider-auth.private',a);}
 const claims=c.jwt(a.idToken);assert.equal(c.hash(claims.sub),reg.uidHash);const allowed=JSON.parse(raw.find(f=>f.name.endsWith('/aiCreateSource')).serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS);assert(!allowed.includes(claims.sub));return {uid:claims.sub,token:a.idToken};}
async function main(action){assert(['gates','cleanup'].includes(action));const raw=await d.rawFunctions(),pilot=await d.pilotAuth(raw),other=await outsider(raw);assert.notEqual(pilot.uid,other.uid);
 if(action==='gates'){assert.equal(deploy.load('execution').status,'WORKER_VERIFIED');const results=[];for(const name of p.CALLABLES)for(const [role,token,expected]of [['anonymous',null,'UNAUTHENTICATED'],['nonpilot',other.token,'AI_INPUT_NOT_ENABLED'],['pilot',pilot.token,'INVALID_REQUEST']]){const r=await fetch(`https://${c.R}-${c.P}.cloudfunctions.net/${name}`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({data:null}),signal:AbortSignal.timeout(45000)}),x=await r.json();assert(!r.ok,'No null request may create material');const code=x.error?.details?.code||x.error?.status;assert.equal(code,expected);results.push({name,role,code,httpStatus:r.status});}deploy.save('auth-gates',{status:'PASS',checks:results});console.log('PASS 27 live gates; anonymous/nonpilot denied; existing pilot admitted; no fixture writes');return;}
 const consent=load('nonpilot-consent.private');assert.equal(consent.projectId,c.P);assert.equal(consent.approved,true);assert.equal(consent.cleanupApproved,true);assert.equal(consent.maximumAccounts,1);const reg=load('outsider-registry.private');const e2e=JSON.parse(fs.readFileSync(path.join(deploy.DIR,'e2e/registry.private.json')));assert.equal(e2e.status,'PRODUCTION_IMAGE_ROUTING_E2E_PASS');assert.equal(deploy.load('auth-gates').status,'PASS');assert(!fs.existsSync(path.join(deploy.DIR,'outsider-cleanup-attempt.json')),'Cleanup mutation never replayed');
 deploy.save('outsider-cleanup-attempt',{status:'DELETE_ATTEMPTED',registryUIDHash:reg.uidHash,originalConsentVerified:true});reg.status='DELETE_ATTEMPTED';save('outsider-registry.private',reg);const resp=await fetch(`https://identitytoolkit.googleapis.com/v1/projects/${c.P}/accounts:delete`,{method:'POST',redirect:'error',headers:{Authorization:'Bearer '+await c.cloud.oauth(),'Content-Type':'application/json'},body:JSON.stringify({localId:other.uid}),signal:AbortSignal.timeout(45000)});assert(resp.ok,'Disposable Auth cleanup HTTP '+resp.status);reg.status='DELETED';save('outsider-registry.private',reg);fs.unlinkSync(path.join(OLD,'outsider-auth.private.json'));
 const admin=require('../functions/node_modules/firebase-admin'),app=admin.initializeApp({projectId:c.P,credential:{getAccessToken:async()=>({access_token:await c.cloud.oauth(),expires_in:2700})}},'image-router-cleanup-read');try{await assert.rejects(app.auth().getUser(other.uid),e=>e.code==='auth/user-not-found');const named=require('../functions/node_modules/firebase-admin/firestore').getFirestore(app,c.DB);assert((await named.collection('aiSources').where('ownerUserId','==',other.uid).limit(1).get()).empty);assert((await named.doc('aiUsage/'+other.uid).collection('periods').limit(1).get()).empty);for(const prefix of ['ai-inputs','ai-derived']){const data=await d.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o?prefix=${encodeURIComponent(prefix+'/'+c.DB+'/'+other.uid+'/')}`);assert(!(data.items||[]).length);}deploy.save('outsider-cleanup',{status:'PASS',authAbsent:true,sourceFixtures:0,usagePeriods:0,storageObjects:0,pilotUntouched:true});console.log('PASS original disposable nonpilot cleanup; pilot untouched; no new account created');}finally{await app.delete();}
}
module.exports={outsider};if(require.main===module)main(process.argv[2]).catch(e=>{console.error('SAFE STOP Auth '+e.name+'; no mutation retry');process.exitCode=1});
