#!/usr/bin/env node
// Exactly one disposable nonpilot account, only after separate human consent.
// No allowlist writes, email/password persistence, Firebase config or IAM changes.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const d=require('./deploy_production_visual_router.cjs'),c=require('./production_phase5a_common.cjs');const DIR=path.join(d.DIR,'e2e');
const load=n=>JSON.parse(fs.readFileSync(path.join(DIR,n+'.json'))),save=(n,x)=>fs.writeFileSync(path.join(DIR,n+'.json'),JSON.stringify(x)+'\n',{mode:0o600});
async function main(action){assert(['create','cleanup'].includes(action));const consent=load('nonpilot-consent.private');assert.equal(consent.approved,true);assert.equal(consent.projectId,c.P);assert.equal(consent.maximumAccounts,1);assert.equal(consent.cleanupApproved,true);
 const raw=await d.rawFunctions(),allowed=JSON.parse(raw.find(f=>f.name.endsWith('/aiCreateSource')).serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS);await d.pilotAuth(raw);
 if(action==='create'){
  assert(['COHORT_AUDIT_PASS','DEPLOY_COMPLETE_E2E_PENDING'].includes(d.load('execution').status));assert(!fs.existsSync(path.join(DIR,'outsider-registry.private.json')),'Signup replay forbidden');save('outsider-registry.private',{status:'SIGNUP_ATTEMPTED',projectId:c.P,allowlisted:false,fixtureSourcesCreated:0});
  const email='router-denied-'+crypto.randomUUID()+'@example.test',password=crypto.randomBytes(32).toString('base64url');const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(c.apiKey()),{method:'POST',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true}),signal:AbortSignal.timeout(45000)});assert(r.ok,'Disposable signup HTTP '+r.status);const x=await r.json();c.jwt(x.idToken,x.localId);assert(!allowed.includes(x.localId));save('outsider-auth.private',{idToken:x.idToken,refreshToken:x.refreshToken,expiresAt:Date.now()/1000+Number(x.expiresIn),projectId:c.P});save('outsider-registry.private',{status:'CREATED',projectId:c.P,uidHash:c.hash(x.localId),allowlisted:false,fixtureSourcesCreated:0});console.log('One separately approved synthetic nonpilot Auth account created; UID masked; no data fixture');return;
 }
 assert.equal(load('registry.private').status,'PERMISSIONS_PASS');const reg=load('outsider-registry.private');assert.equal(reg.status,'CREATED');const a=load('outsider-auth.private'),claims=c.jwt(a.idToken);assert.equal(c.hash(claims.sub),reg.uidHash);assert(!allowed.includes(claims.sub));assert.equal(reg.fixtureSourcesCreated,0);
 reg.status='DELETE_ATTEMPTED';save('outsider-registry.private',reg);const r=await fetch(`https://identitytoolkit.googleapis.com/v1/projects/${c.P}/accounts:delete`,{method:'POST',redirect:'error',headers:{Authorization:'Bearer '+await c.cloud.oauth(),'Content-Type':'application/json'},body:JSON.stringify({localId:claims.sub}),signal:AbortSignal.timeout(45000)});assert(r.ok,'Disposable cleanup HTTP '+r.status);reg.status='DELETED';save('outsider-registry.private',reg);fs.unlinkSync(path.join(DIR,'outsider-auth.private.json'));
 const admin=require('../functions/node_modules/firebase-admin');const app=admin.initializeApp({projectId:c.P,credential:{getAccessToken:async()=>({access_token:await c.cloud.oauth(),expires_in:2700})}},'router-cleanup-read');await assert.rejects(app.auth().getUser(claims.sub),e=>e.code==='auth/user-not-found');
 for(const prefix of [`ai-inputs/${c.DB}/${claims.sub}/`,`ai-derived/${c.DB}/${claims.sub}/`]){const v=await d.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o?prefix=${encodeURIComponent(prefix)}`);assert(!(v.items||[]).length);}
 const named=require('../functions/node_modules/firebase-admin/firestore').getFirestore(app,c.DB);
 assert((await named.collection('aiSources').where('ownerUserId','==',claims.sub).limit(1).get()).empty);
 assert((await named.doc('aiUsage/'+claims.sub).collection('periods').limit(1).get()).empty);
 const result=load('registry.private');result.disposableAuthCleanup={status:'PASS',authAbsent:true,allowlisted:false,sourceFixturesCreated:0,namedSourceFixtures:0,usagePeriods:0,storageObjects:0,pilotUntouched:true};save('registry.private',result);console.log('Registered disposable Auth account removed; pilot untouched; no named source/usage/raw/derived fixtures');
}
if(require.main===module)main(process.argv[2]).catch(e=>{console.error('SAFE STOP disposable Auth '+e.name+'; no automatic mutation retry');process.exitCode=1;});
