const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const cloud=require('./production_cloud_phase4_retry.cjs'),reads=require('./production_read_retry.cjs'),p3b=require('./deploy_production_phase3b.cjs'),p1=require('./provision_production_phase1.cjs');
const metadataHash=require('./deploy_production_phase3a.cjs').hash;
const ROOT=path.resolve(__dirname,'..'),DIR=path.join(ROOT,'build/production-phase5a'),P='forta-aogaku',N='505828754933',R='asia-northeast1',B=P+'.firebasestorage.app',SA='aogaku-ai-runtime@'+P+'.iam.gserviceaccount.com',DB='aogaku-ai',G='https://cloudfunctions.googleapis.com/v2/',parent=`projects/${P}/locations/${R}`,Q=`projects/${P}/locations/${R}/queues/aiProcessSource`;
const ALL=require('./deploy_production_phase4_completion.cjs').ALL_NAMES,CALLABLES=ALL.slice(0,9),CONFIGURED=[...CALLABLES,'aiProcessSource'],SHA='34ef21c5a5f3816693809465c1e79ef2a762119db9686e3ed186130a146cf0a8';
const load=n=>JSON.parse(fs.readFileSync(path.join(DIR,n+'.json'))),hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
function operator(){const x=load('operator');assert.equal(x.projectId,P);assert.equal(x.allowedUIDs.length,1);assert(/^[A-Za-z0-9_-]{1,128}$/.test(x.allowedUIDs[0]));assert.equal(x.sharingEnabled,false);assert.equal(x.phase5bAuthorized,false);return x;}
function masked(x){const uid=operator().allowedUIDs[0],text=JSON.stringify(p3b.safeMetadata(x));return JSON.parse(text.split(uid).join('[PILOT_UID]').split(encodeURIComponent(uid)).join('[PILOT_UID]'));}
function save(n,x){const f=path.join(DIR,n+'.json');fs.mkdirSync(path.dirname(f),{recursive:true,mode:0o700});fs.writeFileSync(f,JSON.stringify(masked(x),null,2)+'\n',{mode:0o600});fs.chmodSync(f,0o600);}
function jwt(token,uid){const c=JSON.parse(Buffer.from(token.split('.')[1],'base64url'));assert.equal(c.aud,P);assert.equal(c.iss,'https://securetoken.google.com/'+P);if(uid)assert.equal(c.sub,uid);assert(c.exp*1000>Date.now());return c;}
function apiKey(){return JSON.parse(execFileSync('python3',['-c','import json,plistlib;d=plistlib.load(open("Aogaku/GoogleService-Info.plist","rb"));assert d["PROJECT_ID"]=="forta-aogaku" and str(d["GCM_SENDER_ID"])=="505828754933" and d["BUNDLE_ID"]=="com.forta2k25.Aogaku" and d["STORAGE_BUCKET"]=="forta-aogaku.firebasestorage.app";print(json.dumps({"key":d["API_KEY"]}))'],{cwd:ROOT,encoding:'utf8'})).key;}
async function auth(which){assert(['pilot','outsider'].includes(which));let a=load(which+'-auth');if(a.expiresAt*1000<Date.now()+120000){const r=await fetch('https://securetoken.googleapis.com/v1/token?key='+encodeURIComponent(apiKey()),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:a.refreshToken}),signal:AbortSignal.timeout(45000)});assert(r.ok,'Auth refresh HTTP '+r.status);const d=await r.json();a={idToken:d.id_token,refreshToken:d.refresh_token,expiresAt:Date.now()/1000+Number(d.expires_in),projectId:P};fs.writeFileSync(path.join(DIR,which+'-auth.json'),JSON.stringify(a)+'\n',{mode:0o600});}
 const c=jwt(a.idToken);if(which==='pilot')assert.equal(c.sub,operator().allowedUIDs[0]);else {assert.notEqual(c.sub,operator().allowedUIDs[0]);assert.equal(hash(c.sub),load('outsider-registry').uidHash);}return {token:a.idToken,uid:c.sub};}
async function read(url,method='GET',body,settings={}){reads.assertRead(url,method,body===undefined?undefined:JSON.stringify(body));const {data}=await reads.read(url,{method,headers:{Authorization:'Bearer '+await cloud.oauth(),'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})},settings);assert(!data?.nextPageToken||settings.boundedPage===true,'STOP: paginated metadata');return data;}
async function snapshot(){
 const metadata=await cloud.inspect();execFileSync('python3',['-c','import sys;sys.path.insert(0,"scripts");import firebase_production as p;s=p.load("build/production-live.json");p.live_check(s);p.require_named_ready(s,True,True)'],{cwd:ROOT,stdio:'pipe'});await cloud.resourcesMetadata();const resources=JSON.parse(fs.readFileSync(path.join(ROOT,'build/production-resources-live.json'))).records;assert(Object.values(resources).every(x=>x.httpStatus===200));
 const functions=(await read(cloud.urls.functions)).functions||[],iam={},functionIAM={},runIAM={},secrets={},keys={};
 for(const [k,p]of Object.entries(p1.policies))iam[k]=await read(p.get,p.getMethod||'GET',p.getMethod==='POST'?{options:{requestedPolicyVersion:3}}:undefined);
 for(const s of ['GROQ_API_KEY','OPENAI_API_KEY','IMPORT_API_KEY']){const u=`https://secretmanager.googleapis.com/v1/projects/${P}/secrets/${s}`;secrets[s]={metadata:await read(u),versions:await read(u+'/versions?pageSize=100')};iam[s]=await read(u+':getIamPolicy?options.requestedPolicyVersion=3');}
 for(const f of functions){const n=f.name.split('/').pop();functionIAM[n]=await read((f.environment==='GEN_1'?'https://cloudfunctions.googleapis.com/v1/':G)+f.name+':getIamPolicy'+(f.environment==='GEN_1'?'':'?options.requestedPolicyVersion=3'));runIAM[n]=f.environment==='GEN_1'?functionIAM[n]:await read('https://run.googleapis.com/v1/'+f.serviceConfig.service+':getIamPolicy');}
 for(const sa of [SA,`aogaku-ai-account-deletion@${P}.iam.gserviceaccount.com`]){keys[sa]=await read(`https://iam.googleapis.com/v1/projects/${P}/serviceAccounts/${sa}/keys?keyTypes=USER_MANAGED`);assert(!(keys[sa].keys||[]).length);}
 return p3b.safeMetadata({metadata,resources,functions,iam,functionIAM,runIAM,secrets,keys});
}
function protectedState(b,a,j){
 assert.equal(a.functions.length,25);for(const k of Object.keys(b.metadata).filter(k=>!['readAt','functions'].includes(k)))assert.deepEqual(p3b.metadataCore(k,a.metadata[k]),p3b.metadataCore(k,b.metadata[k]),'Protected '+k+' drift');
 for(const k of ['iam','functionIAM','secrets','keys'])assert.deepEqual(a[k],b[k],'Protected '+k+' drift');
 for(const k of ['apis','serviceAccounts','scheduler'])assert.deepEqual(a.resources[k],b.resources[k],'Protected '+k+' drift');
 const eventarc=x=>({...x,data:{...x.data,triggers:(x.data.triggers||[]).map(require('./audit_production_phase4_complete.cjs').eventarcCore).sort((a,b)=>a.name.localeCompare(b.name))}});
 assert.deepEqual(eventarc(a.resources.eventarc),eventarc(b.resources.eventarc),'Protected Eventarc drift');
 const qb=structuredClone(b.resources.queue),qa=structuredClone(a.resources.queue);assert.equal(qa.data.state,j.queueResumed?'RUNNING':'PAUSED');qa.data.state=qb.data.state;assert.deepEqual(qa,qb,'Queue configuration drift');
 for(const f of b.functions){const n=f.name.split('/').pop(),current=structuredClone(a.functions.find(x=>x.name===f.name));assert(current);
  if(j.configured.includes(n)){const expected=j.configProof[n];assert.equal(current.serviceConfig.environmentVariables.sha256,expected.environmentSha256);assert.equal(current.updateTime,expected.updateTime);assert.equal(expected.installedSourceSha256,SHA);assert.equal(expected.fullSourceUnchanged,true);assert.equal(metadataHash(current.buildConfig),expected.buildConfigSha256);current.buildConfig=f.buildConfig;current.updateTime=f.updateTime;current.serviceConfig.environmentVariables=f.serviceConfig.environmentVariables;current.serviceConfig.revision=f.serviceConfig.revision;}
  assert.deepEqual(current,f,'Unapproved Function change '+n);
  const publicIAM=j.public.includes(n)?p1.merge(b.runIAM[n],[{member:'allUsers',roles:['roles/run.invoker']}]):b.runIAM[n];assert.deepEqual(p1.policyCore(a.runIAM[n]),p1.policyCore(publicIAM),'Unexpected Run IAM '+n);if(!j.public.includes(n))assert.deepEqual(a.runIAM[n],b.runIAM[n]);
 }
}
module.exports={ROOT,DIR,P,N,R,B,SA,DB,G,parent,Q,ALL,CALLABLES,CONFIGURED,SHA,load,hash,metadataHash,operator,masked,save,jwt,apiKey,auth,read,snapshot,protectedState,cloud,p1,p3b};
