#!/usr/bin/env node
// Synthetic material via existing approved pilot only. No account/AI data deletion,
// no allowlist edits, no default catalog writes and no provider fault injection.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const d=require('./deploy_production_recognition.cjs'),c=require('./production_phase5a_common.cjs'),p=require('./production_recognition_review.cjs'),reads=require('./production_read_retry.cjs'),{value,uploadTarget}=require('./production_phase5a_e2e.cjs');
const DIR=path.join(d.DIR,'e2e'),file=path.join(DIR,'registry.private.json'),db=(id,p)=>`https://firestore.googleapis.com/v1/projects/${c.P}/databases/${id}/documents/${p}`,doc=x=>Object.fromEntries(Object.entries(x.fields||{}).map(([k,v])=>[k,value(v)]));
function save(x){fs.mkdirSync(DIR,{recursive:true,mode:0o700});fs.writeFileSync(file,JSON.stringify(x,null,2)+'\n',{mode:0o600});}
async function main(action){assert(['before','gates','inputs','verify-existing','verify-legacy-final','direct-permissions','permissions','final'].includes(action));let s=fs.existsSync(file)?JSON.parse(fs.readFileSync(file)):{run:crypto.randomUUID(),sources:[],results:[],attempts:[],syntheticOnly:true,status:'STARTED'};assert(s.status!=='STOPPED'||['verify-existing','verify-legacy-final'].includes(action));fs.mkdirSync(DIR,{recursive:true,mode:0o700});const live=await d.rawFunctions(),owner=await d.pilotAuth(live);
 async function call(n,data,token=owner.token){assert(p.CALLABLES.includes(n));assert(data===null||!['aiDeleteSource','aiUpdateSource'].includes(n),'No data deletion/sharing edits');const ev={name:n,payloadHash:c.hash(data),status:'UNKNOWN'};s.attempts.push(ev);save(s);const r=await fetch(`https://${c.R}-${c.P}.cloudfunctions.net/${n}`,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({data}),signal:AbortSignal.timeout(150000)}),x=await r.json().catch(()=>({}));ev.httpStatus=r.status;ev.status='RECEIVED';save(s);if(!r.ok){const e=Error(x.error?.details?.code||x.error?.status||'CALLABLE_ERROR');e.code=e.message;throw e;}return x.result;}
 async function docRead(id,p){const {response,data}=await reads.read(db(id,p),{headers:{Authorization:'Bearer '+await c.cloud.oauth()}},{allowStatuses:[404],sourceName:'recognition_test_boundary'});return response.status===404?null:data;}
 async function pages(id){const items=[];let after,metadata;do{const page=await call('aiGetEvidence',{sourceId:id,...(after?{after}:{})});if(metadata)assert.equal(metadata.activeVersion,page.activeVersion);else metadata=page;items.push(...page.items);after=page.nextCursor;}while(after);return {...metadata,items};}
 async function storage(raw){assert(raw.startsWith(`ai-inputs/${c.DB}/${owner.uid}/`)||raw.startsWith(`ai-derived/${c.DB}/${owner.uid}/`));return d.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o/${encodeURIComponent(raw)}`);}
 async function ready(id){for(let i=0;i<100;i++){const x=await call('aiGetSource',{sourceId:id});if(x.status==='ready')return x;assert(!['failed','partial_ready','deleted','deleting'].includes(x.status),'Processing '+x.status+' '+x.error?.code);if(i%10===0)console.log('Synthetic worker waiting: '+x.status);await new Promise(r=>setTimeout(r,4000));}throw Error('PROCESSING_TIMEOUT');}
 function outsider(){const f=path.join(DIR,'outsider-auth.private.json');assert(fs.existsSync(f),'Additional disposable Auth approval/login is pending');const x=JSON.parse(fs.readFileSync(f)),claims=c.jwt(x.idToken);assert(!JSON.parse(live.find(f=>f.name.endsWith('/aiCreateSource')).serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS).includes(claims.sub));return x;}
 try{
 if(action==='before'){
  assert(!s.legacy,'Do not replace old OCR baseline');const old=JSON.parse(fs.readFileSync('/Users/shum/Documents/Codex/2026-10-06/y/work/Aogaku-main-integration/build/production-phase5a/e2e.json'));assert.equal(old.syntheticOnly,true);const id=old.sources.image.sourceId,raw=await docRead(c.DB,'aiSources/'+id);assert.equal(raw.fields.ownerUserId.stringValue,owner.uid);assert.equal(raw.fields.status.stringValue,'ready');const page=await pages(id);assert(page.items.length&&page.items.every(x=>x.method==='vision_ocr'));s.legacy={sourceId:id,recordHash:c.hash(raw),itemsHash:c.hash(page.items),activeVersion:page.activeVersion};
  const ctx=old.context,idClass=ctx.classDocId;assert(/^\d{5}$/.test(idClass));const catalog=doc(await docRead('(default)','classes/'+idClass));const url=catalog.url||catalog.syllabusURL,year=Number(new URL(url).searchParams.get('YR'));assert(Number.isInteger(year)&&year>=2000&&year<=2100);s.catalog={classDocId:idClass,year,syllabusUrl:url};s.context={classDocId:idClass,year,semester:ctx.semester,dayID:Math.floor(Date.now()/86400000),localCourseUUID:crypto.randomUUID(),occurrenceKey:'recognition-'+s.run};
  s.defaultUsageBefore=await docRead('(default)','aiUsage/'+owner.uid);s.defaultPeriodsBefore=await d.read(db('(default)','aiUsage/'+owner.uid+'/periods?pageSize=100'));
  execFileSync('swift',['scripts/dev_e2e_assets.swift',DIR],{cwd:c.ROOT,stdio:'pipe'});execFileSync('swift',['scripts/image_route_assets.swift',DIR,s.run],{cwd:c.ROOT,stdio:'pipe'});execFileSync('say',['-v','Kyoko','-f',path.join(DIR,'speech.txt'),'-o',path.join(DIR,'speech.aiff')]);const ffmpeg=require('../functions/node_modules/ffmpeg-static');execFileSync(ffmpeg,['-y','-i',path.join(DIR,'speech.aiff'),'-c:a','aac','-b:a','96k',path.join(DIR,'sample-audio.m4a')],{stdio:'pipe'});const ffprobe=require('../functions/node_modules/ffprobe-static').path;const duration=Number(execFileSync(ffprobe,['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',path.join(DIR,'sample-audio.m4a')],{encoding:'utf8'}));assert(duration>0&&duration<60);s.audioDurationSeconds=duration;s.status='OLD_OCR_BASELINE_AND_ASSETS_READY';save(s);console.log('Existing synthetic OCR evidence read-only PASS; fresh 2 images/PDF/memo/short synthesized audio prepared; pilot token valid');return;
 }
 if(action==='gates'){
  assert.equal(d.load('execution').status,'COHORT_AUDIT_PASS');const allowed=[],otherFile=path.join(DIR,'outsider-auth.private.json'),other=fs.existsSync(otherFile)?outsider():null;const roles=other?['anonymous','nonpilot','pilot']:['anonymous','pilot'];for(const n of p.CALLABLES){for(const role of roles){try{await call(n,null,role==='anonymous'?null:role==='pilot'?owner.token:other.idToken);throw Error('NULL_DATA_ACCEPTED');}catch(e){const expected={anonymous:'UNAUTHENTICATED',nonpilot:'AI_INPUT_NOT_ENABLED',pilot:'INVALID_REQUEST'}[role];assert.equal(e.code,expected);allowed.push({name:n,role,result:e.code});}}}s.gates={status:'PASS',checks:allowed,nonpilotLiveConfirmed:!!other};save(s);console.log(allowed.length+'/'+allowed.length+' live Auth gates PASS; nonpilot confirmed='+!!other+'; no processing/data writes');return;
 }
 if(action==='inputs'){
  assert.equal(d.load('execution').status,'DEPLOY_COMPLETE_E2E_PENDING');assert.equal(s.results.length,0,'No billable fixture replay');const capability=(await call('aiListSources',{context:s.context})).inputCapabilities.image;assert.deepEqual(capability,{provider:'groq',model:'qwen/qwen3.8-27b',method:'multimodal_ai',pipelineVersion:'image-ai-v2',fallback:false});
  for(const key of ['note','image-1','image-2','pdf','audio']){
   const type=key.startsWith('image')?'image':key,mime={note:'text/plain',image:'image/jpeg',pdf:'application/pdf',audio:'audio/mp4'}[type],asset={ 'image-1':'image-1.jpg','image-2':'image-2.jpg',pdf:'sample-document.pdf',audio:'sample-audio.m4a'}[key],bytes=asset?fs.readFileSync(path.join(DIR,asset)):null;
   const data={clientRequestId:'recognition-'+s.run+'-'+key,type,title:'Synthetic recognition migration '+key,mime,context:s.context,...(bytes?{size:bytes.length}:{text:'検索拡張生成では根拠資料と出典を保存し、資料に基づき回答を検証する。架空の講義メモ。'}),...(type==='audio'?{durationSeconds:Math.ceil(s.audioDurationSeconds)}:{})};s.sources.push({key,data,attempted:true});save(s);const created=await call('aiCreateSource',data);s.sources.at(-1).sourceId=created.sourceId;save(s);if(type==='image')assert.equal(created.pipelineVersion,'image-ai-v2');
   if(bytes){const url=uploadTarget(created.upload.url,created.sourceId,owner.uid);const r=await fetch(url,{method:'PUT',redirect:'error',headers:created.upload.headers,body:bytes,signal:AbortSignal.timeout(120000)});assert.equal(r.status,200,'Synthetic upload HTTP '+r.status);}
   await call('aiCompleteSource',{sourceId:created.sourceId});const source=await ready(created.sourceId),ev=await pages(created.sourceId);assert(ev.items.length);assert.equal(source.courseOfferingId,s.catalog.year+':'+s.catalog.classDocId);assert.equal(source.courseSnapshot.yearSource,'syllabus');assert.equal(source.courseSnapshot.syllabusUrl,s.catalog.syllabusUrl);assert.equal(source.sharingEnabled,false);assert.equal(source.knowledgeVisibility,'private');
   if(type==='image'){const m=source.recognition;assert.equal(m.provider,'groq');assert.equal(m.model,'qwen/qwen3.8-27b');assert.equal(m.method,'multimodal_ai');assert.equal(m.pipelineVersion,'image-ai-v2');assert.equal(source.pipelineVersion,'image-ai-v2');assert(m.inputTokens>0&&m.outputTokens>0&&m.totalTokens>0&&m.processingMs>0);assert(Math.abs(m.estimatedCostUSD-(m.inputTokens*.8+m.outputTokens*4)/1e6)<1e-12);assert(ev.items.every(x=>x.method==='multimodal_ai'));assert.deepEqual(ev.recognition,m);}
   if(type==='audio'){const m=source.recognition;assert.equal(m.provider,'groq');assert.equal(m.model,'whisper-large-v3-turbo');assert.equal(m.inputTokens,null);assert.equal(m.outputTokens,null);assert(m.audioDurationSeconds>0&&m.processingMs>0&&m.estimatedCostUSD>0);assert(Math.abs(m.estimatedCostUSD-m.billedAudioSeconds/3600*.04)<1e-12);assert(ev.items.every(x=>x.method==='groq_asr'&&x.locator.endMs>x.locator.startMs));}
   if(type==='pdf'){assert(ev.items.some(x=>x.method==='pdf_text'&&x.locator.pageNumber===1));assert(ev.items.some(x=>x.method==='vision_ocr'&&x.locator.pageNumber===2));}
   const result=await call('aiRetrieveContext',{courseOfferingId:source.courseOfferingId,purpose:'lecture_summary',maxCharacters:30000});assert(result.items.some(x=>x.sourceId===created.sourceId));const list=await call('aiListSources',{context:s.context});assert(list.items.some(x=>x.sourceId===created.sourceId));
   const raw=await docRead(c.DB,'aiSources/'+created.sourceId),named=doc(raw);assert.equal(named.ownerUserId,owner.uid);assert.equal(named.status,'ready');assert.deepEqual(named.recognition||null,source.recognition||null);assert.equal(await docRead('(default)','aiSources/'+created.sourceId),null);const chunks=await d.read(db(c.DB,`aiSources/${created.sourceId}/runs/${named.activeRun}/chunks?pageSize=100`));assert(chunks.documents.length);assert.equal((await d.read(db('(default)',`aiSources/${created.sourceId}/runs/${named.activeRun}/chunks?pageSize=100`))).documents?.length||0,0);assert(named.storagePath.startsWith(`ai-inputs/${c.DB}/${owner.uid}/${created.sourceId}/`));const derived=await d.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o?prefix=${encodeURIComponent(`ai-derived/${c.DB}/${owner.uid}/${created.sourceId}/`)}`);assert(derived.items?.length);if(bytes){const rawObject=await storage(named.storagePath);assert.equal(Number(rawObject.size),bytes.length);}
   fs.writeFileSync(path.join(DIR,key+'-result.private.json'),JSON.stringify({source,items:ev.items},null,2),{mode:0o600});s.results.push({key,status:'PASS',recognition:source.recognition||null,pipelineVersion:source.pipelineVersion,chunks:ev.items.length,evidence:true,retrieval:true,namedBoundary:true});save(s);console.log(JSON.stringify(s.results.at(-1)));
  }
  const duplicate=await call('aiCreateSource',s.sources[0].data);assert.equal(duplicate.sourceId,s.sources[0].sourceId);s.duplicate='PASS';assert.deepEqual(await docRead('(default)','aiUsage/'+owner.uid),s.defaultUsageBefore);assert.deepEqual(await d.read(db('(default)','aiUsage/'+owner.uid+'/periods?pageSize=100')),s.defaultPeriodsBefore);assert((await d.read(db(c.DB,'aiUsage/'+owner.uid+'/periods?pageSize=100'))).documents?.some(x=>x.fields.providerCalls));
  const old=await pages(s.legacy.sourceId);assert.equal(c.hash(old.items),s.legacy.itemsHash);assert.equal(c.hash(await docRead(c.DB,'aiSources/'+s.legacy.sourceId)),s.legacy.recordHash);assert.equal(old.activeVersion,s.legacy.activeVersion);s.legacyUnchanged=true;
  const ui=s.results.filter(x=>x.key.startsWith('image')||x.key==='audio').map(x=>{const v=JSON.parse(fs.readFileSync(path.join(DIR,x.key+'-result.private.json')));return {status:'ready',pipelineVersion:v.source.pipelineVersion,recognition:v.source.recognition,processingMs:v.source.processingMs,items:v.items.map(({chunkId,text,method,unitIndex,locator})=>({chunkId,text,method,unitIndex,locator}))};});fs.mkdirSync(path.join(c.ROOT,'AogakuTests/DevFixtures'),{recursive:true});fs.writeFileSync(path.join(c.ROOT,'AogakuTests/DevFixtures/image-route-production-results.json'),JSON.stringify(ui),{mode:0o600});s.status='INPUTS_PASS';save(s);console.log('Five fresh synthetic inputs + duplicate + old OCR unchanged + named/default boundary PASS');return;
 }
 if(action==='verify-existing'){
  // The original audio-raw assertion was invalid: successful ASR deletes raw immediately.
  // Preserve the stop evidence; this phase performs only GET/read Callables, never another input.
  assert.equal(s.status,'STOPPED');assert.equal(s.safeError,'Error');assert.equal(s.sources.length,5);assert.equal(s.results.length,4);
  const backup=path.join(DIR,'registry-audio-raw-stop.private.json');assert(!fs.existsSync(backup));fs.copyFileSync(file,backup);fs.chmodSync(backup,0o600);
  for(const row of s.sources){const source=await call('aiGetSource',{sourceId:row.sourceId});assert.equal(source.status,'ready');const ev=await pages(row.sourceId);assert(ev.items.length);const raw=await docRead(c.DB,'aiSources/'+row.sourceId),named=doc(raw);assert.equal(named.ownerUserId,owner.uid);assert.equal(named.status,'ready');assert.equal(await docRead('(default)','aiSources/'+row.sourceId),null);
   if(row.key==='audio'){
    const m=source.recognition;assert.equal(m.provider,'groq');assert.equal(m.model,'whisper-large-v3-turbo');assert.equal(m.method,'groq_asr');assert.equal(m.inputTokens,null);assert.equal(m.totalTokens,null);assert(m.audioDurationSeconds>0&&m.processingMs>0);assert(Math.abs(m.estimatedCostUSD-m.billedAudioSeconds/3600*.04)<1e-12);assert(ev.items.every(x=>x.method==='groq_asr'&&x.locator.endMs>x.locator.startMs));
    const bytes=fs.readFileSync(path.join(DIR,'sample-audio.m4a'));assert.equal(named.originalHash,crypto.createHash('sha256').update(bytes).digest('hex'),'Processed original must match registered audio');
    const {response}=await reads.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o/${encodeURIComponent(named.storagePath)}`,{headers:{Authorization:'Bearer '+await c.cloud.oauth()}},{allowStatuses:[404],sourceName:'recognition_audio_post_asr_cleanup'});assert.equal(response.status,404,'Successful audio raw cleanup expected');
    const chunks=await d.read(db(c.DB,`aiSources/${row.sourceId}/runs/${named.activeRun}/chunks?pageSize=100`));assert(chunks.documents?.length);assert.equal((await d.read(db('(default)',`aiSources/${row.sourceId}/runs/${named.activeRun}/chunks?pageSize=100`))).documents?.length||0,0);
    const result=await call('aiRetrieveContext',{courseOfferingId:source.courseOfferingId,purpose:'lecture_summary',maxCharacters:30000});assert(result.items.some(x=>x.sourceId===row.sourceId));const derived=await d.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o?prefix=${encodeURIComponent(`ai-derived/${c.DB}/${owner.uid}/${row.sourceId}/`)}`);assert(derived.items?.length);
    fs.writeFileSync(path.join(DIR,'audio-result.private.json'),JSON.stringify({source,items:ev.items},null,2),{mode:0o600});s.results.push({key:'audio',status:'PASS',recognition:m,pipelineVersion:source.pipelineVersion,chunks:ev.items.length,evidence:true,retrieval:true,namedBoundary:true,rawDeletedAfterSuccess:true,originalHashVerified:true});
   }
  }
  const duplicate=await call('aiCreateSource',s.sources[0].data);assert.equal(duplicate.sourceId,s.sources[0].sourceId);s.duplicate='PASS';
  assert.deepEqual(await docRead('(default)','aiUsage/'+owner.uid),s.defaultUsageBefore);assert.deepEqual(await d.read(db('(default)','aiUsage/'+owner.uid+'/periods?pageSize=100')),s.defaultPeriodsBefore);assert((await d.read(db(c.DB,'aiUsage/'+owner.uid+'/periods?pageSize=100'))).documents?.some(x=>x.fields.providerCalls));
  const old=await pages(s.legacy.sourceId);assert.equal(c.hash(old.items),s.legacy.itemsHash);assert.equal(c.hash(await docRead(c.DB,'aiSources/'+s.legacy.sourceId)),s.legacy.recordHash);assert.equal(old.activeVersion,s.legacy.activeVersion);s.legacyUnchanged=true;
  const ui=s.results.filter(x=>x.key.startsWith('image')||x.key==='audio').map(x=>{const v=JSON.parse(fs.readFileSync(path.join(DIR,x.key+'-result.private.json')));return {status:'ready',pipelineVersion:v.source.pipelineVersion,recognition:v.source.recognition,processingMs:v.source.processingMs,items:v.items.map(({chunkId,text,method,unitIndex,locator})=>({chunkId,text,method,unitIndex,locator}))};});
  fs.writeFileSync(path.join(c.ROOT,'AogakuTests/DevFixtures/image-route-production-results.json'),JSON.stringify(ui),{mode:0o600});s.audioAssertionCorrection={status:'PASS',stopEvidencePreserved:true,expectedRawDeletionSourceLine:513,createReplay:false,uploadReplay:false,workerReplay:false,providerReplay:false};s.status='INPUTS_PASS';delete s.safeError;save(s);console.log('PASS existing 5 ready inputs: Qwen2/Turbo/PDF/memo, original audio hash+post-ASR raw absence, evidence/retrieval, duplicate, unchanged old OCR/default boundary. No new upload/provider run.');return;
 }
 if(action==='verify-legacy-final'){
  assert.equal(s.status,'STOPPED');assert.equal(s.safeError,'ERR_ASSERTION');assert.equal(s.results.length,5);assert.equal(s.duplicate,'PASS');const backup=path.join(DIR,'registry-legacy-assertion-stop.private.json');assert(!fs.existsSync(backup));fs.copyFileSync(file,backup);fs.chmodSync(backup,0o600);
  const beforeTime=Date.parse(d.load('baseline').metadata.readAt),raw=await docRead(c.DB,'aiSources/'+s.legacy.sourceId),named=doc(raw);assert.equal(named.ownerUserId,owner.uid);assert.equal(named.status,'ready');assert(Date.parse(raw.updateTime)<beforeTime,'Legacy source was written after preflight');
  const repeat=await docRead(c.DB,'aiSources/'+s.legacy.sourceId);const canonical=require('./deploy_production_phase3a.cjs').hash;assert.equal(canonical(raw),canonical(repeat),'Canonical legacy source drift');
  const ev=await pages(s.legacy.sourceId);assert.equal(c.hash(ev.items),s.legacy.itemsHash,'Legacy evidence content/locators changed');assert.equal(ev.activeVersion,named.activeRun);assert(ev.items.every(x=>x.method==='vision_ocr'));
  const chunks=await d.read(db(c.DB,`aiSources/${s.legacy.sourceId}/runs/${named.activeRun}/chunks?pageSize=100`));assert(chunks.documents?.length);assert(chunks.documents.every(x=>Date.parse(x.updateTime)<beforeTime),'Legacy chunks changed since preflight');
  s.legacyUnchanged=true;s.legacyVerification={status:'PASS',canonicalHash:canonical(raw),documentLastWrittenAt:raw.updateTime,sourceAndChunksUntouchedSincePreflight:true,evidenceHashUnchanged:true,activeRunMatchesEvidence:true,oldApiActiveVersionWasOptional:true};
  const ui=s.results.filter(x=>x.key.startsWith('image')||x.key==='audio').map(x=>{const v=JSON.parse(fs.readFileSync(path.join(DIR,x.key+'-result.private.json')));return {status:'ready',pipelineVersion:v.source.pipelineVersion,recognition:v.source.recognition,processingMs:v.source.processingMs,items:v.items.map(({chunkId,text,method,unitIndex,locator})=>({chunkId,text,method,unitIndex,locator}))};});
  fs.writeFileSync(path.join(c.ROOT,'AogakuTests/DevFixtures/image-route-production-results.json'),JSON.stringify(ui),{mode:0o600});s.audioAssertionCorrection={status:'PASS',stopEvidencePreserved:true,expectedRawDeletionSourceLine:513,createReplay:false,uploadReplay:false,workerReplay:false,providerReplay:false};s.legacyAssertionCorrection={status:'PASS',canonicalInsteadOfRawJSONOrder:true,optionalOldActiveVersionHandled:true,sourceWrite:false};s.status='INPUTS_PASS';delete s.safeError;save(s);console.log('PASS all5 input evidence + legacy document/chunks last-written before preflight, unchanged text/locator hash; UI evidence prepared. No source/upload/provider/deploy replay.');return;
 }
 if(action==='direct-permissions'){
  assert.equal(s.status,'INPUTS_PASS');const sourceId=s.sources.find(x=>x.key==='image-1').sourceId,raw=doc(await docRead(c.DB,'aiSources/'+sourceId)).storagePath;const proof=[];
  for(const[role,token]of [['anonymous',null],['pilot',owner.token]]){
   for(const[service,url,header]of [['Firestore',db(c.DB,'aiSources/'+sourceId),token?'Bearer '+token:null],['Storage',`https://firebasestorage.googleapis.com/v0/b/${c.B}/o/${encodeURIComponent(raw)}?alt=media`,token?'Firebase '+token:null]]){const r=await fetch(url,{headers:header?{Authorization:header}:{},signal:AbortSignal.timeout(45000)});assert.equal(r.status,403,service+' direct '+role);await r.body?.cancel();proof.push({role,service,status:403});}
  }
  s.directAccess={status:'PASS',checks:proof};save(s);console.log('4/4 live direct Firestore/Storage anonymous+pilot 403; valid nonpilot Auth test remains separately gated');return;
 }
 if(action==='permissions'){
  assert.equal(s.status,'INPUTS_PASS');const other=outsider(),sourceId=s.sources.find(x=>x.key==='image-1').sourceId,raw=doc(await docRead(c.DB,'aiSources/'+sourceId)).storagePath;s.access=[];
  for(const n of p.CALLABLES){try{await call(n,null,other.idToken);throw Error('NONPILOT_ACCEPTED');}catch(e){assert.equal(e.code,'AI_INPUT_NOT_ENABLED');s.access.push({name:n,nonpilotDenied:true});}}
  for(const role of ['anonymous','pilot','nonpilot']){const token={anonymous:null,pilot:owner.token,nonpilot:other.idToken}[role];for(const [service,url,authorization]of [['Firestore',db(c.DB,'aiSources/'+sourceId),token?'Bearer '+token:null],['Storage',`https://firebasestorage.googleapis.com/v0/b/${c.B}/o/${encodeURIComponent(raw)}?alt=media`,token?'Firebase '+token:null]]){const r=await fetch(url,{headers:authorization?{Authorization:authorization}:{},signal:AbortSignal.timeout(45000)});assert.equal(r.status,403,service+' direct '+role);await r.body?.cancel();s.access.push({role,service,status:403});}}
  try{await call('aiGetEvidence',{sourceId},other.idToken);throw Error('NONPILOT_SOURCE_READ_ACCEPTED');}catch(e){assert.equal(e.code,'AI_INPUT_NOT_ENABLED');}s.status='PERMISSIONS_PASS';save(s);console.log('9/9 nonpilot callables denied + real evidence denied; anonymous/pilot/nonpilot direct DB/Storage 403');return;
 }
 assert.equal(s.status,'PERMISSIONS_PASS');const q=await d.read('https://cloudtasks.googleapis.com/v2/'+c.Q);assert.equal(q.state,'RUNNING');const snap=await d.snapshot();d.protectedCheck(d.load('baseline'),snap,d.load('execution'));d.save('e2e-final-protected',snap);s.status='PRODUCTION_RECOGNITION_E2E_PASS';save(s);console.log(s.status);
 }catch(e){s.status='STOPPED';s.safeError=/^[A-Z0-9_]+$/.test(e.code||e.message)?e.code||e.message:e.name;save(s);console.error('SAFE STOP E2E '+s.safeError+'; no mutation replay or fixture deletion');process.exitCode=1;}
}
if(require.main===module)main(process.argv[2]).catch(e=>{console.error('SAFE STOP '+e.name);process.exitCode=1});
