#!/usr/bin/env node
// Existing pilots only, five fresh synthetic fixtures; no old-source reprocessing.
// No env/allowlist/IAM/Secret/Rules or Function mutations, no automatic replay.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const deploy=require('./deploy_production_image_router.cjs'),d=require('./deploy_production_visual_router.cjs'),c=require('./production_phase5a_common.cjs'),{value,uploadTarget}=require('./production_phase5a_e2e.cjs'),{joinChunks}=require('./evidence_adoption_dev.cjs');
const DIR=path.join(deploy.DIR,'e2e'),REG=path.join(DIR,'registry.private.json'),db=(id,p)=>`https://firestore.googleapis.com/v1/projects/${c.P}/databases/${id}/documents/${p}`,doc=x=>Object.fromEntries(Object.entries(x.fields||{}).map(([k,v])=>[k,value(v)])),sleep=ms=>new Promise(r=>setTimeout(r,ms));
// Firestore map ordering is not part of the document contract.
const documentDigest=require('./deploy_production_phase3a.cjs').hash;
const save=s=>fs.writeFileSync(REG,JSON.stringify(s,null,2),{mode:0o600});
async function main(){assert.equal(deploy.load('execution').status,'DEPLOYED_E2E_PENDING');assert(!fs.existsSync(REG),'Never replay synthetic provider-billed fixtures');fs.mkdirSync(DIR,{recursive:true,mode:0o700});
 const s={projectId:c.P,run:crypto.randomUUID(),syntheticOnly:true,sources:[],results:[],attempts:[],status:'STARTED'};save(s);
 const raw=await d.rawFunctions(),owner=await d.pilotAuth(raw);c.jwt(owner.token,owner.uid);const start=await d.snapshot();d.protectedCheck(deploy.load('baseline'),start,deploy.load('execution'));deploy.policy(start,raw,'RUNNING');
 async function call(name,data){assert(['aiListSources','aiCreateSource','aiCompleteSource','aiGetSource','aiGetEvidence','aiRetrieveContext'].includes(name));const ev={name,payloadDigest:c.hash(data),status:'ATTEMPTED'};s.attempts.push(ev);save(s);const resp=await fetch(`https://${c.R}-${c.P}.cloudfunctions.net/${name}`,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json',Authorization:'Bearer '+owner.token},body:JSON.stringify({data}),signal:AbortSignal.timeout(150000)}),x=await resp.json().catch(()=>({}));ev.httpStatus=resp.status;ev.status='RECEIVED';save(s);assert(resp.ok,'Callable status '+name+' '+resp.status+' '+x.error?.status);return x.result;}
 async function document(id,p,allow404=false){const {response,data}=await require('./production_read_retry.cjs').read(db(id,p),{headers:{Authorization:'Bearer '+await c.cloud.oauth()}},{allowStatuses:allow404?[404]:[],sourceName:'router_boundary'});return response.status===404?null:data;}
 async function evidence(id){const items=[];let after;do{const r=await call('aiGetEvidence',{sourceId:id,...(after?{after}:{})});items.push(...r.items);after=r.nextCursor;}while(after);return items;}
 async function object(name){assert(name.startsWith(`ai-derived/${c.DB}/${owner.uid}/`));return d.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o/${encodeURIComponent(name)}?alt=media`);}
 try{
 const old=JSON.parse(fs.readFileSync(path.join(d.DIR,'e2e/registry.private.json')));assert(old.syntheticOnly);s.context={...old.context,localCourseUUID:crypto.randomUUID(),occurrenceKey:'image-connector-'+s.run};s.catalog=old.catalog;s.legacy=[];
 // Preserve both old OCR and previously stopped rollout's sources, read-only.
 for(const item of [...old.legacy,...old.sources]){assert(item.sourceId);const source=await document(c.DB,'aiSources/'+item.sourceId);assert.equal(source.fields.ownerUserId.stringValue,owner.uid);const items=await evidence(item.sourceId);s.legacy.push({sourceId:item.sourceId,sourceHash:documentDigest(source),itemsHash:documentDigest(items),updateTime:source.updateTime});}save(s);
 const cap=(await call('aiListSources',{context:s.context})).inputCapabilities;assert.equal(cap.image.pipelineVersion,'image-auto-v1');assert.equal(cap.pdf.pipelineVersion,'pdf-auto-v1');assert.equal(cap.image.fallback,false);
 const fixtures=require('./image_router_fixtures.cjs').generate(path.join(DIR,'fixtures')),selected=['plain','paragraph','two-label-arrow','short-arrow-flow','mixed-pdf'];const defaultUsage=await document('(default)','aiUsage/'+owner.uid,true),defaultPeriods=await d.read(db('(default)','aiUsage/'+owner.uid+'/periods?pageSize=100'));
 for(const key of selected){const f=fixtures.find(x=>x.key===key);assert(f);const type=f.type||'image',bytes=fs.readFileSync(path.join(DIR,'fixtures',f.file)),row={key,status:'CREATE_ATTEMPTED'};s.sources.push(row);save(s);
 const created=await call('aiCreateSource',{clientRequestId:'connector-'+s.run+'-'+key,type,title:'Synthetic connector routing '+key,mime:type==='image'?'image/png':'application/pdf',size:bytes.length,context:s.context});row.sourceId=created.sourceId;row.status='CREATED';save(s);assert.equal(created.pipelineVersion,type+'-auto-v1');const u=uploadTarget(created.upload.url,row.sourceId,owner.uid);row.status='UPLOAD_ATTEMPTED';save(s);const up=await fetch(u,{method:'PUT',redirect:'error',headers:created.upload.headers,body:bytes,signal:AbortSignal.timeout(120000)});assert.equal(up.status,200);row.status='UPLOADED';save(s);await call('aiCompleteSource',{sourceId:row.sourceId});
 let ready;for(let i=0;i<180;i++){ready=await call('aiGetSource',{sourceId:row.sourceId});if(ready.status==='ready')break;assert(!['failed','partial_ready','deleted','deleting'].includes(ready.status),'Worker terminal '+ready.error?.code);if(i%12===0)console.log(key+': '+ready.status+(ready.error?.code?' '+ready.error.code:''));await sleep(5000);}assert.equal(ready.status,'ready');assert.equal(ready.sharingEnabled,false);assert.equal(ready.knowledgeVisibility,'private');assert.equal(ready.courseOfferingId,s.catalog.year+':'+s.catalog.classDocId);assert.equal(ready.courseSnapshot.syllabusUrl,s.catalog.syllabusUrl);assert.equal(ready.courseSnapshot.yearSource,'syllabus');
 const pages=ready.recognition.routing.pages;assert.deepEqual(pages.map(x=>x.route),type==='pdf'?f.expected:[f.expected]);const stored=doc(await document(c.DB,'aiSources/'+row.sourceId));assert.equal(stored.ownerUserId,owner.uid);assert.equal(await document('(default)','aiSources/'+row.sourceId,true),null);
 const ev=await evidence(row.sourceId),chunks=await d.read(db(c.DB,`aiSources/${row.sourceId}/runs/${stored.activeRun}/chunks?pageSize=100`));assert(!chunks.nextPageToken);const chunkItems=chunks.documents.map(doc);assert.deepEqual(chunkItems.map(x=>({text:x.text,method:x.method,locator:x.locator})),ev.map(x=>({text:x.text,method:x.method,locator:x.locator})));
 const own=[];let cursor,pagesRead=0;do{assert(++pagesRead<=100,'Bounded retrieval pagination');const retrieval=await call('aiRetrieveContext',{courseOfferingId:ready.courseOfferingId,lectureIds:[ready.lectureId],purpose:'lecture_summary',maxCharacters:30000,...(cursor?{after:cursor}:{})});own.push(...retrieval.items.filter(x=>x.sourceId===row.sourceId));assert(!retrieval.nextCursor||retrieval.nextCursor!==cursor,'Retrieval cursor repeated');cursor=retrieval.nextCursor;}while(cursor);assert(own.length);const objects=await d.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o?prefix=${encodeURIComponent(`ai-derived/${c.DB}/${owner.uid}/${row.sourceId}/`)}`);assert(!objects.nextPageToken);const trace=[];
 for(const [i,page]of pages.entries()){const suffix=type==='pdf'?`pdf-auto-v1-page-${i+1}.json`:'image-auto-v1-final.json',name=objects.items.find(x=>x.name.endsWith('/'+suffix))?.name;assert(name);const cp=await object(name),select=xs=>xs.filter(x=>type==='image'||x.locator.pageNumber===i+1);assert.equal(cp.unit.method,page.route);for(const xs of [chunkItems,ev,own])assert.equal(joinChunks(select(xs)),cp.unit.text,'Qwen finalText -> Unit/chunks/Evidence/retrieval');
 const expectedChunks=require('../functions/lib/ai/domain').chunksFor([cp.unit]);assert.deepEqual(select(ev).map(x=>({text:x.text,method:x.method,locator:x.locator})),expectedChunks.map(x=>({text:x.text,method:x.method,locator:x.locator})));for(const x of select(own)){const found=ev.find(y=>y.chunkId===x.chunkId);assert(found);assert.equal(x.text,found.text);assert.deepEqual(x.locator,found.locator);assert.equal(x.method,found.method);}
 const probeSuffix=type==='pdf'?suffix.replace('.json','-ocr-probe.json'):'image-auto-v1-ocr-probe.json',probeName=objects.items.find(x=>x.name.endsWith('/'+probeSuffix))?.name,probe=probeName?await object(probeName):null;
 if(page.route==='multimodal_ai'){assert.equal(page.provider,'groq');assert.equal(page.model,'qwen/qwen3.8-27b');assert(page.totalTokens>0);assert.notEqual(cp.unit.text,probe?.text);const pricing=require('../functions/lib/ai/pricing').RECOGNITION_PRICING.image;assert(Math.abs(page.aiCostUSD-(page.inputTokens*pricing.inputPricePerMillionTokens+page.outputTokens*pricing.outputPricePerMillionTokens)/1e6)<1e-12);}
 if(key==='two-label-arrow'||key==='short-arrow-flow'||(type==='pdf'&&i===2)){const labels=key==='two-label-arrow'?['Observation','Question']:['Observation','Question','Hypothesis','Experiment','Conclusion','Result'];for(const l of labels)assert(cp.unit.text.includes(l));assert(/→|↓|矢印|接続|connect|arrow/i.test(cp.unit.text));assert(!/Result\s*(?:→|->|⇒|から)\s*Observation/i.test(cp.unit.text),'Invented closing edge');}
 if(key==='short-arrow-flow'){assert.equal(page.features.relationMark,false);assert.equal(page.features.lineScore,0);assert(page.features.connectorComponents>0);}
 if(page.route==='vision_ocr')assert.equal(cp.unit.text,probe.text.trim());if(page.route==='native_text'){assert.equal(page.totalTokens,0);assert.equal(probe,null);assert.equal(page.features.connectorComponents,undefined);}
 trace.push({pageNumber:type==='pdf'?i+1:null,route:page.route,provider:page.provider,model:page.model,metadata:page,ocrProbe:probe?.text||null,finalText:cp.unit.text,unit:cp.unit,chunkText:joinChunks(select(chunkItems)),evidenceText:joinChunks(select(ev)),retrieveContextText:joinChunks(select(own)),locatorConsistent:true});
 }
 fs.writeFileSync(path.join(DIR,key+'-result.private.json'),JSON.stringify({source:ready,trace,items:ev},null,2),{mode:0o600});row.status='PASS';s.results.push({key,routes:pages.map(x=>x.route),tokens:ready.recognition.totalTokens,costUSD:ready.recognition.estimatedCostUSD,processingMs:ready.recognition.processingMs});save(s);console.log(JSON.stringify(s.results.at(-1)));
 }
 for(const old of s.legacy){const current=await document(c.DB,'aiSources/'+old.sourceId);assert.equal(documentDigest(current),old.sourceHash);assert.equal(current.updateTime,old.updateTime);assert.equal(documentDigest(await evidence(old.sourceId)),old.itemsHash);}assert.equal(documentDigest(await document('(default)','aiUsage/'+owner.uid,true)),documentDigest(defaultUsage));assert.equal(documentDigest(await d.read(db('(default)','aiUsage/'+owner.uid+'/periods?pageSize=100'))),documentDigest(defaultPeriods));
 const permissionChecks=[];const testSource=s.sources.find(x=>x.key==='short-arrow-flow').sourceId,rawSource=doc(await document(c.DB,'aiSources/'+testSource));
 for(const [role,token]of [['anonymous',null],['pilot',owner.token]])for(const [service,url,header]of [['Firestore',db(c.DB,'aiSources/'+testSource),token?'Bearer '+token:null],['Storage',`https://firebasestorage.googleapis.com/v0/b/${c.B}/o/${encodeURIComponent(rawSource.storagePath)}?alt=media`,token?'Firebase '+token:null]]){const resp=await fetch(url,{headers:header?{Authorization:header}:{},signal:AbortSignal.timeout(45000)});await resp.body?.cancel();assert.equal(resp.status,403);permissionChecks.push({role,service,status:403});}
 // A private, sanitized mirror of real API results exercises the existing UIKit
 // display test (five fresh inputs plus unchanged legacy OCR). No UID/source ID.
 const ui=[];for(const row of s.sources){const result=JSON.parse(fs.readFileSync(path.join(DIR,row.key+'-result.private.json')));ui.push({key:row.key==='mixed-pdf'?'pdf':'image-'+row.key,evidence:{status:result.source.status,pipelineVersion:result.source.pipelineVersion,recognition:result.source.recognition,processingMs:result.source.processingMs,items:result.items.map(({chunkId,text,method,unitIndex,locator})=>({chunkId,text,method,unitIndex,locator}))},trace:result.trace.map(x=>({pageNumber:x.pageNumber,finalText:x.finalText}))});}
 const legacyId=old.legacy[0].sourceId,legacySource=await call('aiGetSource',{sourceId:legacyId}),legacyItems=await evidence(legacyId);ui.push({key:'legacy-ocr',evidence:{status:legacySource.status,pipelineVersion:legacySource.pipelineVersion,recognition:legacySource.recognition,processingMs:legacySource.processingMs,items:legacyItems.map(({chunkId,text,method,unitIndex,locator})=>({chunkId,text,method,unitIndex,locator}))},trace:[{pageNumber:null,finalText:joinChunks(legacyItems)}]});
 const uiDir=path.join(c.ROOT,'AogakuTests/DevFixtures');fs.mkdirSync(uiDir,{recursive:true});fs.writeFileSync(path.join(uiDir,'visual-router-production.json'),JSON.stringify(ui),{mode:0o600});
 s.directAccess=permissionChecks;const last=await d.snapshot();d.protectedCheck(deploy.load('baseline'),last,deploy.load('execution'));deploy.policy(last,await d.rawFunctions(),'RUNNING');deploy.save('e2e-final-protected',last);s.status='PRODUCTION_IMAGE_ROUTING_E2E_PASS';save(s);console.log(s.status);
 }catch(e){s.status='STOPPED';s.safeError=e.name;save(s);console.error('SAFE STOP production synthetic '+e.name+'; no replay or additional mutation');process.exitCode=1;}
}
if(require.main===module)main().catch(e=>{console.error('SAFE STOP '+e.name);process.exitCode=1});

module.exports={documentDigest};
