#!/usr/bin/env node
// Registered synthetic inputs ONLY. No source/account deletion, reconcile,
// provider fault injection, quota limit, sharing or arbitrary fixture replay.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),https=require('node:https');
const c=require('./production_phase5a_common.cjs'),reads=require('./production_read_retry.cjs');
const base=database=>`https://firestore.googleapis.com/v1/projects/${c.P}/databases/${database}/documents/`;
function value(v){if(v.stringValue!==undefined)return v.stringValue;if(v.integerValue!==undefined)return Number(v.integerValue);if(v.doubleValue!==undefined)return v.doubleValue;if(v.booleanValue!==undefined)return v.booleanValue;if(v.nullValue!==undefined)return null;if(v.mapValue)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,value(x)]));if(v.arrayValue)return(v.arrayValue.values||[]).map(value);if(v.timestampValue)return v.timestampValue;return v;}
const doc=d=>Object.fromEntries(Object.entries(d.fields||{}).map(([k,v])=>[k,value(v)]));
async function cloudDoc(database,p,allow404=true){const {response,data}=await reads.read(base(database)+p,{headers:{Authorization:'Bearer '+await c.cloud.oauth()}},{allowStatuses:allow404?[404]:[],sourceName:'phase5a_document_boundary'});return response.status===404?null:doc(data);}
function uploadTarget(url,sourceId,uid){const u=new URL(url);assert.equal(u.protocol,'https:');assert(!u.username&&!u.password&&!u.port);const wanted=`/${c.B}/ai-inputs/${c.DB}/${uid}/${sourceId}/`;assert(u.hostname==='storage.googleapis.com'&&decodeURIComponent(u.pathname).startsWith(wanted),'STOP: wrong signed upload target');return u;}
async function main(action){assert(['inputs','edges','finish-upload-retry','permissions'].includes(action));assert.equal(c.load('execution').status,'QUEUE_RUNNING');assert.equal(c.load('gates').status,'PASS');
 const plan=c.load('fixture-plan'),file=path.join(c.DIR,'e2e.json');let s=fs.existsSync(file)?c.load('e2e'):{status:'STARTED',runId:plan.runId,sources:{},results:[],attempts:[],syntheticOnly:true,sourceDeletionsPerformed:0,phase5bAuthorized:false};if(action!=='finish-upload-retry')assert(s.status!=='STOPPED');assert.equal(s.runId,plan.runId);const persist=()=>c.save('e2e',s),uid=c.operator().allowedUIDs[0];
 async function call(name,data,role='pilot'){
  assert(c.CALLABLES.includes(name));assert(name!=='aiDeleteSource'&&name!=='aiUpdateSource','No source deletion or sharing changes in Phase5a harness');const a=await c.auth(role);
  const attempt={function:name,role,payloadSha256:c.hash(data),at:new Date().toISOString(),status:'UNKNOWN'};s.attempts.push(attempt);persist();
  const r=await fetch(`https://${c.R}-${c.P}.cloudfunctions.net/${name}`,{method:'POST',redirect:'error',headers:{Authorization:'Bearer '+a.token,'Content-Type':'application/json'},body:JSON.stringify({data}),signal:AbortSignal.timeout(120000)}),d=await r.json().catch(()=>({}));attempt.httpStatus=r.status;attempt.status='RECEIVED';persist();
  if(!r.ok||d.error){const e=Error(d.error?.details?.code||d.error?.status||'CALLABLE_HTTP_'+r.status);e.code=d.error?.details?.code||d.error?.status;throw e;}return d.result;
 }
 async function storage(p,allow404=false){assert(p.startsWith(`ai-inputs/${c.DB}/${uid}/`)||p.startsWith(`ai-derived/${c.DB}/${uid}/`));const {response,data}=await reads.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o/${encodeURIComponent(p)}`,{headers:{Authorization:'Bearer '+await c.cloud.oauth()}},{allowStatuses:allow404?[404]:[],sourceName:'phase5a_storage_boundary'});return response.status===404?null:data;}
 async function upload(source,bytes){const u=uploadTarget(source.upload.url,source.sourceId,uid);assert.equal(source.upload.headers['x-goog-if-generation-match'],'0');const r=await fetch(u,{method:'PUT',redirect:'error',headers:source.upload.headers,body:bytes,signal:AbortSignal.timeout(120000)});assert(r.ok,'Signed fixture upload HTTP '+r.status);}
 async function ready(id){const trace=[];for(let i=0;i<120;i++){const x=await call('aiGetSource',{sourceId:id});if(trace.at(-1)!==x.status)trace.push(x.status);if(x.status==='ready')return {source:x,trace};assert(!['failed','partial_ready','deleting','deleted'].includes(x.status),'Pipeline '+x.status+' '+(x.error?.code||''));if(i%10===0)console.log('Synthetic pipeline waiting: '+x.status);await new Promise(r=>setTimeout(r,3000));}throw Error('STOP: pipeline wait exceeded; no retry of create/upload');}
 async function contextForRun(){
  if(s.context)return s.context;const listing=await c.read(base('(default)')+'classes?pageSize=100','GET',undefined,{boundedPage:true});assert((listing.documents||[]).length,'Catalog empty');let selected;
  for(const d of listing.documents){const id=d.name.split('/').pop(),v=doc(d),url=v.url||v.syllabusURL||'';if(!/^\d{5}$/.test(id))continue;let year;try{year=Number(new URL(url).searchParams.get('YR'));}catch{continue;}if(Number.isInteger(year)&&year>=2000&&year<=2100){selected={classDocId:id,year,url};break;}}
  assert(selected,'No five-digit class with valid syllabus YR in bounded catalog sample');s.catalog={classDocId:selected.classDocId,year:selected.year,syllabusUrl:selected.url,readDatabase:'(default)'};
  // URL omitted deliberately: server must read the existing default catalog,
  // then freeze its actual URL/YR metadata in the source's named-DB snapshot.
  s.context={classDocId:selected.classDocId,year:selected.year,semester:'fall',dayID:Math.floor(Date.now()/86400000),localCourseUUID:crypto.randomUUID(),occurrenceKey:'phase5a-'+s.runId};persist();return s.context;
 }
 async function verify(type,created){const id=created.sourceId,{source,trace}=await ready(id);assert.equal(source.databaseId,c.DB);assert.equal(source.courseOfferingId,`${s.catalog.year}:${s.catalog.classDocId}`);const snapshot=source.courseSnapshot;assert.equal(snapshot.classDocId,s.catalog.classDocId);assert.equal(snapshot.year,s.catalog.year);assert.equal(snapshot.yearSource,'syllabus');assert.equal(snapshot.syllabusUrl,s.catalog.syllabusUrl);assert.equal(snapshot.semester,s.context.semester);assert.equal(snapshot.courseOfferingId,source.courseOfferingId);assert.equal(source.sharingEnabled,false);assert.equal(source.rawVisibility,'private');assert.equal(source.knowledgeVisibility,'private');
  const evidence=await call('aiGetEvidence',{sourceId:id});assert(evidence.items.length>0);const methods=[...new Set(evidence.items.map(x=>x.method))];
  if(type==='image')assert(evidence.items.every(x=>x.method==='vision_ocr'&&x.locator.imageIndex===1));
  if(type==='pdf'){assert.deepEqual([...new Set(evidence.items.map(x=>x.locator.pageNumber))].sort(),[1,2]);assert(methods.includes('pdf_text')&&methods.includes('vision_ocr'));}
  if(type==='audio')assert(evidence.items.every(x=>x.method==='groq_asr'&&x.locator.startMs>=0&&x.locator.endMs>x.locator.startMs));
  if(type==='note')assert(evidence.items.every(x=>x.locator.endChar>x.locator.startChar));
  const context=await call('aiRetrieveContext',{courseOfferingId:source.courseOfferingId,purpose:'lecture_summary',maxCharacters:30000});assert(context.items.some(x=>x.sourceId===id));const question=await call('aiRetrieveContext',{courseOfferingId:source.courseOfferingId,purpose:'question',query:'根拠資料',maxCharacters:30000});assert(question.items.some(x=>x.sourceId===id),'Synthetic grounded question lookup missing source');
  const list=await call('aiListSources',{context:s.context});assert(list.items.some(x=>x.sourceId===id));
  const named=await cloudDoc(c.DB,`aiSources/${id}`,false);assert.equal(named.ownerUserId,uid);assert.equal(named.databaseId,c.DB);assert.equal(named.status,'ready');assert.equal(named.courseOfferingId,source.courseOfferingId);assert.deepEqual(named.courseSnapshot,snapshot);assert.equal(await cloudDoc('(default)',`aiSources/${id}`),null);
  // The worker stores chunks beneath a run path without creating its parent
  // document. Firestore permits this; verify actual chunks rather than demand
  // a nonexistent run metadata document.
  assert(named.storagePath.startsWith(`ai-inputs/${c.DB}/${uid}/${id}/`));const chunks=await c.read(base(c.DB)+`aiSources/${id}/runs/${named.activeRun}/chunks?pageSize=100`, 'GET',undefined,{sourceName:'phase5a_chunks_boundary'});assert((chunks.documents||[]).length>0);
  const defaultChunks=await c.read(base('(default)')+`aiSources/${id}/runs/${named.activeRun}/chunks?pageSize=100`,'GET',undefined,{sourceName:'phase5a_default_chunks_boundary'});assert.equal((defaultChunks.documents||[]).length,0);
  const derived=await c.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o?prefix=${encodeURIComponent(`ai-derived/${c.DB}/${uid}/${id}/`)}`,'GET',undefined,{sourceName:'phase5a_derived_prefix'});assert((derived.items||[]).length>0);assert(derived.items.every(o=>o.name.startsWith(`ai-derived/${c.DB}/${uid}/${id}/`)));
  const result={type,sourceId:id,status:'PASS',ready:true,trace,methods,evidenceCount:evidence.items.length,locators:evidence.items.map(x=>x.locator),list:true,retrieveContext:true,questionContext:true,namedDatabase:c.DB,defaultSourceAbsent:true,classDocId:s.catalog.classDocId,year:s.catalog.year,yearSource:'syllabus',snapshotPreserved:true,sharing:false};s.results.push(result);persist();console.log('PASS synthetic '+type+': ready / provider extraction / evidence / grounded retrieval / named DB boundary');return result;
 }
 async function input(type,key=type){assert(!s.sources[key],'STOP: no automatic repeat of fixture creation');const context=await contextForRun(),asset={image:'sample-photo.jpg',pdf:'sample-document.pdf',audio:'sample-audio.m4a'}[type],bytes=asset?fs.readFileSync(path.join(c.DIR,'assets',asset)):null;
  const data={clientRequestId:'phase5a-'+s.runId+'-'+key,type,title:'Synthetic Phase5a '+key+' '+s.runId.slice(0,8),mime:{note:'text/plain',image:'image/jpeg',pdf:'application/pdf',audio:'audio/mp4'}[type],context,...(bytes?{size:bytes.length}:{text:'検索拡張生成 RAG は根拠資料の出典を保存し、回答を検証する。内部テスト専用の架空メモです。'}),...(type==='audio'?{durationSeconds:Math.ceil(c.load('assets/manifest').audioDurationSeconds)}:{})};
  const expected=c.hash([uid,data.clientRequestId]);s.sources[key]={sourceId:expected,data,creationAttempted:true};persist();const created=await call('aiCreateSource',data);assert.equal(created.sourceId,expected);assert.equal(created.databaseId,c.DB);s.sources[key].accepted=true;persist();
  if(bytes){assert(created.upload);await upload(created,bytes);const p=`ai-inputs/${c.DB}/${uid}/${created.sourceId}/${type==='audio'?'audio/original.m4a':'original'}`,raw=await storage(p);assert.equal(Number(raw.size),bytes.length);assert.equal(raw.md5Hash,crypto.createHash('md5').update(bytes).digest('base64'));s.sources[key].rawUploadVerified=true;persist();}
  await call('aiCompleteSource',{sourceId:created.sourceId});return verify(type,created);
 }
 try{
  persist();if(action==='inputs'){
   assert.equal(s.results.length,0);assert.equal(c.load('assets/manifest').syntheticOnly,true);assert(c.load('assets/manifest').audioDurationSeconds<60);const beforeDefault=await cloudDoc('(default)',`aiUsage/${uid}`),beforePeriods=await c.read(base('(default)')+`aiUsage/${uid}/periods?pageSize=100`,'GET',undefined,{sourceName:'phase5a_default_usage_boundary'});s.defaultUsageBefore=beforeDefault;s.defaultPeriodsBefore=beforePeriods;persist();
   for(const t of ['note','image','pdf','audio'])await input(t);
   assert.deepEqual(await cloudDoc('(default)',`aiUsage/${uid}`),beforeDefault);assert.deepEqual(await c.read(base('(default)')+`aiUsage/${uid}/periods?pageSize=100`,'GET',undefined,{sourceName:'phase5a_default_usage_boundary'}),beforePeriods);const periods=await c.read(base(c.DB)+`aiUsage/${uid}/periods?pageSize=100`,'GET',undefined,{sourceName:'phase5a_usage_boundary'});assert((periods.documents||[]).length>0);s.usageInNamedDatabase=true;s.status='FOUR_INPUTS_PASS';persist();console.log('Four production synthetic inputs PASS; no default AI source/usage write');return;
  }
  if(action==='finish-upload-retry'){
   assert.equal(s.status,'STOPPED');assert.equal(s.error,'ERR_ASSERTION');assert.equal(s.results.length,4);assert.equal(s.duplicateRequest.status,'PASS');const proof=c.load('retry-harness-proof'),old=s.sources['interrupted-upload'];assert.equal(proof.status,'PASS');assert.equal(proof.registeredSourceId,old.sourceId);assert.equal(s.attempts.at(-1).function,'aiRetrySource');assert.equal(s.attempts.at(-1).httpStatus,200);
   const backup=path.join(c.DIR,'retry-harness-stop/e2e.json');assert(!fs.existsSync(backup));fs.mkdirSync(path.dirname(backup),{recursive:true,mode:0o700});fs.copyFileSync(file,backup);fs.chmodSync(backup,0o600);
   const current=await call('aiGetSource',{sourceId:old.sourceId});assert.equal(current.status,'awaiting_upload');assert.equal(await storage(`ai-inputs/${c.DB}/${uid}/${old.sourceId}/original`,true),null);
   s.retryHarnessStopPreserved=true;s.status='RETRY_CONTINUING';delete s.error;persist();
   // iOS receipt recovery obtains a fresh URL via the same request ID. This
   // intentional recovery call creates no new source and does not repeat the
   // already successful aiRetrySource or the intentional interrupted PUT.
   const recovered=await call('aiCreateSource',old.data);assert.equal(recovered.sourceId,old.sourceId);assert.equal(recovered.status,'awaiting_upload');assert(recovered.upload);const bytes=fs.readFileSync(path.join(c.DIR,'assets/sample-photo.jpg'));await upload(recovered,bytes);const raw=await storage(`ai-inputs/${c.DB}/${uid}/${old.sourceId}/original`);assert.equal(Number(raw.size),bytes.length);assert.equal(raw.md5Hash,crypto.createHash('md5').update(bytes).digest('base64'));await call('aiCompleteSource',{sourceId:old.sourceId});await verify('image',recovered);
   s.interruptedUpload={status:'PASS',rawAbsentAfterAbort:true,sameSourceId:true,retryReady:true,recovery:'same request receipt refresh',successfulAiRetryNotReplayed:true};s.status='EDGES_PASS';persist();console.log('PASS interrupted upload → same-receipt signed URL recovery → full PUT → ready; previous successful retry not replayed');return;
  }
  assert(['FOUR_INPUTS_PASS','EDGES_PASS','PERMISSIONS_PASS'].includes(s.status));
  if(action==='edges'){
   assert.equal(s.status,'FOUR_INPUTS_PASS');const old=s.sources.note,duplicate=await call('aiCreateSource',old.data);assert.equal(duplicate.sourceId,old.sourceId);assert.equal(duplicate.status,'ready');s.duplicateRequest={status:'PASS',sameSourceId:true};persist();
   const type='image',key='interrupted-upload',bytes=fs.readFileSync(path.join(c.DIR,'assets/sample-photo.jpg')),context=s.context;assert(!s.sources[key]);const data={clientRequestId:'phase5a-'+s.runId+'-'+key,type,title:'Synthetic interrupted upload',mime:'image/jpeg',size:bytes.length,context},id=c.hash([uid,data.clientRequestId]);s.sources[key]={sourceId:id,data,creationAttempted:true};persist();const source=await call('aiCreateSource',data);assert.equal(source.sourceId,id);const u=uploadTarget(source.upload.url,id,uid);
   await new Promise((resolve,reject)=>{let interrupted=false;const request=https.request(u,{method:'PUT',headers:{...source.upload.headers,'Content-Length':bytes.length}},r=>{r.resume();reject(Error('Unexpected completed partial PUT HTTP '+r.statusCode));});request.on('error',e=>interrupted?resolve():reject(e));request.write(bytes.subarray(0,Math.floor(bytes.length/2)));setTimeout(()=>{interrupted=true;request.destroy(Error('SYNTHETIC_UPLOAD_INTERRUPTION'));},500);});
   const p=`ai-inputs/${c.DB}/${uid}/${id}/original`;assert.equal(await storage(p,true),null,'Interrupted object unexpectedly finalized');try{await call('aiCompleteSource',{sourceId:id});throw Error('Incomplete upload accepted');}catch(e){assert.equal(e.code,'UPLOAD_INCOMPLETE');}
   const retried=await call('aiRetrySource',{sourceId:id});assert.equal(retried.sourceId,id);const recovered=await call('aiCreateSource',data);assert.equal(recovered.sourceId,id);assert(recovered.upload);await upload(recovered,bytes);await call('aiCompleteSource',{sourceId:id});await verify(type,recovered);s.interruptedUpload={status:'PASS',rawAbsentAfterAbort:true,sameSourceId:true,retryReady:true,recovery:'same request receipt refresh'};s.status='EDGES_PASS';persist();console.log('PASS duplicate request + interrupted upload/retry; no source deletion races');return;
  }
  const owner=await c.auth('pilot'),outsider=await c.auth('outsider'),id=s.sources.image.sourceId,raw=`ai-inputs/${c.DB}/${uid}/${id}/original`,proof=[];
  for(const [role,token]of [['anonymous',null],['approvedUID',owner.token],['nonAllowedUID',outsider.token]]){
   const get=await fetch(base(c.DB)+`aiSources/${id}`,{headers:token?{Authorization:'Bearer '+token}:{},signal:AbortSignal.timeout(45000)});assert.equal(get.status,403,'Direct named Firestore admission');await get.body?.cancel();proof.push({role,service:'Firestore direct',httpStatus:403});
   const storageRead=await fetch(`https://firebasestorage.googleapis.com/v0/b/${c.B}/o/${encodeURIComponent(raw)}?alt=media`,{headers:token?{Authorization:'Firebase '+token}:{},signal:AbortSignal.timeout(45000)});assert.equal(storageRead.status,403,'Direct Storage admission');await storageRead.body?.cancel();proof.push({role,service:'Storage direct',httpStatus:403});
  }
  for(const n of ['aiGetSource','aiGetEvidence','aiRetrieveContext'])try{await call(n,n==='aiRetrieveContext'?{courseOfferingId:`${s.catalog.year}:${s.catalog.classDocId}`,purpose:'lecture_summary'}:{sourceId:id},'outsider');throw Error('Non-allowed UID read accepted');}catch(e){assert.equal(e.code,'AI_INPUT_NOT_ENABLED');}
  s.permissions={status:'PASS',checks:proof,nonAllowedCallableReadsDenied:3,sharingOff:true};s.status='PERMISSIONS_PASS';persist();console.log('PASS direct Firestore/Storage anonymous/owner/outsider denies and real-source non-allowed Callable denial');
 }catch(e){s.status='STOPPED';s.error=c.masked(e.code||e.message);persist();console.error('STOP Phase5a E2E: '+c.masked(e.code||e.message)+'; fixtures retained; no create/upload automatic retry or deletion');throw e;}
}
module.exports={uploadTarget,value};if(require.main===module)main(process.argv[2]).catch(()=>process.exitCode=1);
