#!/usr/bin/env node
// OFFLINE REVIEW ONLY. No network/deploy/mutation entry point.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'build/image-router-production-review'),p=require('./production_recognition_review.cjs'),{sourceManifest}=require('./deploy_production_phase3a.cjs');
const MODULES=Object.freeze(['lib/ai/visualExtraction.js','lib/ai/visualRouter.js']);
function assertModuleDelta(before,after){assert.deepEqual(Object.keys(after).sort(),Object.keys(before).sort());const changed=Object.keys(before).filter(n=>before[n]!==after[n]).sort();assert.deepEqual(changed,[...MODULES]);return changed;}
function validatePlan(plan){assert.equal(plan.productionDeploymentAuthorized,false);assert.deepEqual(plan.functions,['aiProcessSource']);assert.deepEqual(plan.changedModules,[...MODULES]);assert.equal(plan.updateMask,'buildConfig.source');assert.equal(plan.environmentUpdateAuthorized,false);assert.equal(plan.iamUpdateAuthorized,false);assert.equal(plan.oldSourceReprocessingAuthorized,false);assert.equal(plan.queuePauseDrainRestoreRequiresApproval,true);assert.equal(plan.sharing,false);assert.equal(plan.schedulerState,'PAUSED');assert.equal(plan.originalQueueState,'RUNNING');assert.equal(plan.pipelineVersion,'image-auto-v1');assert.equal(plan.pdfPipelineVersion,'pdf-auto-v1');assert.equal(plan.model,'qwen/qwen3.8-27b');p.validateIdentity(plan.target);assert.equal(plan.allowlistCount,2);}
function prepare(){assert.equal(execFileSync('git',['branch','--show-current'],{cwd:ROOT,encoding:'utf8'}).trim(),'codex/ai-recognition-comparison-lab');assert(!fs.existsSync(OUT),'Never overwrite review or deployment evidence');
 const fresh=JSON.parse(fs.readFileSync(path.join(ROOT,'build/image-router-fix/production-fresh.private.json')));assert.equal(fresh.productionMutations,0);assert(Date.now()-Date.parse(fresh.at)>=0&&Date.now()-Date.parse(fresh.at)<600000,'Fresh production read-only state required');assert.equal(Object.keys(fresh.sourceProof).length,25);assert.equal(fresh.snapshot.resources.queue.data.state,'RUNNING');
 const beforeZip=path.join(ROOT,'build/production-visual-router-20261009/sources/image-routing-review-aiProcessSource.zip'),before=sourceManifest(beforeZip);assert.equal(crypto.createHash('sha256').update(JSON.stringify(before)).digest('hex'),fresh.sourceProof.aiProcessSource.sha256);fs.mkdirSync(OUT,{recursive:true,mode:0o700});
 execFileSync('python3',['-c',`import zipfile,sys,pathlib
src,dst,root,*mods=sys.argv[1:]
with zipfile.ZipFile(src) as z,zipfile.ZipFile(dst,'w',zipfile.ZIP_DEFLATED) as out:
 for n in z.namelist():
  if not n.endswith('/'):
   assert not n.startswith('/') and '..' not in n.split('/')
   out.writestr(n,(pathlib.Path(root)/n).read_bytes() if n in mods else z.read(n))`,beforeZip,path.join(OUT,'candidate.zip'),path.join(ROOT,'functions'),...MODULES]);
 const after=sourceManifest(path.join(OUT,'candidate.zip')),changedModules=assertModuleDelta(before,after),worker=fresh.snapshot.functions.find(x=>x.name.endsWith('/aiProcessSource'));
 const plan={status:'IMAGE_ROUTING_REVIEW_AWAITING_APPROVAL',productionDeploymentAuthorized:false,target:p.TARGET,functions:['aiProcessSource'],changedModules,updateMask:'buildConfig.source',environmentUpdateAuthorized:false,iamUpdateAuthorized:false,oldSourceReprocessingAuthorized:false,queuePauseDrainRestoreRequiresApproval:true,sharing:false,schedulerState:'PAUSED',originalQueueState:'RUNNING',pipelineVersion:'image-auto-v1',pdfPipelineVersion:'pdf-auto-v1',model:'qwen/qwen3.8-27b',allowlistCount:fresh.cohort.allowedUIDCount,allowlistDigest:fresh.cohort.allowedUIDDigest,beforeRevision:worker.serviceConfig.revision,beforeManifest:fresh.sourceProof.aiProcessSource.sha256,afterManifest:crypto.createHash('sha256').update(JSON.stringify(after)).digest('hex'),beforeFiles:before,afterFiles:after,freshReadAt:fresh.at};validatePlan(plan);fs.writeFileSync(path.join(OUT,'review.json'),JSON.stringify(plan,null,2),{mode:0o600});console.log(JSON.stringify({status:plan.status,functions:plan.functions,changedModules,productionMutations:0,beforeRevision:plan.beforeRevision,candidateManifest:plan.afterManifest}));}
module.exports={MODULES,assertModuleDelta,validatePlan};if(require.main===module){assert.deepEqual(process.argv.slice(2),['prepare']);prepare();}
