#!/usr/bin/env node
// Explicitly approved pilot-only eight-input production E2E. Never creates Auth,
// changes environment/IAM/Rules, replays fixture mutations or deletes old materials.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const d=require('./deploy_production_visual_router.cjs'),op=require('./deploy_production_visual_latency.cjs'),c=require('./production_phase5a_common.cjs'),{joinChunks}=require('./evidence_adoption_dev.cjs');
const OUT=path.join(op.DIR,'e2e'),P=c.P,R=c.R,D=c.DB,sleep=ms=>new Promise(r=>setTimeout(r,ms)),digest=x=>crypto.createHash('sha256').update(x).digest('hex'),stable=require('./deploy_production_phase3a.cjs').hash;
const db=(id,p)=>`https://firestore.googleapis.com/v1/projects/${P}/databases/${id}/documents/${p}`,v={read:d.read};
function save(n,x){fs.mkdirSync(OUT,{recursive:true,mode:0o700});fs.writeFileSync(path.join(OUT,n+'.json'),JSON.stringify(x,null,2),{mode:0o600});}
async function document(id,p){const {response,data}=await require('./production_read_retry.cjs').read(db(id,p),{headers:{Authorization:'Bearer '+await c.cloud.oauth()}},{allowStatuses:[404],sourceName:'latency_boundary'});return response.status===404?null:data;}
const callTimes=[];
async function call(state,name,data){while(callTimes.length&&callTimes[0]<Date.now()-60000)callTimes.shift();if(callTimes.length>=100){await sleep(callTimes[0]+60100-Date.now());while(callTimes.length&&callTimes[0]<Date.now()-60000)callTimes.shift();}callTimes.push(Date.now());assert(['aiListSources','aiCreateSource','aiCompleteSource','aiGetSource','aiGetEvidence','aiRetrieveContext','aiDeleteSource'].includes(name));const auth=state.auth,start=performance.now();const r=await fetch(`https://${R}-${P}.cloudfunctions.net/${name}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+auth.token},body:JSON.stringify({data}),signal:AbortSignal.timeout(150000)}),v=await r.json();assert(r.ok,'Production '+name+' HTTP '+r.status+' '+v.error?.message);return {value:v.result,ms:performance.now()-start};}
async function evidence(state,sid,preview=false){const items=[];let after,latest;do{latest=(await call(state,'aiGetEvidence',{sourceId:sid,...(preview?{preview:true}:{}),...(after?{after}:{})})).value;items.push(...latest.items);after=latest.nextCursor;}while(after);return {items,latest};}
async function retrieveSource(state,source){const items=[];let after;const seen=new Set();do{const page=(await call(state,'aiRetrieveContext',{courseOfferingId:source.courseOfferingId,lectureIds:[source.lectureId],purpose:'lecture_summary',maxCharacters:30000,...(after?{after}:{})})).value;items.push(...page.items.filter(x=>x.sourceId===source.sourceId));after=page.nextCursor;if(after){assert(!seen.has(after),'Retrieval cursor cycle');seen.add(after);}}while(after);return items;}
async function benchmark(){
 assert.equal(op.load('execution').status,'DEPLOYED_E2E_PENDING');assert(!fs.existsSync(path.join(OUT,'registry.json')),'Never replay billed fixtures');
 const mode='production',state={projectId:P,run:crypto.randomUUID(),sources:[],results:[]};const raw=await d.rawFunctions(),auth=await d.pilotAuth(raw);state.user={uid:auth.uid};Object.defineProperty(state,"auth",{value:auth,enumerable:false});
 const old=JSON.parse(fs.readFileSync(path.join(c.ROOT,'build/production-visual-router-20261009/e2e/registry.private.json')));assert(old.syntheticOnly);state.context={...old.context,occurrenceKey:'latency-'+state.run};state.catalog=old.catalog;save('registry',state);const expected=op.load('baseline');d.protectedCheck(expected,await d.snapshot(),op.load('execution'));
 const legacy=[];for(const row of old.legacy){const x=await v.read(db(D,'aiSources/'+row.sourceId));assert.equal(x.fields.ownerUserId.stringValue,auth.uid);legacy.push({id:row.sourceId,digest:stable(x),evidence:stable((await evidence(state,row.sourceId)).items)});}
 const defaultUsage=await document('(default)','aiUsage/'+auth.uid),defaultPeriods=await v.read(db('(default)','aiUsage/'+auth.uid+'/periods?pageSize=100'));
 const cases=require('./visual_latency_fixtures.cjs').generate(path.join(OUT,'fixtures')).filter(x=>['plain','paragraph','two-label-arrow','short-arrow-flow','pdf-text-10','pdf-mixed-30','pdf-scanned','pdf-diagram'].includes(x.key)),rows=[];
 for(const [index,f]of cases.entries()){const bytes=fs.readFileSync(path.join(OUT,'fixtures',f.file)),row={mode,key:f.key,type:f.type,status:'CREATE_ATTEMPTED',uploadBytes:bytes.length,fixtureSHA:digest(bytes)};state.sources.push(row);save('registry',state);const start=performance.now(),context={...state.context,dayID:state.context.dayID+index+20};
  const created=(await call(state,'aiCreateSource',{clientRequestId:state.run+'-'+mode+'-'+f.key,type:f.type,title:'Synthetic latency '+mode+' '+f.key,mime:f.type==='pdf'?'application/pdf':'image/png',size:bytes.length,context})).value;row.sourceId=created.sourceId;save('registry',state);assert.equal(created.pipelineVersion,f.type+'-auto-v1');const u=new URL(created.upload.url);assert.equal(u.hostname,'storage.googleapis.com');assert(u.pathname.startsWith('/'+c.B+'/'));const uploading=performance.now();row.status='UPLOAD_ATTEMPTED';save('registry',state);const uploaded=await fetch(u,{method:'PUT',redirect:'error',headers:created.upload.headers,body:bytes,signal:AbortSignal.timeout(60000)});assert.equal(uploaded.status,200);row.actualUploadMs=performance.now()-uploading;row.status='COMPLETE_ATTEMPTED';save('registry',state);await call(state,'aiCompleteSource',{sourceId:row.sourceId,uploadMs:row.actualUploadMs});
  let ready,firstUsefulMs=null,observedPreviews=0,lastCount=0;for(let i=0;i<240;i++){ready=(await call(state,'aiGetSource',{sourceId:row.sourceId})).value;if(ready.status==='ready')break;assert(!['failed','partial_ready'].includes(ready.status),'Processing '+ready.error?.code);const count=ready.previewProgress?.completed||0;
   if(count>lastCount&&ready.previewVersion){let preview;try{preview=await evidence(state,row.sourceId,true);}catch(e){if(!String(e.message).includes('SOURCE_VERSION_CHANGED'))throw e;preview={items:[]};}if(preview.items.length){firstUsefulMs??=performance.now()-start;observedPreviews++;const ownRag=await retrieveSource(state,{...ready,sourceId:row.sourceId});if(ownRag.length){const published=(await call(state,'aiGetSource',{sourceId:row.sourceId})).value;assert.equal(published.status,'ready','Processing previews entered RAG');assert(ownRag.every(x=>x.activeVersion===published.activeVersion),'Preview run entered RAG');}save(mode+'-'+f.key+'-preview',{source:ready,items:preview.items});}lastCount=count;}
   await sleep(2000);
  }
  assert.equal(ready.status,'ready');assert.equal(ready.sharingEnabled,false);assert.equal(ready.courseOfferingId,state.catalog.year+':'+state.catalog.classDocId);assert.equal(ready.courseSnapshot.yearSource,'syllabus');const readyMs=performance.now()-start;const eStart=performance.now(),e=await evidence(state,row.sourceId),evidenceMs=performance.now()-eStart;firstUsefulMs??=performance.now()-start;
  const routes=ready.recognition.routing.pages.map(x=>x.route);assert.deepEqual(routes,f.type==='pdf'?f.expected:[f.expected],'Real route '+f.key);assert(e.items.length);const own=await retrieveSource(state,{...ready,sourceId:row.sourceId});
  const normalized=xs=>xs.map(({text,method,locator})=>({text,method,locator}));assert.deepEqual(normalized(own),normalized(e.items),'Evidence/retrieval full contract');
  const sourceDoc=await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${row.sourceId}`);const attempts=Number(sourceDoc.fields.attempts.integerValue);
  const previewPages=f.type==='pdf'?await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${row.sourceId}/runs/${ready.activeVersion}/previewPages?pageSize=100`):null;const firstPreviewAt=previewPages?.documents?.length?Math.min(...previewPages.documents.map(d=>Date.parse(d.createTime))):null;
  const latency=ready.latency;assert.equal(latency.version,'visual-latency-v1');assert(latency.totalProcessingMs>=0);assert(latency.queueWaitMs===null||latency.queueWaitMs>=0);assert.equal(latency.coldStartMs,null);if(mode==='production'&&f.type==='pdf'){assert.deepEqual(require('../functions/lib/ai/latency').VISUAL_EXECUTION,{aiConcurrency:2,ocrConcurrency:3,pageConcurrency:4,providerMaxSide:1800,routerMaxSide:640});for(const [stage,limit]of [[['aiMs'],2],[['ocrMs','ocrProbeMs'],3]]){const events=latency.providerSpans.filter(x=>stage.includes(x.stage)).flatMap(x=>[[x.startedAt,1],[x.finishedAt,-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let active=0;for(const [t,delta]of events){active+=delta;assert(active<=limit,'Provider concurrency exceeded');}}const noPreview=await evidence(state,row.sourceId,true);assert.equal(noPreview.items.length,0);}if(['two-label-arrow','short-arrow-flow'].includes(f.key))assert(ready.recognition.routing.pages[0].ocrProbeSkipped);
  const objects=await v.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o?prefix=${encodeURIComponent(`ai-derived/${D}/${state.user.uid}/${row.sourceId}/checkpoints/`)}`);assert(!objects.nextPageToken);
  const stored=await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${row.sourceId}/runs/${ready.activeVersion}/chunks?pageSize=100`);assert(!stored.nextPageToken);
  const {value}=require('./production_phase5a_e2e.cjs');const storedItems=(stored.documents||[]).map(d=>Object.fromEntries(Object.entries(d.fields||{}).map(([k,x])=>[k,value(x)])));assert.deepEqual(normalized(storedItems),normalized(e.items),'Stored chunks/Evidence');
  const pages=[];for(const page of ready.recognition.routing.pages){const number=page.pageNumber,subset=xs=>xs.filter(x=>f.type==='image'||x.locator.pageNumber===number),text=joinChunks(subset(e.items));assert(text.trim());const suffix=f.type==='pdf'?`pdf-auto-v1-page-${number}.json`:'image-auto-v1-final.json',name=objects.items.find(x=>x.name.endsWith('/'+suffix))?.name;assert(name);const checkpoint=await v.read(`https://storage.googleapis.com/storage/v1/b/${c.B}/o/${encodeURIComponent(name)}?alt=media`);assert.equal(checkpoint.unit.text,text,'Selected finalText/Unit/chunks/Evidence');assert.equal(checkpoint.unit.method,page.route);if(page.route==='multimodal_ai'){assert.equal(page.provider,'groq');assert.equal(page.model,'qwen/qwen3.8-27b');assert(page.totalTokens>0);const pricing=require('../functions/lib/ai/pricing').RECOGNITION_PRICING.image;assert(Math.abs(page.aiCostUSD-(page.inputTokens*pricing.inputPricePerMillionTokens+page.outputTokens*pricing.outputPricePerMillionTokens)/1e6)<1e-12);}if(f.key==='short-arrow-flow'){for(const label of ['Observation','Question','Hypothesis','Experiment','Conclusion','Result'])assert(text.includes(label));assert(/矢印|接続|→|arrow|connect/i.test(text));assert(!/Result\s*(?:→|から)\s*Observation/i.test(text));}pages.push({pageNumber:number||null,route:page.route,provider:page.provider,model:page.model,text,textSHA:digest(text),locator:subset(e.items).map(x=>x.locator)});}
  assert.equal(await document('(default)','aiSources/'+row.sourceId),null);
  const result={serverReadyMs:ready.updatedAt-ready.createdAt,firstServerUsefulMs:firstPreviewAt?firstPreviewAt-ready.createdAt:ready.updatedAt-ready.createdAt,attempts,timingResumed:false,key:f.key,type:f.type,fixtureSHA:row.fixtureSHA,latency,actualUploadMs:row.actualUploadMs,uploadBytes:bytes.length,firstUsefulMs,readyMs,evidenceMs,observedPreviews,routes,tokens:ready.recognition.totalTokens,costUSD:ready.recognition.estimatedCostUSD,ocrProbeSkipped:ready.recognition.routing.pages.filter(p=>p.ocrProbeSkipped).length,pages};save(mode+'-'+f.key+'-full',{source:ready,result,evidence:e.items,retrieval:own});rows.push(result);row.status='PASS';state.results.push({mode,key:f.key,status:'PASS'});save('registry',state);console.log(JSON.stringify({mode,key:f.key,workerMs:Math.round(latency.totalProcessingMs),firstUsefulMs:Math.round(firstUsefulMs),readyMs:Math.round(readyMs),routes:routes.length>10?ready.recognition.routing.counts:routes,calls:latency.providerCalls,skipped:result.ocrProbeSkipped,tokens:result.tokens,costUSD:result.costUSD}));
 }
 for(const row of legacy){assert.equal(stable(await v.read(db(D,'aiSources/'+row.id))),row.digest);assert.equal(stable((await evidence(state,row.id)).items),row.evidence);}
 assert.equal(stable(await document('(default)','aiUsage/'+auth.uid)),stable(defaultUsage));assert.equal(stable(await v.read(db('(default)','aiUsage/'+auth.uid+'/periods?pageSize=100'))),stable(defaultPeriods));
 const source=rows.find(x=>x.key==='short-arrow-flow'),sourceId=state.sources.find(x=>x.key===source.key).sourceId,stored=await v.read(db(D,'aiSources/'+sourceId));
 const permission=[];for(const [role,token]of [['anonymous',null],['pilot',auth.token]])for(const [service,url,header]of [['Firestore',db(D,'aiSources/'+sourceId),token?'Bearer '+token:null],['Storage',`https://firebasestorage.googleapis.com/v0/b/${c.B}/o/${encodeURIComponent(stored.fields.storagePath.stringValue)}?alt=media`,token?'Firebase '+token:null]]){const resp=await fetch(url,{headers:header?{Authorization:header}:{},signal:AbortSignal.timeout(45000)});await resp.body?.cancel();assert.equal(resp.status,403);permission.push({role,service,status:403});}
 const ui=[];for(const row of rows){const full=JSON.parse(fs.readFileSync(path.join(OUT,mode+'-'+row.key+'-full.json')));const make=(key,items,preview,source)=>{const groups=[...new Set(items.map(x=>x.locator.pageNumber))];const expectedText=groups.map(n=>(n?'[p.'+n+']\n':'')+joinChunks(items.filter(x=>x.locator.pageNumber===n))).join('\n');return {key,expectedText,evidence:{status:source.status,pipelineVersion:source.pipelineVersion,recognition:source.recognition,processingMs:source.processingMs,latency:source.latency,preview,progress:preview?source.previewProgress:null,items:items.map(({chunkId,text,method,unitIndex,locator})=>({chunkId,text,method,unitIndex,locator})),nextCursor:null}}};ui.push(make(row.key+'-ready',full.evidence,false,full.source));const previewPath=path.join(OUT,mode+'-'+row.key+'-preview.json');if(fs.existsSync(previewPath)){const q=JSON.parse(fs.readFileSync(previewPath));ui.push(make(row.key+'-preview',q.items,true,q.source));}}
 assert(ui.some(x=>x.key==='pdf-mixed-30-preview'),'Processing mixed PDF preview must be observed');const uiDir=path.join(c.ROOT,'AogakuTests/DevFixtures');fs.mkdirSync(uiDir,{recursive:true});fs.writeFileSync(path.join(uiDir,'visual-latency-production.json'),JSON.stringify(ui),{mode:0o600});
 const a=await d.snapshot();d.protectedCheck(expected,a,op.load('execution'));d.policyChecks(a,await d.rawFunctions(),'RUNNING');save(mode+'-results',rows);save(mode+'-benchmark-final',a);save('direct-access',{status:'PASS',checks:permission});state.status='PRODUCTION_LATENCY_E2E_PASS';save('registry',state);console.log(state.status);}

module.exports={benchmark,evidence,retrieveSource};if(require.main===module)benchmark().catch(e=>{save('safe-stop',{status:'STOPPED',safeError:e.name,category:/^[A-Za-z0-9 :_.()-]{1,180}$/.test(e.message)?e.message:'assertion details withheld'});console.error('SAFE STOP production E2E '+e.name+'; no automatic replay or additional mutation');process.exitCode=1});
