#!/usr/bin/env node
// No Auth creation or fixture writes. Live anonymous/pilot admission probes plus
// exact installed-source/live-env nonpilot domain gates; credentials never logged.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawnSync,execFileSync}=require('node:child_process');
const d=require('./deploy_production_visual_router.cjs'),op=require('./deploy_production_visual_latency.cjs'),c=require('./production_phase5a_common.cjs'),p=require('./production_recognition_review.cjs');
async function main(){assert.equal(op.load('execution').status,'ALL_POSTCHECK_PASS');const raw=await d.rawFunctions(),pilot=await d.pilotAuth(raw),checks=[];
 for(const name of p.CALLABLES){const f=raw.find(x=>x.name.endsWith('/'+name)),label=op.ORDER.includes(name)?'final':'before',zip=path.join(op.DIR,'sources',label+'-'+name+'.zip'),dir=path.join(op.DIR,'domain',name);
 const manifest=require('./deploy_production_phase3a.cjs').sourceManifest(zip);assert.deepEqual(manifest,op.ORDER.includes(name)?op.artifact(name).files:op.load('baseline-sources')[name].files);fs.mkdirSync(dir,{recursive:true,mode:0o700});
 execFileSync('python3',['-c','import zipfile,sys;zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])',zip,dir]);
 const code=`global.fetch=async()=>{throw Error('NETWORK_FORBIDDEN')};const assert=require('node:assert/strict'),api=require(require('node:path').resolve(require('./package.json').main));(async()=>{await assert.rejects(api[${JSON.stringify(name)}].run({auth:{uid:'SYNTHETIC_NONPILOT_DOMAIN_ONLY'},data:null}),e=>e.message==='AI_INPUT_NOT_ENABLED');console.log('PASS')})().catch(e=>{console.error(e.name);process.exit(1)});`;
 const result=spawnSync(process.execPath,['-e',code],{cwd:dir,env:{...process.env,NODE_PATH:path.join(c.ROOT,'functions/node_modules'),GCLOUD_PROJECT:c.P,FIREBASE_CONFIG:JSON.stringify({projectId:c.P,storageBucket:c.B}),...f.serviceConfig.environmentVariables},encoding:'utf8'});assert.equal(result.status,0,'Installed nonpilot domain gate '+name);checks.push({name,role:'nonpilot',kind:'installed-source/live-env/network-forbidden',code:'AI_INPUT_NOT_ENABLED'});
 for(const [role,token,expected]of [['anonymous',null,'UNAUTHENTICATED'],['pilot',pilot.token,'INVALID_REQUEST']]){const resp=await fetch(`https://${c.R}-${c.P}.cloudfunctions.net/${name}`,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({data:null}),signal:AbortSignal.timeout(45000)}),x=await resp.json();assert(!resp.ok);const code=x.error?.details?.code||x.error?.status;assert.equal(code,expected);checks.push({name,role,kind:'live',code,httpStatus:resp.status});}}
 op.save('auth-gates',{status:'PASS',checks,newAuthAccounts:0});console.log('PASS 18 live anonymous/pilot and 9 exact installed nonpilot domain checks; no data writes');}
if(require.main===module)main().catch(e=>{op.save('auth-gates-stop',{status:'STOPPED',safeError:e.name,category:/^[A-Za-z0-9 :_.()-]{1,180}$/.test(e.message)?e.message:'details withheld'});console.error('SAFE STOP gates '+e.name);process.exitCode=1});
