#!/usr/bin/env node
// Dev-only: add one database/index. No default Rules/index/data writes.
const {ROOT,PROJECT:P,NUMBER:N,BUCKET:B,REGION:R,guard,request}=require('./dev_cloud.cjs');
const {mkdirSync,writeFileSync,readFileSync}=require('node:fs');const {join}=require('node:path');const assert=require('node:assert/strict');
const DB='aogaku-ai',base=`https://firestore.googleapis.com/v1/projects/${P}/databases/`,out=join(ROOT,'build/named-firestore');mkdirSync(out,{recursive:true});
const save=(name,v)=>writeFileSync(join(out,name+'.json'),JSON.stringify(v,null,2),{mode:0o600});
async function snapshot(){return {indexes:await request(base+'(default)/collectionGroups/-/indexes'),fields:await request(base+'(default)/collectionGroups/-/fields?filter=indexConfig.usesAncestorConfig=false'),release:await request(`https://firebaserules.googleapis.com/v1/projects/${P}/releases/cloud.firestore`),storageRelease:await request(`https://firebaserules.googleapis.com/v1/projects/${P}/releases/firebase.storage/${B}`)};}
async function main(){guard();const project=await request(`https://cloudresourcemanager.googleapis.com/v1/projects/${P}`);assert.equal(project.projectId,P);assert.equal(project.projectNumber,N);const bucket=await request(`https://storage.googleapis.com/storage/v1/b/${B}`);assert.equal(bucket.name,B);
 const action=process.argv[2];assert(['provision','pause','resume','verify'].includes(action));
 const queue=`https://cloudtasks.googleapis.com/v2/projects/${P}/locations/${R}/queues/aiProcessSource`,jobs=await request(`https://cloudscheduler.googleapis.com/v1/projects/${P}/locations/${R}/jobs`);const scheduler=jobs.jobs.find(j=>j.name.endsWith('/firebase-schedule-aiReconcileInputs-'+R));assert(scheduler);
 if(action==='pause'||action==='resume'){const before=await request(queue);if(before.state!==(action==='pause'?'PAUSED':'RUNNING'))await request(queue+':'+action,'POST',{});if(scheduler.state!==(action==='pause'?'PAUSED':'ENABLED'))await request('https://cloudscheduler.googleapis.com/v1/'+scheduler.name+':'+action,'POST',{});console.log(JSON.stringify({project:P,queueState:(await request(queue)).state,schedulerState:(await request('https://cloudscheduler.googleapis.com/v1/'+scheduler.name)).state}));return;}
 if(action==='verify'){const before=JSON.parse(readFileSync(join(out,'default-before.json')));const after=await snapshot();save('default-after',after);assert.deepEqual(after,before,'default configuration changed');console.log('PASS: default Rules/Storage Rules/indexes/fieldOverrides unchanged');return;}
 const before=await snapshot();if(!require('node:fs').existsSync(join(out,'default-before.json')))save('default-before',before);
 let database;try{database=await request(base+DB);}catch(e){if(e.httpStatus!==404)throw e;const op=await request(base.slice(0,-1)+'?databaseId='+DB,'POST',{type:'FIRESTORE_NATIVE',locationId:R,deleteProtectionState:'DELETE_PROTECTION_ENABLED'});save('create-operation',op);database=await request(base+DB);}
 assert.equal(database.name,`projects/${P}/databases/${DB}`);assert.equal(database.locationId,R);assert.equal(database.type,'FIRESTORE_NATIVE');save('database',database);
 const url=base+DB+'/collectionGroups/aiSources/indexes';const current=await request(url);const specification=JSON.parse(readFileSync(join(ROOT,'Config/AI/firestore.indexes.json'))).indexes[0];assert((current.indexes||[]).length<=1,'unexpected named indexes');if(!(current.indexes||[]).length)save('index-operation',await request(url,'POST',{queryScope:specification.queryScope,fields:specification.fields}));
 for(let i=0;i<120;i++){const indexes=await request(base+DB+'/collectionGroups/-/indexes');save('indexes',indexes);if(indexes.indexes?.length===1&&indexes.indexes[0].state==='READY'){console.log(JSON.stringify({project:P,database:DB,location:database.locationId,indexState:'READY',defaultChanged:false}));return;}await new Promise(r=>setTimeout(r,5000));}throw Error('Named index not READY yet');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
