const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {validate}=require('./deploy_production_phase5a.cjs'),c=require('./production_phase5a_common.cjs');
const uid='SYNTHETIC_APPROVED_UID',pilot=[uid],name='aiCreateSource',before={name:c.parent+'/functions/'+name,serviceConfig:{service:c.parent+'/services/aicreatesource',environmentVariables:{AI_INPUT_ALLOWED_UIDS:'[]',AI_SHARING_ENABLED:'false',AI_FIRESTORE_DATABASE_ID:'aogaku-ai',OTHER:'preserve'}}};
const url=c.G+before.name+'?updateMask=serviceConfig.environmentVariables',body={name:before.name,serviceConfig:{environmentVariables:{...before.serviceConfig.environmentVariables,AI_INPUT_ALLOWED_UIDS:JSON.stringify(pilot)}}};
test('Only ten UID-gated Functions and an environment-only exact PATCH are allowed',()=>{validate(url,'PATCH',body,{action:'configure',name,before,pilot});for(const n of ['aiReconcileInputs','aiRejectLateUpload','askCourseAI','onAuthUserDelete'])assert.throws(()=>validate(c.G+c.parent+'/functions/'+n+'?updateMask=serviceConfig.environmentVariables','PATCH',body,{action:'configure',name:n,before,pilot}));assert.throws(()=>validate(url.replace('serviceConfig.environmentVariables','buildConfig.source'),'PATCH',body,{action:'configure',name,before,pilot}));});
test('Extra/wildcard UID, sharing, default DB and unrelated environment changes reject',()=>{for(const tweak of [x=>x.serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS='["SYNTHETIC_APPROVED_UID","other"]',x=>x.serviceConfig.environmentVariables.AI_SHARING_ENABLED='true',x=>x.serviceConfig.environmentVariables.AI_FIRESTORE_DATABASE_ID='(default)',x=>x.serviceConfig.environmentVariables.OTHER='changed']){const x=structuredClone(body);tweak(x);assert.throws(()=>validate(url,'PATCH',x,{action:'configure',name,before,pilot}));}assert.throws(()=>validate(url,'PATCH',body,{action:'configure',name,before,pilot:[uid,'other']}));assert.throws(()=>validate(url,'PATCH',body,{action:'configure',name,before,pilot:['*']}));});
test('Only nine actual Callable Run services gain precisely public HTTP invoker',()=>{const policy={etag:'live',bindings:[]},desired=c.p1.merge(policy,[{member:'allUsers',roles:['roles/run.invoker']}]),u='https://run.googleapis.com/v1/'+before.serviceConfig.service+':setIamPolicy';validate(u,'POST',{policy:desired},{action:'public',name,before,policy,pilot});for(const n of ['aiProcessSource','aiReconcileInputs','aiRejectLateUpload'])assert.throws(()=>validate(u,'POST',{policy:desired},{action:'public',name:n,before,policy,pilot}));assert.throws(()=>validate('https://cloudresourcemanager.googleapis.com/v1/projects/forta-aogaku:setIamPolicy','POST',{policy:desired},{action:'public',name,before,policy,pilot}));const extra=structuredClone(desired);extra.bindings.push({role:'roles/editor',members:['allUsers']});assert.throws(()=>validate(u,'POST',{policy:extra},{action:'public',name,before,policy,pilot}));});
test('Queue resume needs live gate pass; Scheduler, Secrets, Rules and deletion have no mutation path',()=>{const u='https://cloudtasks.googleapis.com/v2/'+c.Q+':resume';validate(u,'POST',{}, {action:'resume',pilot,gatesPassed:true});assert.throws(()=>validate(u,'POST',{}, {action:'resume',pilot,gatesPassed:false}));for(const u of ['https://cloudscheduler.googleapis.com/v1/'+c.parent+'/jobs/test:resume','https://secretmanager.googleapis.com/v1/projects/forta-aogaku/secrets/GROQ_API_KEY:addVersion',c.G+before.name])assert.throws(()=>validate(u,'POST',{}, {action:'resume',pilot,gatesPassed:true}));assert.throws(()=>validate(c.G+before.name,'DELETE',{}, {action:'configure',name,before,pilot}));});
test('No production source deploy or automatic mutation retries; gates use null data before IO',()=>{const s=fs.readFileSync(__dirname+'/deploy_production_phase5a.cjs','utf8');assert(!s.includes('generateUploadUrl'));assert(s.includes('mutation cannot be replayed'));assert(s.includes('JSON.stringify({data:null})'));assert(s.includes("'AI_INPUT_NOT_ENABLED'"));assert(s.includes('revisionGuard.assertRevision'));assert(s.includes('await installedSource(after)'));assert(s.includes('j.queueResumed=true'));});
