const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {notificationBoundary,protectedWithNotification,eventarcCore}=require('./audit_production_phase4_complete.cjs');
// Self-contained synthetic metadata; no production evidence/credentials needed.
function fixture(){
 const P='forta-aogaku',R='asia-northeast1',B=P+'.firebasestorage.app',SA='aogaku-ai-runtime@'+P+'.iam.gserviceaccount.com',parent=`projects/${P}/locations/${R}`,id='airejectlateupload-fixture',topic=`projects/${P}/topics/eventarc-us-central1-${id}-fixture`;
 const t={name:`projects/${P}/locations/us-central1/triggers/${id}`,serviceAccount:SA,labels:{'goog-managed-by':'cloudfunctions'},eventFilters:[{attribute:'type',value:'google.cloud.storage.object.v1.finalized'},{attribute:'bucket',value:B}],destination:{cloudFunction:parent+'/functions/aiRejectLateUpload'},transport:{pubsub:{topic}}};
 const f={name:parent+'/functions/aiRejectLateUpload',serviceConfig:{service:parent+'/services/airejectlateupload'},eventTrigger:{trigger:t.name,pubsubTopic:topic}};
 const n={items:[{id:`eventarc-${P}-us-central1-${id}`,topic:'//pubsub.googleapis.com/'+topic,payload_format:'JSON_API_V1',event_types:['OBJECT_FINALIZE']}]};
 const b={metadata:{bucket:{name:B,location:'US-CENTRAL1',metageneration:'3',lifecycle:{rule:[]},softDeletePolicy:{retentionDurationSeconds:'604800'}},rules:{firestore:{content:'EXISTING_RULES'}}},iam:{bucket:{version:1,etag:'CAM=',bindings:[{role:'roles/storage.objectViewer',members:['serviceAccount:'+SA]}]},aiProcessSource:{etag:'workerRun',bindings:[{role:'roles/run.invoker',members:['serviceAccount:'+SA]}]},aiProcessSourceFunctionIAM:{bindings:[{role:`projects/${P}/roles/aogakuAIFunctionMetadata`,members:['serviceAccount:'+SA]}]}},keys:{},secrets:{},functions:[{name:parent+'/functions/preDeleteCleanup',updateTime:'UNCHANGED'}],resources:{apis:[],serviceAccounts:[],queue:{data:{state:'PAUSED'}},scheduler:{data:{jobs:[]}},eventarc:{data:{triggers:[]}}}};
 const a=structuredClone(b);a.metadata.bucket.metageneration='4';a.iam.bucket.etag='CAQ=';a.functions.push({name:parent+'/functions/aiReconcileInputs'},f);a.resources.scheduler.data.jobs.push({name:require('./deploy_production_phase4_completion.cjs').JOB,state:'PAUSED'});a.resources.eventarc.data.triggers.push(t);return {b,a,f,t,n};
}
test('Eventarc filter ordering is immaterial; changed values still fail comparison',()=>{const x=fixture(),reverse=structuredClone(x.t);reverse.eventFilters.reverse();assert.deepEqual(eventarcCore(x.t),eventarcCore(reverse));reverse.eventFilters[0].value='wrong';assert.notDeepEqual(eventarcCore(x.t),eventarcCore(reverse));});
test('Exact approved Eventarc notification +1 metadata counter passes; raw baseline is untouched',()=>{const x=fixture(),original=JSON.stringify(x.b);const proof=protectedWithNotification(x.b,x.a,x.f,x.t,x.n);assert.equal(proof.classification,'APPROVED_EVENTARC_NOTIFICATION_SIDE_EFFECT');assert.equal(JSON.stringify(x.b),original);assert.equal(x.a.metadata.bucket.metageneration,'4');});
test('Lifecycle, soft delete and bucket region changes still reject',()=>{for(const k of ['lifecycle','softDeletePolicy','location']){const x=fixture();x.a.metadata.bucket[k]='CHANGED';assert.throws(()=>protectedWithNotification(x.b,x.a,x.f,x.t,x.n));}});
test('Only one exactly linked finalized notification is accepted',()=>{for(const mutate of [x=>x.n.items.push({...x.n.items[0]}),x=>x.n.items[0].topic='//pubsub.googleapis.com/projects/forta-aogaku/topics/unrelated',x=>x.n.items[0].event_types.push('OBJECT_DELETE'),x=>x.n.items[0].object_name_prefix='avatars/',x=>x.n.items[0].id='another-id',x=>x.a.metadata.bucket.metageneration='5']){const x=fixture();mutate(x);assert.throws(()=>notificationBoundary(x.b.metadata.bucket,x.a.metadata.bucket,x.f,x.t,x.n));}});
test('Wrong Eventarc destination, account, bucket and type still reject',()=>{for(const mutate of [x=>x.t.destination.cloudFunction=x.f.name.replace('aiRejectLateUpload','aiCreateSource'),x=>x.t.serviceAccount='unexpected@example.com',x=>x.t.eventFilters[0].value='wrong',x=>x.t.transport.pubsub.topic='projects/forta-aogaku/topics/unrelated']){const x=fixture();mutate(x);assert.throws(()=>notificationBoundary(x.b.metadata.bucket,x.a.metadata.bucket,x.f,x.t,x.n));}});
test('Approved notification never permits worker/legacy/Rules/IAM drift',()=>{for(const mutate of [x=>x.a.functions[0].updateTime='changed',x=>x.a.iam.aiProcessSource.etag='changed',x=>x.a.metadata.rules.firestore.content+='\n//changed',x=>x.a.resources.queue.data.state='RUNNING']){const x=fixture();mutate(x);assert.throws(()=>protectedWithNotification(x.b,x.a,x.f,x.t,x.n));}});
test('Bucket IAM validators do not permit any binding, condition, version or unexpected etag change',()=>{for(const mutate of [x=>x.a.iam.bucket.bindings[0].members.push('allUsers'),x=>x.a.iam.bucket.bindings[0].condition={expression:'true'},x=>x.a.iam.bucket.version=3,x=>x.a.iam.bucket.etag='OTHER']){const x=fixture();mutate(x);assert.throws(()=>protectedWithNotification(x.b,x.a,x.f,x.t,x.n));}});
test('Audit has no cloud mutation path and never rewrites failed journal/baseline',()=>{const s=fs.readFileSync(__dirname+'/audit_production_phase4_complete.cjs','utf8');assert(s.includes('reads.assertRead(url,method'));assert(!s.includes(':setIamPolicy'));assert(!s.includes(':generateUploadUrl'));assert(!s.includes("method:'PUT'"));assert(!s.includes("method:'PATCH'"));assert(s.includes("assert.deepEqual(fs.readFileSync(path.join(INPUT,'execution.json')),journalBytes)"));assert(s.includes("assert.deepEqual(fs.readFileSync(path.join(INPUT,'baseline.json')),baselineBytes)"));});
