const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const p=require('./production_recognition_review.cjs'),sha='a'.repeat(64);
const env={AI_FIRESTORE_DATABASE_ID:p.TARGET.databaseId,AI_SHARING_ENABLED:'false',AI_INPUT_ALLOWED_UIDS:JSON.stringify(['SYNTHETIC_PILOT_A','SYNTHETIC_PILOT_B'])};
function fn(n){return {name:`projects/${p.TARGET.projectId}/locations/${p.TARGET.region}/functions/${n}`,environment:'GEN_2',state:'ACTIVE',buildConfig:{runtime:'nodejs22',build:'old',source:{storageSource:{bucket:'old',object:'old',generation:'1'}},sourceProvenance:{resolvedStorageSource:{bucket:'old',object:'old',generation:'1'}},entryPoint:n},serviceConfig:{environmentVariables:{...env},serviceAccountEmail:p.TARGET.runtimeServiceAccount,revision:'old',ingressSettings:'ALLOW_ALL'},updateTime:'before'};}
const before=fn('aiProcessSource'),storage={bucket:'gcf-v2-uploads-505828754933-asia-northeast1',object:'fresh-object',generation:'2'};
const context={stagingUploaded:true,issuedStorageSourceHash:require('node:crypto').createHash('sha256').update(JSON.stringify(storage)).digest('hex'),approved:true,baselineAgeSeconds:0,queuePaused:true,inflightWorkers:0,schedulerPaused:true,phase5bAuthorized:false,identity:p.TARGET,liveFunctions:p.FUNCTIONS.map(fn),functions:p.FUNCTIONS,name:'aiProcessSource',before,freshStorageSource:storage,approvedSourceManifestSha256:sha,actualSourceManifestSha256:sha};
const url=`https://cloudfunctions.googleapis.com/v2/${before.name}?updateMask=buildConfig.source`,body={name:before.name,buildConfig:{source:{storageSource:storage}}};
test('Exact ten Functions only; capability list is published last; no Scheduler/Eventarc/legacy target',()=>{p.names(p.FUNCTIONS);assert.equal(p.ORDER[0],'aiProcessSource');assert.equal(p.ORDER.at(-1),'aiListSources');p.names(p.ORDER);for(const n of ['aiReconcileInputs','aiRejectLateUpload','aiLinkSourceOffering','onAuthUserDelete','askCourseAI'])assert.throws(()=>p.names([...p.FUNCTIONS.slice(1),n]));});
test('Live allowlist is preserved as exact raw value, supports multiple pilots, never stale one-UID phase5a config',()=>{const v=p.cohort(p.FUNCTIONS.map(fn));assert.equal(v.allowedUIDCount,2);assert.equal(v.environmentUpdateAuthorized,false);assert(!JSON.stringify(v).includes('SYNTHETIC'));const a=p.FUNCTIONS.map(fn);a[0].serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS='["SYNTHETIC_PILOT_A"]';assert.throws(()=>p.cohort(a));});
test('Wildcard/empty/general admission/sharing/default DB and wrong project/runtime fail before source update',()=>{for(const tweak of [x=>x.serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS='["*"]',x=>x.serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS='[]',x=>x.serviceConfig.environmentVariables.AI_INPUT_ADMISSION_MODE='public',x=>x.serviceConfig.environmentVariables.AI_SHARING_ENABLED='true',x=>x.serviceConfig.environmentVariables.AI_FIRESTORE_DATABASE_ID='(default)',x=>x.name=x.name.replace('forta-aogaku','forta-aogaku-dev'),x=>x.buildConfig.runtime='nodejs20']){const a=p.FUNCTIONS.map(fn);tweak(a[0]);assert.throws(()=>p.cohort(a));}});
test('Only fresh authorized source-only PATCH after queue drain is possible',()=>{p.validateSourcePatch(url,'PATCH',body,context);for(const t of [{approved:false},{baselineAgeSeconds:301},{queuePaused:false},{inflightWorkers:1},{schedulerPaused:false},{phase5bAuthorized:true},{actualSourceManifestSha256:'b'.repeat(64)}])assert.throws(()=>p.validateSourcePatch(url,'PATCH',body,{...context,...t}));});
test('No mutation for environment/IAM/Secrets/Rules/queue; no CREATE/DELETE or non-target update',()=>{for(const method of ['POST','PUT','DELETE'])assert.throws(()=>p.validateSourcePatch(url,method,body,context));for(const suffix of ['serviceConfig.environmentVariables','serviceConfig.serviceAccountEmail'])assert.throws(()=>p.validateSourcePatch(url.replace('buildConfig.source',suffix),'PATCH',body,context));assert.throws(()=>p.validateSourcePatch(url,'PATCH',{...body,serviceConfig:{environmentVariables:{AI_INPUT_ALLOWED_UIDS:'[]'}}},context));assert.throws(()=>p.validateSourcePatch(url.replace('aiProcessSource','askCourseAI'),'PATCH',body,context));});
test('SourceCodeGet manifest is mandatory; business env, IAM-facing ingress, runtime and Secret references stay exact',()=>{const after=structuredClone(before);after.state='ACTIVE';after.buildConfig.build='new';after.buildConfig.source={storageSource:storage};after.buildConfig.sourceProvenance={resolvedStorageSource:storage};after.updateTime='after';after.serviceConfig.revision='new';p.postCheck(before,after,{x:sha},{x:sha});assert.throws(()=>p.postCheck(before,after,{x:'b'.repeat(64)},{x:sha}));for(const t of [x=>x.serviceConfig.environmentVariables.AI_INPUT_ALLOWED_UIDS='[]',x=>x.serviceConfig.environmentVariables.AI_INPUT_REQUIRE_APP_CHECK='true',x=>x.serviceConfig.serviceAccountEmail='other',x=>x.serviceConfig.ingressSettings='ALLOW_INTERNAL_ONLY',x=>x.serviceConfig.secretEnvironmentVariables=[{key:'GROQ_API_KEY',version:'2'}],x=>x.buildConfig.runtime='nodejs20']){const a=structuredClone(after);t(a);assert.throws(()=>p.postCheck(before,a,{x:sha},{x:sha}));}});
test('Review artifact has exactly ten entrypoints, no private env/config, no automatic cloud/deploy execution',()=>{const review=JSON.parse(fs.readFileSync(path.join(p.DIR,'review.json')));assert.equal(review.productionDeploymentAuthorized,false);assert.equal(review.livePreflightCompleted,false);p.names(review.functions);const files=p.inventory(p.PACKAGE);assert.deepEqual(files,review.files);assert(!Object.keys(files).some(x=>/\.env|GoogleService|fixture|credentials|node_modules|\.local/.test(x)));const s=fs.readFileSync(__dirname+'/production_recognition_review.cjs','utf8');assert(!s.includes('generateUploadUrl'));assert(!s.includes('https://oauth2.'));assert(!s.includes('firebase deploy'));assert(s.includes("['prepare']"));});
function child(code,extra={}){return spawnSync(process.execPath,['-e',code],{cwd:p.PACKAGE,env:{...process.env,NODE_PATH:path.resolve(__dirname,'../functions/node_modules'),GCLOUD_PROJECT:p.TARGET.projectId,FIREBASE_CONFIG:JSON.stringify({projectId:p.TARGET.projectId,storageBucket:p.TARGET.bucket}),AI_RUNTIME_SERVICE_ACCOUNT:p.TARGET.runtimeServiceAccount,...env,AI_INPUT_ADMISSION_MODE:'pilot',AI_INPUT_REQUIRE_APP_CHECK:'false',...extra},encoding:'utf8'});}
test('Exact packaged nine Callables deny anonymous/outsider; BOTH synthetic allowed pilots pass admission, before any I/O',()=>{const r=child(`global.fetch=async()=>{throw Error('NETWORK_FORBIDDEN')};const assert=require('node:assert/strict'),api=require('./lib/recognition-production');(async()=>{for(const n of ${JSON.stringify(p.CALLABLES)}){await assert.rejects(api[n].run({data:null}),e=>e.code==='unauthenticated');await assert.rejects(api[n].run({auth:{uid:'SYNTHETIC_OUTSIDER'},data:null}),e=>e.message==='AI_INPUT_NOT_ENABLED');for(const uid of ['SYNTHETIC_PILOT_A','SYNTHETIC_PILOT_B'])await assert.rejects(api[n].run({auth:{uid},data:null}),e=>e.message==='INVALID_REQUEST');}assert.equal(api.aiReconcileInputs,undefined);assert.equal(api.aiRejectLateUpload,undefined);console.log('27+9 admission checks PASS')})().catch(e=>{console.error(e.name);process.exit(1)});`);assert.equal(r.status,0,r.stderr);assert(r.stdout.includes('admission checks PASS'));});
test('Exact packaged named database accepts absent/fixed only, never implicit default fallback',()=>{for(const [raw,ok]of [['UNDEFINED',true],['aogaku-ai',true],['',false],['(default)',false],['other',false]]){const r=child(`if(${JSON.stringify(raw)}==='UNDEFINED')delete process.env.AI_FIRESTORE_DATABASE_ID;try{console.log(require('./lib/ai/databases').aiDatabaseId())}catch(e){console.error(e.code);process.exit(1)}`,{AI_FIRESTORE_DATABASE_ID:raw});assert.equal(r.status,ok?0:1,r.stderr);assert.equal((ok?r.stdout:r.stderr).trim(),ok?'aogaku-ai':'AI_DATABASE_MISMATCH');}});
test('Exact packaged provider/pricing is Qwen AI-only and Turbo audio time; OCR remains PDF-only',()=>{const r=child(`const assert=require('node:assert/strict'),fs=require('node:fs'),p=require('./lib/ai/pricing'),x=fs.readFileSync('./lib/ai/extractors.js','utf8');assert.equal(p.IMAGE_PIPELINE.model,'qwen/qwen3.8-27b');assert.equal(p.IMAGE_PIPELINE.fallback,false);assert.equal(p.audioUsage(180,180,1).estimatedCostUSD,.002);assert.equal(p.audioUsage(180,180,1).inputTokens,null);assert.equal(p.RECOGNITION_PRICING.audio.model,'whisper-large-v3-turbo');assert(!x.includes('documentTextDetection'));assert(x.includes('batchAnnotateFiles'));console.log('PASS');`);assert.equal(r.status,0,r.stderr);});

test('Production target number, bucket, Release bundle and named DB are mandatory even for source-only changes',()=>{p.validateIdentity(p.TARGET);for(const [key,value]of [['projectId','forta-aogaku-dev'],['projectNumber','1064661805206'],['bucket','forta-aogaku-dev.firebasestorage.app'],['bundleId','com.forta2k25.Aogaku.dev'],['databaseId','(default)'],['region','us-central1']]){const identity={...p.TARGET,[key]:value};assert.throws(()=>p.validateSourcePatch(url,'PATCH',body,{...context,identity}));}});

test('Gen2 issued staging storageSource may omit generation; other project/bad path/unuploaded objects reject',()=>{const storage={bucket:'gcf-v2-uploads-505828754933-asia-northeast1',object:'fresh.zip'};const c={...context,freshStorageSource:storage,issuedStorageSourceHash:require('node:crypto').createHash('sha256').update(JSON.stringify(storage)).digest('hex')};const b={name:before.name,buildConfig:{source:{storageSource:storage}}};p.validateSourcePatch(url,'PATCH',b,c);for(const change of [{bucket:'gcf-v2-uploads-1064661805206-asia-northeast1'},{object:'../wrong'},{generation:'invalid'}]){const s={...storage,...change};assert.throws(()=>p.validateSourcePatch(url,'PATCH',{name:before.name,buildConfig:{source:{storageSource:s}}},{...c,freshStorageSource:s,issuedStorageSourceHash:require('node:crypto').createHash('sha256').update(JSON.stringify(s)).digest('hex')}));}assert.throws(()=>p.validateSourcePatch(url,'PATCH',b,{...c,stagingUploaded:false}));});
test('Current modules match their fresh review; archived AI-only approval cannot authorize Router',()=>{
 const routed=fs.readFileSync(path.join(__dirname,'../functions/src/ai/index.ts'),'utf8').includes('schemaVersion: 5');
 let packageDir=p.PACKAGE;
 if(routed){const next=require('./production_visual_router_review.cjs');next.contract();assert.throws(()=>p.verifyContract());packageDir=path.join(next.DIR,'package');}
 const files=p.inventory(packageDir);for(const [file,expected]of Object.entries(files)){if(!file.startsWith('lib/ai/'))continue;assert.equal(require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../functions',file))).digest('hex'),expected);}
});
