#!/usr/bin/env node
// Read-only stop audit; never resumes a partial deployment or creates Auth fixtures.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..'),DIR=path.join(ROOT,'build/production-phase4-final'),P='forta-aogaku',R='asia-northeast1',G2='https://cloudfunctions.googleapis.com/v2/',G1='https://cloudfunctions.googleapis.com/v1/';
const {hash,sourceManifest}=require('./deploy_production_phase3a.cjs'),phase=require('./deploy_production_phase4_final.cjs');
const load=n=>JSON.parse(fs.readFileSync(path.join(DIR,n+'.json'))),save=(n,x)=>{const p=path.join(DIR,n+'.json');fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n',{mode:0o600});fs.chmodSync(p,0o600);};
async function main(){
 const j=load('execution'),a=load('artifact'),s=load('audit-before'),old=load('legacy-sources');assert.equal(j.status,'STOPPED');assert.equal(j.attempts.length,0);assert.deepEqual(j.created,[]);assert.equal(load('stop-audit').status,'PROTECTED_STATE_UNCHANGED');
 const lib='/Users/shum/anaconda3/lib/node_modules/firebase-tools/lib',account=require(lib+'/auth.js').getGlobalDefaultAccount(),api=require(lib+'/api.js');const refresh=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:api.clientId(),client_secret:api.clientSecret(),refresh_token:account.tokens.refresh_token,grant_type:'refresh_token'}),signal:AbortSignal.timeout(45000)});const t=await refresh.json();assert(refresh.ok&&t.access_token);const token=t.access_token;
 const aiPresent=[...phase.EXISTING_TEN,...j.created],names=[...Object.keys(old),...j.created],reads=new Set(['https://cloudresourcemanager.googleapis.com/v1/projects/'+P,...names.flatMap(n=>[G1+`projects/${P}/locations/${R}/functions/${n}`,G2+`projects/${P}/locations/${R}/functions/${n}`]),...aiPresent.flatMap(n=>{const f=s.functions.find(f=>f.name.endsWith('/'+n));return ['https://run.googleapis.com/v1/'+f.serviceConfig.service+':getIamPolicy','https://run.googleapis.com/v1/'+f.serviceConfig.service];}),G2+`projects/${P}/locations/${R}/functions/aiProcessSource:getIamPolicy?options.requestedPolicyVersion=3`]);
 async function request(url,method='GET',body){if(method==='GET')assert(reads.has(url));else {assert.equal(method,'POST');assert(names.some(n=>url===(s.functions.find(f=>f.name.endsWith('/'+n)).environment==='GEN_1'?G1:G2)+`projects/${P}/locations/${R}/functions/${n}:generateDownloadUrl`));}const r=await fetch(url,{method,redirect:'error',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(45000)});assert(r.ok,'Read-only audit HTTP '+r.status+' '+method+' '+new URL(url).hostname+new URL(url).pathname);return r.json();}
 const identity=await request('https://cloudresourcemanager.googleapis.com/v1/projects/'+P);assert.equal(identity.projectId,P);assert.equal(identity.projectNumber,'505828754933');
 const proof={status:'STARTED',phase:'4',cloudWrites:0,sourceSha256:a.sourceSha256,created:j.created,aiPresent,legacySourcesUnchanged:false,protectedStateUnchanged:true,functions:{},anonymousProbes:[],validProductionAndDevTokenProbes:'No valid user tokens acquired; IAM boundary structurally verified and anonymous probes executed; no Auth fixture created',queueState:'PAUSED',schedulerCreated:false,eventarcCreated:false,additionalIAMBindings:0,phase4Complete:false,phase5Authorized:false};save('stop-source-and-closed',proof);
 for(const n of names){const resource=`projects/${P}/locations/${R}/functions/${n}`,v2=await request(G2+resource);assert.equal(v2.updateTime,s.functions.find(f=>f.name===resource).updateTime,'STOP: metadata changed since read-only stop audit');const v1=v2.environment==='GEN_1',meta=v1?await request(G1+resource):v2,download=await request((v1?G1:G2)+resource+':generateDownloadUrl','POST',v1?{versionId:meta.versionId}:{}),u=new URL(download.downloadUrl);assert.equal(u.protocol,'https:');assert(u.hostname==='storage.googleapis.com'||u.hostname.endsWith('.storage.googleapis.com'));assert(!u.username&&!u.password&&!u.port);const r=await fetch(u,{redirect:'error',signal:AbortSignal.timeout(45000)});assert(r.ok);const bytes=Buffer.from(await r.arrayBuffer());assert(bytes.length<=100*1024*1024);const zip=path.join(DIR,n+'-stop-source.zip');fs.writeFileSync(zip,bytes,{mode:0o600});fs.chmodSync(zip,0o600);const files=sourceManifest(zip),expected=j.created.includes(n)?a.files:old[n].files;assert.deepEqual(files,expected,'STOP: actual source drift '+n);assert.equal((await request(G2+resource)).updateTime,v2.updateTime);
  if(aiPresent.includes(n)){
   const sc=v2.serviceConfig;assert.equal(v2.state,'ACTIVE');assert.equal(v2.buildConfig.runtime,'nodejs22');assert.equal(sc.serviceAccountEmail,phase.env().AI_RUNTIME_SERVICE_ACCOUNT);assert.equal(sc.environmentVariables.AI_FIRESTORE_DATABASE_ID,'aogaku-ai');assert.equal(sc.environmentVariables.AI_INPUT_ALLOWED_UIDS,'[]');assert.equal(sc.environmentVariables.AI_SHARING_ENABLED,'false');const run=await request('https://run.googleapis.com/v1/'+sc.service);assert(run.metadata?.annotations?.['run.googleapis.com/invoker-iam-disabled']!=='true');const policy=await request('https://run.googleapis.com/v1/'+sc.service+':getIamPolicy');if(n==='aiProcessSource'){assert((policy.bindings||[]).some(b=>b.role==='roles/run.invoker'&&b.members.includes('serviceAccount:'+phase.env().AI_RUNTIME_SERVICE_ACCOUNT)));const functionIAM=await request(G2+resource+':getIamPolicy?options.requestedPolicyVersion=3');proof.workerIAM={runResource:sc.service,runInvokerRuntimeSA:true,functionMetadataBindingPresent:(functionIAM.bindings||[]).some(b=>b.role==='projects/'+P+'/roles/aogakuAIFunctionMetadata'&&b.members.includes('serviceAccount:'+phase.env().AI_RUNTIME_SERVICE_ACCOUNT)),runPolicy:policy,functionPolicy:functionIAM};}assert(!(policy.bindings||[]).some(b=>b.members.some(m=>['allUsers','allAuthenticatedUsers'].includes(m))));
   proof.functions[n]={state:'ACTIVE',runtime:'nodejs22',region:R,trigger:n==='aiProcessSource'?'TaskQueue HTTPS':'Callable HTTPS',sourceSha256:hash(files),serviceAccount:sc.serviceAccountEmail,allowedUIDs:[],sharingEnabled:false,databaseId:'aogaku-ai',publicInvoker:false,updateTime:v2.updateTime};
   for(const endpoint of [sc.uri,`https://${R}-${P}.cloudfunctions.net/${n}`]){const response=await fetch(endpoint,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:{}}),signal:AbortSignal.timeout(45000)});assert([401,403].includes(response.status),'STOP: anonymous admission unexpected HTTP '+response.status);proof.anonymousProbes.push({function:n,endpointType:endpoint===sc.uri?'Cloud Run':'cloudfunctions.net',httpStatus:response.status,denied:true});}
  }else proof.functions[n]={sourceSha256:hash(files),updateTime:v2.updateTime,unchanged:true};
  save('stop-source-and-closed',proof);console.log(n+': stopped-state installed full source '+(aiPresent.includes(n)?'/ empty cohort / private IAM / anonymous denied':'unchanged')+' PASS');
 }
 proof.status='PASS_STOPPED_SAFE';proof.legacySourcesUnchanged=true;proof.remainingFunctions=phase.NAMES.filter(n=>!j.created.includes(n));proof.phase4Blockers=['Read timeout during pre-mutation worker metadata/IAM snapshot; no mutation attempted','aiProcessSource Function-scoped metadata binding and individual post-check incomplete','aiReconcileInputs and paused Scheduler not created','aiRejectLateUpload and Storage/Eventarc not created','All-twelve final control-plane/rejection audit incomplete'];save('stop-source-and-closed',proof);console.log('Read-only stopped-state audit PASS: 10 AI private closed + 13 legacy sources unchanged; deployment remains STOPPED');
}
if(require.main===module)main().catch(e=>{console.error(e.message);process.exitCode=1});
