#!/usr/bin/env node
// Offline metrics projection only. Never copy UID, Auth, URLs or provider/Evidence bodies to docs.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),DIR=path.join(ROOT,'build/visual-latency/dev');
const read=n=>JSON.parse(fs.readFileSync(path.join(DIR,n+'.json')));
const sec=x=>x===null||x===undefined?'unknown':(x/1000).toFixed(3);
const gain=(b,a)=>b?((b-a)/b*100).toFixed(1)+'%':'—';
function report(){const before=read('before-results'),after=read('after-results');assert.equal(before.length,13);assert.equal(after.length,13);
 const rows=before.map(b=>{const a=after.find(x=>x.key===b.key);assert(a);assert.equal(a.fixtureSHA,b.fixtureSHA);assert.deepEqual(a.routes,b.routes);assert.deepEqual(a.pages.map(p=>[p.pageNumber,p.textSHA,p.locator]),b.pages.map(p=>[p.pageNumber,p.textSHA,p.locator]),'Final selected Evidence changed: '+b.key);return {before:b,after:a}});
 let out='## Measured before / after\n\nWorker = successful attempt; Ready = source creation → ready; First = first preview write, or ready for images. Times are seconds. N=1; 429/retry differences are shown separately.\n\n';
 out+='| Fixture | Worker before → after | Reduction | Ready before → after | First before → after | Attempts before → after |\n|---|---:|---:|---:|---:|---:|\n';
 for(const {before:b,after:a}of rows)out+=`| ${b.key} | ${sec(b.latency.totalProcessingMs)} → ${sec(a.latency.totalProcessingMs)} | ${gain(b.latency.totalProcessingMs,a.latency.totalProcessingMs)} | ${sec(b.serverReadyMs)} → ${sec(a.serverReadyMs)} | ${sec(b.firstServerUsefulMs)} → ${sec(a.firstServerUsefulMs)} | ${b.attempts} → ${a.attempts} |\n`;
 out+='\nAll 13 route arrays, selected Unit/chunk/Evidence/retrieval bodies and locators matched exactly between the real Dev runs. This fixture result does not prove accuracy for every real document.\n\n';
 const stages=['uploadMs','queueWaitMs','workerStartupMs','routerMs','nativeExtractionMs','ocrProbeMs','ocrMs','aiMs','persistenceMs'];out+='### Stage times (seconds, before → after)\n\n| Fixture | '+stages.join(' | ')+' |\n|---|'+stages.map(()=>'---:').join('|')+'|\n';
 for(const {before:b,after:a}of rows)out+=`| ${b.key} | `+stages.map(k=>`${sec(b.latency[k])} → ${sec(a.latency[k])}`).join(' | ')+' |\n';
 out+='\nUpload timing kinds differ: before uses the server creation window; after uses measured client transfer. These values are labeled metadata, not like-for-like speed comparisons. Cached provider results can make a last-attempt stage zero even though the source has billed usage. Provider sums under concurrency are not wall time.\n\n';
 out+='### Usage, costs, operations and bytes\n\n| Fixture | Tokens before → after | Estimated USD before → after | Logical completed operations before → after | Calls in successful attempt before → after | Upload bytes | Probe skips after |\n|---|---:|---:|---:|---:|---:|---:|\n';
 let bCost=0,aCost=0,imageB=0,imageA=0,bCalls=0,aCalls=0,skips=0,bTokens=0,aTokens=0;
 for(const {before:b,after:a}of rows){const rb=read('before-'+b.key+'-full').source.recognition.routing,ra=read('after-'+a.key+'-full').source.recognition.routing,bc=rb.ocrUnits+rb.counts.multimodal_ai,ac=ra.ocrUnits+ra.counts.multimodal_ai;bCost+=b.costUSD;aCost+=a.costUSD;bTokens+=b.tokens;aTokens+=a.tokens;if(b.type==='image'){imageB+=b.costUSD;imageA+=a.costUSD;bCalls+=bc;aCalls+=ac;skips+=a.ocrProbeSkipped;}assert.equal(b.uploadBytes,a.uploadBytes);out+=`| ${b.key} | ${b.tokens} → ${a.tokens} | $${b.costUSD.toFixed(7)} → $${a.costUSD.toFixed(7)} | ${bc} → ${ac} | ${b.latency.providerCalls} → ${a.latency.providerCalls} | ${a.uploadBytes} | ${a.ocrProbeSkipped} |\n`;}
 out+=`\nImage OCR probes skipped: **${skips}/8** (two-label, six-label, nodes). Logical image provider operations: **${bCalls} → ${aCalls}**, excluding failures/verification HTTP reads. Image provider estimate: **$${imageB.toFixed(7)} → $${imageA.toFixed(7)} (${gain(imageB,imageA)})**. All 13 cases: ${bTokens} → ${aTokens} tokens, **$${bCost.toFixed(7)} → $${aCost.toFixed(7)}**. No pricing-table change; excluded platform costs/free tiers are described above.\n\n`;
 out+='### Evidence read and first-result observation\n\n| Fixture | Client paginated Evidence read before → after | PDF previews observed in after polling |\n|---|---:|---:|\n';for(const {before:b,after:a}of rows)out+=`| ${b.key} | ${sec(b.evidenceMs)} → ${sec(a.evidenceMs)} | ${a.observedPreviews} |\n`;
 out+='\nClient preview observations can be zero when a previously finished source is resumed; Firestore preview creation timestamps retain the actual first-result time. Processing-only preview exclusion and final publication races are tested independently. This is backend/client-script observation, **not a physical iPhone perceived-latency measurement**.\n\n';
 if(fs.existsSync(path.join(DIR,'resize-results.json'))){const sizes=read('resize-results'),prep=read('resize-preparation');assert.equal(sizes.length,4);out+='## Same-image resize experiment\n\nAll four original/2000/1600/1200px sources were sent through the Dev worker, with one-minute task schedule spacing. Each exhausted its existing four attempts with `IMAGE_AI_RATE_LIMIT` (HTTP 429). No active version/recognition was published and no OCR fallback occurred. The exact quota dimension cannot be established from the safe public error code; no Secret/provider payload was inspected.\n\n| Provider max side | Locally prepared PNG bytes | Raw upload bytes | Attempts | Result | Usage / AI time / quality |\n|---:|---:|---:|---:|---|---|\n';for(const r of sizes){const p=prep.find(x=>x.side===r.maxSide);out+=`| ${r.maxSide} | ${p.preparedImageBytes} | ${p.rawUploadBytes} | ${r.attempts} | ${r.status} | unavailable |\n`;}out+='\nPrepared bytes are local payload-preparation measurements, not evidence that Groq accepted/billed the request. Actual usage, cost, AI completion latency, relationship accuracy and fine-text retention **cannot be compared** for these blocked requests. No extra billed replay, quota change, model change or key rotation was performed.\n\n**Decision: retain the existing 1800px provider maximum.** Resize optimization remains unverified and is not proposed for production. Repeat this four-size quality experiment separately after rate limits recover, before considering a new bound.\n\n';}

 return out;
}
module.exports={report};if(require.main===module){const text=report();const file=path.join(ROOT,'docs/ai-input/visual-latency.md'),existing=fs.readFileSync(file,'utf8'),marker='## Pending measurement summary';assert(existing.includes(marker)||existing.includes('## Measured before / after'));const suffix=existing.includes('## Regression, limitations and final state')?'## Regression, limitations and final state'+existing.split('## Regression, limitations and final state')[1]:'';fs.writeFileSync(file,existing.split(marker)[0].split('## Measured before / after')[0]+text+suffix);console.log('PASS offline privacy-safe metric tables and exact Evidence comparison, 13/13');}
