#!/usr/bin/env node
// Dev-only task-input experiment, no Secret payloads/local provider keys.
// Own synthetic fixtures; resume only after the reviewed worker state is verified.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const c=require('./dev_cloud.cjs'),v=require('./visual_router_dev.cjs'),op=require('./visual_latency_dev.cjs'),b=require('./visual_latency_benchmark.cjs');
const P=c.PROJECT,R=c.REGION,D='aogaku-ai',Q=`https://cloudtasks.googleapis.com/v2/projects/${P}/locations/${R}/queues/aiProcessSource`,sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function run(){const state=op.load('registry'),expected=op.load('after-complete'),before=await v.snapshot();v.protectedCheck(expected,before);assert.deepEqual(expected.functions,before.functions);assert.equal(before.queue.state,'RUNNING');assert(!fs.existsSync(path.join(op.OUT,'resize-attempt.json')),'Never replay billed resize fixtures');op.save('resize-attempt',{status:'PAUSE_ATTEMPTED'});await c.request(Q+':pause','POST',{});assert.equal((await v.read(Q)).state,'PAUSED');assert(!(await v.read(Q+'/tasks')).tasks?.length);await sleep(10000);
 const file=require('./visual_latency_fixtures.cjs').resizeFixture(path.join(op.OUT,'fixtures')),bytes=fs.readFileSync(file),worker=before.functions.functions.find(x=>x.name.endsWith('/aiProcessSource'));
 const sources=[];for(const [i,side]of [4032,2000,1600,1200].entries()){const row={mode:'resize',key:'resize-'+side,status:'CREATE_ATTEMPTED',providerMaxSide:side,fixtureSHA:crypto.createHash('sha256').update(bytes).digest('hex')};state.sources.push(row);op.save('registry',state);
  const created=(await b.call(state,'aiCreateSource',{clientRequestId:state.run+'-'+row.key,type:'image',title:'Synthetic image resize '+side,mime:'image/png',size:bytes.length,context:{...state.context,dayID:state.context.dayID+50+i}})).value;row.sourceId=created.sourceId;op.save('registry',state);const u=new URL(created.upload.url);assert.equal(u.hostname,'storage.googleapis.com');assert(u.pathname.startsWith('/'+c.BUCKET+'/'));assert.equal((await fetch(u,{method:'PUT',headers:created.upload.headers,body:bytes})).status,200);await b.call(state,'aiCompleteSource',{sourceId:row.sourceId});
  const jobs=await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${row.sourceId}/jobs`);assert.equal(jobs.documents.length,1);const originalId=jobs.documents[0].name.split('/').pop();await c.request(Q+'/tasks/'+originalId,'DELETE');
  const taskId=crypto.createHash('sha256').update(state.run+'-'+row.key).digest('hex'),payload={data:{sourceId:row.sourceId,taskId,databaseId:D,benchmarkProviderMaxSide:side}};
  await c.request(Q+'/tasks','POST',{task:{name:Q.slice('https://cloudtasks.googleapis.com/v2/'.length)+'/tasks/'+taskId,scheduleTime:new Date(Date.now()+60000*(i+1)).toISOString(),httpRequest:{httpMethod:'POST',url:worker.serviceConfig.uri,headers:{'Content-Type':'application/json'},body:Buffer.from(JSON.stringify(payload)).toString('base64'),oidcToken:{serviceAccountEmail:worker.serviceConfig.serviceAccountEmail,audience:worker.serviceConfig.uri}}}});row.taskId=taskId;op.save('registry',state);sources.push(row);
 }
 const queued=await v.read(Q+'/tasks?pageSize=100');assert.equal(queued.tasks.length,4);const guarded=await v.snapshot();v.protectedCheck(before,guarded);assert.deepEqual(before.functions,guarded.functions);assert.equal(guarded.queue.state,'PAUSED');op.save('resize-attempt',{status:'RESUME_ATTEMPTED'});await c.request(Q+':resume','POST',{});assert.equal((await v.read(Q)).state,'RUNNING');
 const results=[];for(const row of sources){let ready;for(let i=0;i<180;i++){ready=(await b.call(state,'aiGetSource',{sourceId:row.sourceId})).value;if(ready.status==='ready')break;assert(!['failed','partial_ready'].includes(ready.status),'Resize processing '+ready.error?.code);await sleep(2000);}assert.equal(ready.status,'ready');const evidence=await b.evidence(state,row.sourceId);const text=require('./evidence_adoption_dev.cjs').joinChunks(evidence.items),page=ready.recognition.routing.pages[0];assert.equal(page.route,'multimodal_ai');assert.equal(page.provider,'groq');assert.equal(page.model,'qwen/qwen3.8-27b');
  const quality={prominentLabels:['Synthetic Observation','Synthetic Question'].every(label=>text.includes(label)),fineFragments:['72A','19','3.14'].map(label=>({label,retained:text.includes(label)})),relation:/矢印|接続|→|arrow|connect/i.test(text)};const result={maxSide:row.providerMaxSide,sourceId:row.sourceId,providerBytes:ready.latency.providerBytes,aiMs:ready.latency.aiMs,tokens:ready.recognition.totalTokens,costUSD:ready.recognition.estimatedCostUSD,quality,text,recognition:ready.recognition};results.push(result);row.status='PASS';op.save('registry',state);console.log(JSON.stringify({side:row.providerMaxSide,bytes:result.providerBytes,aiMs:Math.round(result.aiMs),tokens:result.tokens,costUSD:result.costUSD,quality}));
 }
 const after=await v.snapshot();v.protectedCheck(before,after);assert.deepEqual(before.functions,after.functions);assert.equal(after.queue.state,'RUNNING');op.save('resize-results',results);op.save('resize-attempt',{status:'PASS'});console.log('DEV_RESIZE_MEASURED; default 1800px unchanged pending quality review');}
// A stopped rate-limit experiment may only observe existing sources; no task/source replay.
async function observe(){const state=op.load('registry'),expected=op.load('after-complete');assert.equal(state.projectId,P);assert(['RESUME_ATTEMPTED','PASS'].includes(op.load('resize-attempt').status));const rows=state.sources.filter(x=>x.mode==='resize');assert.equal(rows.length,4);assert.equal(new Set(rows.map(x=>x.fixtureSHA)).size,1);const results=[];
 for(const row of rows){let ready;for(let i=0;i<180;i++){ready=(await b.call(state,'aiGetSource',{sourceId:row.sourceId})).value;if(['ready','failed'].includes(ready.status))break;await sleep(2000);}const raw=await v.read(`https://firestore.googleapis.com/v1/projects/${P}/databases/${D}/documents/aiSources/${row.sourceId}`);assert.equal(raw.fields.ownerUserId.stringValue,state.user.uid);assert.equal(raw.fields.sourceType.stringValue,'image');assert.equal(ready.pipelineVersion,'image-auto-v1');
  let result;if(ready.status==='failed'){assert.equal(ready.error?.code,'IMAGE_AI_RATE_LIMIT');assert.equal(ready.error.retryable,true);assert(!ready.activeVersion);assert(!ready.recognition,'Failed AI must not silently publish OCR');row.status='FAILED_RATE_LIMIT';result={maxSide:row.providerMaxSide,status:row.status,errorCode:ready.error.code,attempts:Number(raw.fields.attempts.integerValue),providerBytes:null,aiMs:null,tokens:null,costUSD:null,quality:null};}
  else{assert.equal(ready.status,'ready');const e=await b.evidence(state,row.sourceId),text=require('./evidence_adoption_dev.cjs').joinChunks(e.items),page=ready.recognition.routing.pages[0];assert.equal(page.route,'multimodal_ai');assert.equal(page.provider,'groq');assert.equal(page.model,'qwen/qwen3.8-27b');row.status='PASS';result={maxSide:row.providerMaxSide,status:'PASS',providerBytes:ready.latency.providerBytes,aiMs:ready.latency.aiMs,tokens:ready.recognition.totalTokens,costUSD:ready.recognition.estimatedCostUSD,quality:{prominentLabels:['Synthetic Observation','Synthetic Question'].every(label=>text.includes(label)),fineFragments:['72A','19','3.14'].map(label=>({label,retained:text.includes(label)})),relation:/矢印|接続|→|arrow|connect/i.test(text)}};}
  results.push(result);op.save('registry',state);console.log(JSON.stringify(result));
 }
 const after=await v.snapshot();v.protectedCheck(expected,after);assert.deepEqual(expected.functions,after.functions);assert.equal(after.queue.state,'RUNNING');assert(!(await v.read(Q+'/tasks')).tasks?.length);op.save('resize-results',results);op.save('resize-observed-final',after);console.log('DEV_RESIZE_OBSERVED_NO_REPLAY; rate limits do not authorize a size change');}
if(require.main===module)(process.argv[2]==='observe'?observe():run()).catch(e=>{console.error('SAFE STOP Dev resize '+e.name+' '+String(e.message).slice(0,180));process.exitCode=1});module.exports={run};
