#!/usr/bin/env node
// Resume only this experiment's deleted synthetic Dev Auth owner; never invoke a global sweep.
const assert=require('node:assert/strict'),fs=require('node:fs');
const c=require('./dev_cloud.cjs'),v=require('./visual_router_dev.cjs'),op=require('./visual_latency_dev.cjs');
async function main(){c.guard();const state=op.load('registry');assert.equal(state.projectId,c.PROJECT);assert(fs.existsSync(op.OUT+'/cleanup-attempt.json'));assert(!state.user.idToken&&!state.user.refreshToken);assert.equal(state.sources.length,30);assert(state.sources.every(x=>x.status==='PASS'||(x.mode==='resize'&&x.status==='FAILED_RATE_LIMIT')));
 process.env.GCLOUD_PROJECT=c.PROJECT;process.env.GOOGLE_CLOUD_PROJECT=c.PROJECT;process.env.AI_FIRESTORE_DATABASE_ID='aogaku-ai';assert(!process.env.FIRESTORE_EMULATOR_HOST&&!process.env.FIREBASE_AUTH_EMULATOR_HOST&&!process.env.FIREBASE_STORAGE_EMULATOR_HOST);
 const path=require('node:path'),lib=process.env.FIREBASE_TOOLS_LIB;assert(lib,'Explicit existing Firebase CLI runtime required');const account=require(path.join(lib,'auth.js')).getGlobalDefaultAccount(),api=require(path.join(lib,'api.js'));assert(account?.tokens?.refresh_token);const credentialFile=path.join(op.OUT,'cleanup-oauth-temporary.json');assert(!fs.existsSync(credentialFile),'Do not overwrite a retained credential');fs.writeFileSync(credentialFile,JSON.stringify({type:'authorized_user',client_id:api.clientId(),client_secret:api.clientSecret(),refresh_token:account.tokens.refresh_token}),{mode:0o600});process.env.GOOGLE_APPLICATION_CREDENTIALS=credentialFile;
 const admin=require('../functions/node_modules/firebase-admin');try{admin.initializeApp({projectId:c.PROJECT,storageBucket:c.BUCKET,credential:admin.credential.applicationDefault()});
 await assert.rejects(admin.auth().getUser(state.user.uid),e=>e.code==='auth/user-not-found');
 const sdk=require('node:module').createRequire(require('node:path').join(c.ROOT,'functions/package.json')),db=sdk('firebase-admin/firestore').getFirestore(admin.app(),'aogaku-ai'),owner=db.doc('aiInputOwners/'+state.user.uid),helper=require('../functions/lib/ai/account-deletion');
 const own=await db.collection('aiSources').where('ownerUserId','==',state.user.uid).get();assert.equal(own.size,30);assert.deepEqual(own.docs.map(x=>x.id).sort(),state.sources.map(x=>x.sourceId).sort());
 for(let i=0;i<3&&(await owner.get()).get('state')==='deleting';i++){c.guard();await helper.continueAIAccountDeletion(state.user.uid);}
 assert.equal((await owner.get()).get('state'),'deleted');
 for(const source of state.sources){const ref=db.doc('aiSources/'+source.sourceId);assert.equal((await ref.get()).get('status'),'deleted');const runs=await v.read(`https://firestore.googleapis.com/v1/projects/${c.PROJECT}/databases/aogaku-ai/documents/aiSources/${source.sourceId}/runs?showMissing=true&pageSize=100`);assert(!runs.documents?.length,'Nested/missing-parent preview remains');}
 for(const prefix of ['ai-inputs','ai-derived'])assert(!(await v.read(`https://storage.googleapis.com/storage/v1/b/${c.BUCKET}/o?prefix=${encodeURIComponent(prefix+'/aogaku-ai/'+state.user.uid+'/')}`)).items?.length);
 const usage=await v.read(`https://firestore.googleapis.com/v1/projects/${c.PROJECT}/databases/aogaku-ai/documents/aiUsage/${state.user.uid}/periods`);assert(!usage.documents?.length);
 const after=await v.snapshot(),expected=op.load('after-complete');v.protectedCheck(expected,after);assert.deepEqual(expected.functions,after.functions);assert.equal(after.queue.state,'RUNNING');assert(!(await v.read(`https://cloudtasks.googleapis.com/v2/projects/${c.PROJECT}/locations/${c.REGION}/queues/aiProcessSource/tasks`)).tasks?.length);
 state.status='DEV_LATENCY_PASS_CLEANED';op.save('registry',state);op.save('cleanup-final',after);console.log('PASS own deleted Dev Auth owner; 30 sources/nested previews/storage/usage cleaned; minimal tombstones retained; queue RUNNING and protected state unchanged');await db.terminate();await admin.app().delete();}finally{fs.unlinkSync(credentialFile);delete process.env.GOOGLE_APPLICATION_CREDENTIALS;}}
if(require.main===module)main().catch(e=>{console.error('SAFE STOP own Dev cleanup '+e.name+' '+(e.code||''));process.exitCode=1});
